### ISSUE TITLE
Enable local cache throw exception

### ISSUE THREAD

**Issue by Yohahaha** [oap-project/gluten#1012]
**Describe the bug**
set spark.gluten.sql.columnar.backend.velox.cacheEnabled="true" to enable local cache.

```
java.lang.RuntimeException: Exception: VeloxRuntimeError
Error Source: RUNTIME
Error Code: INVALID_STATE
Reason: Could not allocate working memory mmap failed with 无法分配内存 for sizeClass 1
Retriable: False
Function: SizeClass
File: ../../velox/common/memory/MmapAllocator.cpp
Line: 455
Stack trace:
# 0  _ZN8facebook5velox7process10StackTraceC1Ei
# 1  _ZN8facebook5velox14VeloxExceptionC1EPKcmS3_St17basic_string_viewIcSt11char_traitsIcEES7_S7_S7_bNS1_4TypeES7_
# 2  _ZN8facebook5velox6detail14veloxCheckFailINS0_17VeloxRuntimeErrorERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEEEvRKNS1_18VeloxCheckFailArgsET0_
# 3  _ZN8facebook5velox6memory13MmapAllocator9SizeClassC1Emm
# 4  _ZN8facebook5velox6memory13MmapAllocatorC2ERKNS2_7OptionsE
# 5  _ZN6gluten16VeloxInitializer4InitESt13unordered_mapINSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEES7_St4hashIS7_ESt8equal_toIS7_ESaISt4pairIKS7_S7_EEE
# 6  _ZN6gluten16VeloxInitializerC1ERKSt13unordered_mapINSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEES7_St4hashIS7_ESt8equal_toIS7_ESaISt4pairIKS7_S7_EEE
# 7  Java_io_glutenproject_vectorized_ExpressionEvaluatorJniWrapper_nativeInitNative
# 8  0x00007f83c3ae8427
```

**To Reproduce**
```
  --conf spark.gluten.sql.enable.native.engine=${enable} \
  --conf spark.plugins=io.glutenproject.GlutenPlugin \
  --conf spark.gluten.sql.columnar.backend.lib=velox \
  --conf spark.shuffle.manager=org.apache.spark.shuffle.sort.ColumnarShuffleManager \
  --conf spark.gluten.sql.columnar.backend.velox.cacheEnabled="true" \
  --conf spark.sql.shuffle.partitions=1000 \
  --conf spark.driver.maxResultSize=2g \
  --conf spark.executor.instances=20 \
  --conf spark.executor.cores=5 \
  --conf spark.executor.memory=5G \
  --conf spark.executor.memoryOverhead=1g \
  --conf spark.memory.offHeap.enabled=true \
  --conf spark.memory.offHeap.size=25g \
```

**Expected behavior**

**Additional context**

**Comment by Yohahaha** [comment]
Hi @zhouyuan, does this feature has been fully supported? what expected conf should used here?

**Comment by zhouyuan** [comment]
Hi @Yohahaha 
the SSD caching framework is integrated into Gluten but not well tested. The issue is due to the hard-coded memory size for SSD caching:  
https://github.com/oap-project/gluten/blob/main/cpp/velox/compute/VeloxBackend.cc#L89

initially I'm thinking to using off-heap memory size, like (off-heap size or 50% * off-heap size), but haven't make this patch yet. 

Note: the memory allocation in velox is not 100% managed by Spark, some allocations via _mmap()_ are not tracked. We may need to fix those first  

Thanks, -yuan

**Comment by Yohahaha** [comment]
@zhouyuan  Thanks.
Is anyone working on enhance this feature? I would like take this.

**Comment by zhouyuan** [comment]
Hi @Yohahaha 

Sure, please go ahead 👍 . The caching feature is still naïve, e.g., unable to reuse old cache after spark context restart, unable to specify the cache replacement policies(LRU, FIFO, or just read-only), we could(should) iterate from this.

thanks, -yuan

**Comment by Yohahaha** [comment]
> unable to reuse old cache after spark context restart, unable to specify the cache replacement policies(LRU, FIFO, or just read-only)

That's sounds good. However, I prefer to make it works first and gain benefits from reading remote cloud storage.

I will close this issue and open another issue to support local cache.
Thanks. @zhouyuan
