### ISSUE TITLE
Gluten support local cache with Velox backend

### ISSUE THREAD

**Issue by Yohahaha** [oap-project/gluten#1013]
Gluten has been added codes for local cache, but it not works well. #1012 

This issue will try to make it works and gain benefits with cloud storage which has expensive scan.

**Comment by zhouyuan** [comment]
Yes, the cache memory allocation is using mmap(). Once SSD cached is enabled, the memory allocator will be registered as "default allocator", its capacity will be limited as the value configured here.

BR, -yuan
________________________________
