### ISSUE TITLE
[VL] SusbtraitToVeloxPlan error

### ISSUE THREAD

**Issue by FelixYBW** [oap-project/gluten#1028]
**Describe the bug**
Observed by customer
![image](https://user-images.githubusercontent.com/47296334/221767772-eccdc3d2-f2a5-4adb-8ebe-5daf8f46dac1.png)

**To Reproduce**
customer env.

**Comment by jinchengchenghh** [comment]
No. This is in SubstraitToVelox plan conversion, `SelectionNode` is not suported. which should be validated but seems not.

**Comment by JkSelf** [comment]
The filter condition may be scalar, AND, OR expression. The SelectionNode may be the core case.

**Comment by JkSelf** [comment]
@FelixYBW Can we get the physical plan for this case?

**Comment by rui-mo** [comment]
Tried to throw exception in `flattenConditions` as below.

```c++
void SubstraitVeloxPlanConverter::flattenConditions(
    const ::substrait::Expression& substraitFilter,
    std::vector<::substrait::Expression_ScalarFunction>& scalarFunctions,
    std::vector<::substrait::Expression_SingularOrList>& singularOrLists,
    std::vector<::substrait::Expression_IfThen>& ifThens) {
  VELOX_FAIL("Failed.");
```
But found the validation could take effect and scan fallbacked with success, so I'm not sure why fallback does not occur in this issue.

```shell
WARNING: Logging before InitGoogleLogging() is written to STDERR
E0303 10:28:57.100342 3581697 Exceptions.h:68] Line: ../../velox/substrait/SubstraitToVeloxPlan.cpp:1066, Function:flattenConditions, Expression:  Failed., Source: RUNTIME, ErrorCode: INVALID_STATE
ReadRel validation failed due to:Failed.
```
![Screenshot from 2023-03-03 03-10-06](https://user-images.githubusercontent.com/41687378/222622722-347584af-e555-418f-a879-de62290282bd.png)

**Comment by jinchengchenghh** [comment]
What's the config `spark.gluten.sql.enable.native.validation`? It should be true, I cannot find any code path can run to here with validation

**Comment by JkSelf** [comment]
[Here](https://github.com/oap-project/velox/blob/f420185ed52b4aae5bb45fcbb50655a1a0e3c069/velox/substrait/SubstraitToVeloxPlanValidator.cpp#L791) will call the `flattenConditions ` method in validation.

**Comment by jinchengchenghh** [comment]
Can we close this issue, it should have been fixed by https://github.com/oap-project/gluten/pull/952/files
