### ISSUE TITLE
Remove compute pid metric in shuffle operator.

### ISSUE THREAD

**Issue by Yohahaha** [oap-project/gluten#1039]
As discussed in https://github.com/oap-project/gluten/pull/998#discussion_r1117853033.

To remove this, we need to change common interface `io/glutenproject/vectorized/SplitResult`, both Velox backend and CK backend need to apply this change.

**Comment by Yohahaha** [comment]
Hi @zzcclp, Does this metric is used in CH backend?

**Comment by zzcclp** [comment]
Please leave this metric, I will raise another pr to modify some metrics about the CH backend.
