### ISSUE TITLE
[RFC] Spill support

### ISSUE THREAD

**Issue by zhanglistar** [oap-project/gluten#1046]
> (you don't have to strictly follow this form)

**Use case**
Used when 
input data is too large for  all memory processing, eg. hash agg, join, sort etc.

> A clear and concise description of what is the intended usage scenario is.

**Describe the solution you'd like**
Spill immediate data to disk to run query on low memory. There are two ways, one is like Photon, `To handle this, we separate the concept of memory reservations from allocations in Photon. A memory reservation asks for memory from Spark’s unified memory manager. Like all requests to the memory manager, this can cause a spill, where Spark asks some memory consumer to release memory to satisfy a new request. Pho- ton hooks into this memory consumer API, so Spark can ask Photon to spill data on behalf of other memory-consuming operators that are executing (e.g., a sort task in Spark may ask a Photon operator to spill). Similarly, Photon can make reservations that cause other Spark operators to spill, or cause Photon itself to spill (leading to a “recursive spill” where one Photon operator spills memory on behalf of another one). This differs slightly from many other data- base engines, where operators are given a fixed memory budget and can only “self-spill.” Spilling is dynamic because we often do not have information on how much data an operator will consume, especially if SQL operators are co-existing with user-defined code that also reserves memory.`
Another way is that we set per query memory config from user settings for physical execution layer and tell it to control the memory usage, this way is easy to implement, because both velox and clickhouse have supported spill in main operators like order by, hash aggregation, join etc, which is controlled by configuration.

We may implement the second first.

**Comment by zhztheplayer** [comment]
Thanks for opening this @zhanglistar 

Velox's spill was enabled by https://github.com/oap-project/gluten/commit/14d2eef937842d306ffef40d273f6175222d8a50 it's pretty much like your "second way", I think what we need at this time is too create some UT or some test utilities to emulate the scenario of having limited memory to trigger spills.

And indeed Gluten's memory allocator is already compatible with Spark's memory manager. I think what we require is to account native allocation accurately to it to report to Spark memory manager. But for now Velox's mmap allocations were out of this Gluten allocator routine.

**Comment by zhanglistar** [comment]
OK, ch backend already supports.
