### ISSUE TITLE
Subfield filters creation not supported for input type 'MAP<VARCHAR,BIGINT>'

### ISSUE THREAD

**Issue by PHILO-HE** [oap-project/gluten#1055]
java.lang.RuntimeException: Exception: VeloxRuntimeError
Error Source: RUNTIME
Error Code: NOT_IMPLEMENTED
Reason: Subfield filters creation not supported for input type 'MAP<VARCHAR,BIGINT>'
Retriable: False
Function: mapToFilters
File: ../../velox/substrait/SubstraitToVeloxPlan.cpp
Line: 1945
Stack trace:

\# 0 facebook::velox::VeloxException::VeloxException(char const*, unsigned long, char const*, std::basic_string_view<char, std::char_traits<char> >, std::basic_string_view<char, std::char_traits<char> >, std::basic_string_view<char, std::char_traits<char> >, std::basic_string_view<char, std::char_traits<char> >, bool, facebook::velox::VeloxException::Type, std::basic_string_view<char, std::char_traits<char> >)
\# 1 void facebook::velox::detail::veloxCheckFail<facebook::velox::VeloxRuntimeError, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&>(facebook::velox::detail::VeloxCheckFailArgs const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)
\# 2 facebook::velox::substrait::SubstraitVeloxPlanConverter::mapToFilters(std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > const&, std::vector<std::shared_ptr<facebook::velox::Type const>, std::allocator<std::shared_ptr<facebook::velox::Type const> > > const&, std::unordered_map<unsigned int, std::shared_ptr<facebook::velox::substrait::SubstraitVeloxPlanConverter::FilterInfo>, std::hash<unsigned int>, std::equal_to<unsigned int>, std::allocator<std::pair<unsigned int const, std::shared_ptr<facebook::velox::substrait::SubstraitVeloxPlanConverter::FilterInfo> > > >)
\# 3 facebook::velox::substrait::SubstraitVeloxPlanConverter::toSubfieldFilters(std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > const&, std::vector<std::shared_ptr<facebook::velox::Type const>, std::allocator<std::shared_ptr<facebook::velox::Type const> > > const&, std::vector<substrait::Expression_ScalarFunction, std::allocator<substrait::Expression_ScalarFunction> > const&, std::vector<substrait::Expression_SingularOrList, std::allocator<substrait::Expression_SingularOrList> > const&)

**Comment by rui-mo** [comment]
Fallback works in my test if an exception is thrown from `mapToFilters`.

```c++
connector::hive::SubfieldFilters SubstraitVeloxPlanConverter::mapToFilters(
    const std::vector<std::string>& inputNameList,
    const std::vector<TypePtr>& inputTypeList,
    std::unordered_map<uint32_t, std::shared_ptr<FilterInfo>> colInfoMap) {
  VELOX_NYI("mapToFilters");
```
```shell
E0303 13:13:21.180364 3590228 Exceptions.h:68] Line: ../../velox/substrait/SubstraitToVeloxPlan.cpp:1914, Function:mapToFilters, Expression:  mapToFilters, Source: RUNTIME, ErrorCode: NOT_IMPLEMENTED
ReadRel validation failed due to:mapToFilters
```
