### ISSUE TITLE
[CORE] Handle the exception when task is interrupted.

### ISSUE THREAD

**Issue by jackylee-ch** [oap-project/gluten#1199]
**Describe the bug**
Currentlly, we meet some problems, such as null pointer or memory leak, when spark speculation is enabled. It seems that we need recheck the code and handle the Exception, such as `ClosedByInterruptException`, and then return it to Java side, rather than executor core dump.

**To Reproduce**
Run TPCDS with `spark.speculation=true`

**Expected behavior**
Only Exception is thrown.

**Comment by jinchengchenghh** [comment]
Can we close this issue? @jackylee-ch

**Comment by jackylee-ch** [comment]
> Can we close this issue? @jackylee-ch

Sorry for late response, we are still working on this.
