### ISSUE TITLE
[VL] Improve shuffle API

### ISSUE THREAD

**Issue by zhztheplayer** [oap-project/gluten#1205]
This targets to do some small-scale refactoring against shuffle write / read API, to make sure the upper-layer code structure is capable to maintain / extend, and is friendly to read.

The plan (respectively):

1. In Java, consolidate `GlutenColumnarBatchSerializer` and `CelebornColumnarBatchSerializer`
2. In C++, consolidate `CelebornXXSplitter`s and `XXSpliter`s
    * Add API `ShufflePartitionWriter` (or probably `shuffle::StreamWriter`), responsible for evicting / pushing binary partition data in different ways, depending on the implementation of Writer
      `ShufflePartitionWriter` is different from `ShuffleSplitter`. It only accepts binary data then write it out. `ShufflePartitionWriter` will be the underlying I/O writer as a member variable in each `ShuffleSplitter`
    * Add `CelebornShufflePartitionWriter`, and `FileShufflePartitionWriter`
3. Enable `CelebornShufflePartitionWriter` in `VeloxSpliter`
4. In C++, rename `XXSpliter` in `splitter.h` as `ArrowXXSplitter`

After the above is done:
1. Rename all Java/C++ `XXShuffleSplitter` / `XXSplitter` as `XXShuffleWriter`
  The components with name "Splitter" actually do far more than "splitting". They read, split, then write the data out to its destination. The name "ShuffleWriter" is also aligned with vanilla Apache Spark's naming convention

Be to do, not sure about the precedence for now:

1. Move Celeborn shuffle Java code into a new individual Maven module

**Comment by zhztheplayer** [comment]
@kerwin-zk @jinchengchenghh If you have any comments here.

**Comment by jinchengchenghh** [comment]
Very good, with this rename, we can also rename `SplitterBase` to `ShuffleStreamWriter`. A little wonder, do we need `Stream` in name?

**Comment by zhztheplayer** [comment]
> Very good, with this rename, we can also rename SplitterBase to ShuffleStreamWriter. A little wonder, do we need Stream in name?

`SplitterBase` Will be renamed to `ShuffleWriterBase` or something.

`ShuffleStreamWriter` will be a member variable in each `ShuffleWriter` implementation, only for writing binary data out. E.g if `CelebornShuffleStreamWriter` is set, `VeloxSplitter` will be capable to call Celeborn once it is about to evict data.

If the naming `ShuffleStreamWriter` is confusing, I'd name it as `shuffle::StreamWriter` or `ShufflePartitionWriter`, I am not sure about that yet.

**Comment by zhztheplayer** [comment]
Changed name of `ShuffleStreamWriter` to `ShufflePartitionWriter`.

**Comment by jinchengchenghh** [comment]
I will consider `ShuffleStreamWriter extends ShuffleWriter` at first sight, maybe `shuffle::PartitionWriter`  is better, not sure yet.

**Comment by zhztheplayer** [comment]
@jinchengchenghh I see. Thanks for your comment.

**Comment by zhztheplayer** [comment]
@kerwin-zk Can you recall the reason why we need this?

https://github.com/oap-project/gluten/blob/a04106623966f8cb384a2c64d89c02fbe18f0eb1/gluten-data/src/main/scala/io/glutenproject/vectorized/CelebornColumnarBatchSerializer.scala#L84-L116

I am not able to test against celeborn, but seems to me that if the underlying empty celeborn stream returns `-1` immediately, `GlutenColumnarBatchSerializer` can handle this as EoS then ends reading.

Was there anything unexpected shown when you used `GlutenColumnarBatchSerializer` for celeborn?

**Comment by kerwin-zk** [comment]
> 1. Rename all Java/C++ `XXShuffleSplitter` / `XXSplitter` as `XXShuffleWriter`
>    The components with name "Splitter" actually do far more than "splitting". They read, split, then write the data out to its destination. The name "ShuffleWriter" is also aligned with vanilla Apache Spark's naming convention.

@zhztheplayer ShuffleWriter is a specific class in Spark. Splitter is only a part of ShuffleWriter. It is not suitable to directly change to ShuffleWriter. Maybe you can consider ShuffleProcessor.

**Comment by kerwin-zk** [comment]
> @kerwin-zk Can you recall the reason why we need this?
> 
> https://github.com/oap-project/gluten/blob/a04106623966f8cb384a2c64d89c02fbe18f0eb1/gluten-data/src/main/scala/io/glutenproject/vectorized/CelebornColumnarBatchSerializer.scala#L84-L116
> 
> I am not able to test against celeborn, but seems to me that if the underlying empty celeborn stream returns `-1` immediately, `GlutenColumnarBatchSerializer` can handle this as EoS then ends reading.
> 
> Was there anything unexpected shown when you used `GlutenColumnarBatchSerializer` for celeborn?

@zhztheplayer  Yes, as follows
```
Reader::Reader(std::shared_ptr<arrow::io::InputStream> in, std::shared_ptr<arrow::Schema> schema, ReaderOptions options)
    : in_(std::move(in)), options_(std::move(options)), schema_(std::move(schema)) {
# In the celeborn scenario, if the stream is empty, it will crash at this point
  GLUTEN_ASSIGN_OR_THROW(first_message_, arrow::ipc::ReadMessage(in_.get()))
.............
}
```

**Comment by kerwin-zk** [comment]
> > Splitter is only a part of ShuffleWriter. It is not suitable to directly change to ShuffleWriter. Maybe you can consider ShuffleProcessor.
> 
> Thanks for your advice. `ShuffleProcessor` is great but `ShuffleWriterProcessor` could be preferred in this speaking. But probably it's a little bit too long.
> 
> I think we don't have to worry much about the naming collision on `ShuffleWriter`. `ShuffleSplitter` does basically all the works derived from Java-side `ShuffleWriter`, the only different is that it's in C++. It's usual in Gluten to directly map a Java-side Spark component to C++ side with the same name, e.g. `ColumnarBatch`.
> 
> It's worth noting that we didn't have `ShuffleSplitter` on Java side. We used `ShuffleSplitterJniWrapper`.
> 
> And I went through current code of `CelebornHashBasedColumnarShuffleWriter` and `GlutenColumnarShuffleWriter`, then they both seem like the wrapper of C++ writer with some extra metrics and configurations. So overall I think it's safe to call the C++ `Splitter` as `Writer`. Can you double-check on that?

@zhztheplayer Yes. The main difference is metrics and configurations. I can also participate in this part of Shuffle refactoring, and you can assign part of the work to me if necessary.

**Comment by zhztheplayer** [comment]
> you can assign part of the work to me if necessary.

Thanks for helping, and feel free to pick from the list :)

Besides I may suggest getting started with merging GlutenColumnarBatchSerializer and CelebornColumnarBatchSerializer, and give some time to let others to check on the other parts of the plan.

**Comment by zhztheplayer** [comment]
> merging GlutenColumnarBatchSerializer and CelebornColumnarBatchSerializer

@kerwin-zk Would you like to take this? By going through your comment I think it's possible to have a fix for it.

**Comment by kerwin-zk** [comment]
> > merging GlutenColumnarBatchSerializer and CelebornColumnarBatchSerializer
> 
> @kerwin-zk Would you like to take this? By going through your comment I think it's possible to have a fix for it.

@zhztheplayer OK. I'll handle this.

**Comment by jackylee-ch** [comment]
@zhztheplayer Is is possible to move celebern to a extra module and user can choose whether to use it?

**Comment by zuochunwei** [comment]
> Very good, with this rename, we can also rename `SplitterBase` to `ShuffleStreamWriter`. A little wonder, do we need `Stream` in name?

+1, I more like the name without `Stream`

**Comment by zuochunwei** [comment]
> > 1. Rename all Java/C++ `XXShuffleSplitter` / `XXSplitter` as `XXShuffleWriter`
> >    The components with name "Splitter" actually do far more than "splitting". They read, split, then write the data out to its destination. The name "ShuffleWriter" is also aligned with vanilla Apache Spark's naming convention.
> 
> @zhztheplayer ShuffleWriter is a specific class in Spark. Splitter is only a part of ShuffleWriter. It is not suitable to directly change to ShuffleWriter. Maybe you can consider ShuffleProcessor.

I like the name `ShuffleWriter` more, it is respond to the `ShuffleReader`, the two names represent the two ends of shuffle work

**Comment by zuochunwei** [comment]
> 
> `SplitterBase` Will be renamed to `ShuffleWriterBase` or something.
> 

how about `ShuffleWriter`, we don't need the base suffix, and let's keep this habit

**Comment by zuochunwei** [comment]
> @zhztheplayer Is is possible to move celebern to a extra module and user can choose whether to use it?

+1

**Comment by LuciferYang** [comment]
> @zhztheplayer Is is possible to move celebern to a extra module and user can choose whether to use it?
+1, It should not be coupled with specific implementations. In addition, it is not recommended to use third-party snapshot repositories, which can cause a lot of uncertainty

**Comment by CLTFOREVER** [comment]
@zhztheplayer @jinchengchenghh @zuochunwei   We have discuss the code refactoring for shuffle offline，here is the  Uml diagram after refactoring:
![1680757078514-image](https://user-images.githubusercontent.com/11614188/230275948-af569db4-7e5c-4a1e-b482-75b8faa7f745.png)
The plan for code refactoring (respectively):
1.Rename some unreasonable Class name，like:GlutenColumnarShuffleWriter->ColumnarShuffleWriter,SplitterBase->ShuffleWriter and so on
2.Add API Partitioner, responsible for computing partitionId info.
3.Add API PartitionWriter , responsible for evicting / pushing binary partition data in different ways, depending on the implementation of Writer
4.Enable CelebornPartitionWriter in VeloxShuffleWriter
If you have any other ideas, please add them

**Comment by zhztheplayer** [comment]
@zuochunwei Should we keep this open until we finish the sub-tasks?

**Comment by kerwin-zk** [comment]
I suggest closing the issue after completing all tasks.
