### ISSUE TITLE
[VL] Decimal  21 failed UTs

### ISSUE THREAD

**Issue by JkSelf** [oap-project/gluten#1217]
Here lists the failed unit tests when enable decimal type in gluen + velox backend.

- [ ]  GlutenDataFrameSuite
       SPARK-22271: mean overflows and returns null for some decimal variables ---chengcheng
       SPARK-35955: Aggregate avg should not return wrong results for decimal overflow
       SPARK-28067: Aggregate sum should not return wrong results for decimal overflow
       SPARK-28067: sum of null decimal values
       SPARK-28224: Aggregate sum big decimal overflow

- [x] GlutenDataFrameAggregateSuite  ---Chengcheng
       SPARK-36926: decimal average mistakenly overflow

- [x] GlutenParquetIOSuite  ---Rui
       SPARK-34167: read LongDecimals with precision < 10, VectorizedReader false

- [x] GlutenParquetPartitionDiscoverySuite  ---Rui
      Resolve type conflicts - decimals, dates and timestamps in partition column

- [ ] GlutenParquetQuerySuite ---Rui
      SPARK-34212 Parquet should read decimals correctly

- [x]  GlutenCastWithAnsiOffSuite and  GlutenCastWithAnsiOnSuite 
       String to decimal: ---Chengcheng
       Fast fail for cast string type to decimal type
       data type casting
       Cast should output null for invalid strings when ANSI is not enabled.
       
     Others: ---Rui
       cast from date  
       SPARK-28470: Cast should honor nullOnOverflow property
       casting to fixed-precision decimals
       cast and add

- [ ] GlutenParquetQuerySuite  ---Rui
      SPARK-34212 Parquet should read decimals correctly

- [x] GlutenStatisticsCollectionSuite --Chengcheng
     analyze column command - result verification

- [x] GlutenParquetPartitionDiscoverySuite.
       Resolve type conflicts - decimals, dates and timestamps in partition column

- [x] GlutenSQLQueryTestSuite
      udf/udf-union.sql
      decimalArithmeticOperations.sql

**Comment by jinchengchenghh** [comment]
I will take `GlutenSQLQueryTestSuite`

**Comment by liujiayi771** [comment]
@JkSelf @rui-mo Some UTs fail because of ANSI mode, I find the [issue](https://github.com/facebookincubator/velox/issues/3869), It seems that the support of ANSI mode in velox has not yet been determined. I can add ANSI mode adaptation in agg node, but I think ANSI mode should have a global design, so should we ignore these UTs as they are now, and then adapt after velox has ANSI mode?

**Comment by JkSelf** [comment]
@rui-mo How do we deal with the ut with ansi mode now?

**Comment by rui-mo** [comment]
@liujiayi771 You're right. This part of doc describes how we handle ANSI ON cases for now.

**Comment by JkSelf** [comment]
Got it. Thanks Rui. @liujiayi771 Let us fallback the ansi on case to vanilla spark for failed decimal uts.

**Comment by rui-mo** [comment]
@liujiayi771 @JkSelf I think the fallback code is already there: https://github.com/oap-project/gluten/blob/main/gluten-core/src/main/scala/io/glutenproject/extension/columnar/TransformHintRule.scala#L121-L128. Maybe we can check whether it can work well for the ANSI ON cases.

**Comment by liujiayi771** [comment]
> 

Ok, the current idea is fallback, right? In this case, I need to return null during overflow, but the current implementation will throw an exception. I will fix it.

**Comment by liujiayi771** [comment]
> @liujiayi771 @JkSelf I think the fallback code is already there: https://github.com/oap-project/gluten/blob/main/gluten-core/src/main/scala/io/glutenproject/extension/columnar/TransformHintRule.scala#L121-L128. Maybe we can check whether it can work well for the ANSI ON cases.

Ok, the current idea is fallback, right? In this case, I need to return null during overflow, but the current implementation will throw an exception. I will fix it.

**Comment by rui-mo** [comment]
> Ok, the current idea is fallback, right? In this case, I need to return null during overflow, but the current implementation will throw an exception. I will fix it.

@liujiayi771 Yes, the current idea is to fallback when ANSI is ON, thanks.

**Comment by liujiayi771** [comment]
SPARK-35955: Aggregate avg should not return wrong results for decimal overflow
SPARK-28067: Aggregate sum should not return wrong results for decimal overflow
SPARK-28067: sum of null decimal values
SPARK-28224: Aggregate sum big decimal overflow

fixed.
