### ISSUE TITLE
Run single test in gluten-ut by mvn throw exception

### ISSUE THREAD

**Issue by Yohahaha** [oap-project/gluten#1220]
**Describe the bug**
When execute `mvn clean install -pl gluten-ut/spark32  -P spark-3.2,backends-velox,spark-ut -Dsuites="org.apache.spark.sql.GlutenStringFunctionsSuite"`, maven will throw exception if test file contains shim class.

```
[ERROR] /mnt/disk1/oap-gluten/gluten-ut/spark32/src/test/scala/org/apache/spark/sql/GlutenDynamicPartitionPruningSuite.scala:275: error: Symbol 'type org.apache.spark.sql.execution.datasources.v2.BatchScanExecShi
m' is missing from the classpath.
[ERROR] This symbol is required by 'class io.glutenproject.execution.BatchScanExecTransformer'.
[ERROR] Make sure that type BatchScanExecShim is in your classpath and check for conflicting dependencies with `-Ylog-classpath`.
[ERROR] A full rebuild may help if 'BatchScanExecTransformer.class' was compiled against an incompatible version of org.apache.spark.sql.execution.datasources.v2.
[ERROR]       case s: BatchScanExecTransformer => s.runtimeFilters.collect {
[ERROR]               ^
[ERROR] /mnt/disk1/oap-gluten/gluten-ut/spark32/src/test/scala/org/apache/spark/sql/GlutenDynamicPartitionPruningSuite.scala:275: error: value runtimeFilters is not a member of io.glutenproject.execution.BatchSca
nExecTransformer
[ERROR]       case s: BatchScanExecTransformer => s.runtimeFilters.collect {
[ERROR]                                             ^
```

If use `mvn clean install -pl gluten-ut/spark32 -am -P spark-3.2,backends-velox,spark-ut -Dsuites="org.apache.spark.sql.GlutenStringFunctionsSuite"` to build shim jar as upstream dependency, maven will not found specific test file.

```
[INFO] ScalaTest report directory: /mnt/disk1/oap-gluten/shims/spark32/target/scalatest-reports
*** RUN ABORTED ***
  java.lang.ClassNotFoundException: org.apache.spark.sql.GlutenStringFunctionsSuite
  at java.net.URLClassLoader.findClass(URLClassLoader.java:387)
  at java.lang.ClassLoader.loadClass(ClassLoader.java:418)
  at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
  at org.scalatest.tools.Runner$.$anonfun$doRunRunRunDaDoRunRun$6(Runner.scala:1176)
  at org.scalatest.tools.Runner$.$anonfun$doRunRunRunDaDoRunRun$6$adapted(Runner.scala:1174)
  at scala.collection.TraversableLike.noneIn$1(TraversableLike.scala:319)
  at scala.collection.TraversableLike.filterImpl(TraversableLike.scala:385)
  at scala.collection.TraversableLike.filterImpl$(TraversableLike.scala:297)
  at scala.collection.AbstractTraversable.filterImpl(Traversable.scala:108)
  at scala.collection.TraversableLike.filter(TraversableLike.scala:395)
```

**To Reproduce**

mvn clean install -pl gluten-ut/spark32  -P spark-3.2,backends-velox,spark-ut -Dsuites="org.apache.spark.sql.GlutenStringFunctionsSuite"

mvn clean install -pl gluten-ut/spark32 -am -P spark-3.2,backends-velox,spark-ut -Dsuites="org.apache.spark.sql.GlutenStringFunctionsSuite"

**Expected behavior**

**Additional context**

**Comment by jinchengchenghh** [comment]
You can use ` mvn clean install -Pbackends-velox -Pspark-ut -DwildcardSuites=org.apache.spark.sql.GlutenStringFunctionsSuite` to run the single suite

**Comment by Yohahaha** [comment]
> You can use  mvn clean install -Pbackends-velox -Pspark-ut -DwildcardSuites=org.apache.spark.sql.GlutenStringFunctionsSuite to run the single suite

Thanks @jinchengchenghh , this command looks good, but it seems compile all modules then find suites mathced wildcard.
`-pl` would be more effiecient.

I compared two command's elapsed time:
`mvn clean install -Pbackends-velox -Pspark-ut -Pspark-3.3 -DwildcardSuites=org.apache.spark.sql.GlutenStringFunctionsSuite`
![image](https://user-images.githubusercontent.com/34979747/228147156-0a04d9d0-2a8c-4ef6-8beb-8fb79d811fee.png)

`mvn clean install -pl gluten-ut/spark33 -P spark-3.3,backends-velox,spark-ut -Dsuites="org.apache.spark.sql.GlutenStringFunctionsSuite"`
![image](https://user-images.githubusercontent.com/34979747/228146970-62bc0885-10e5-4c15-b611-16357ce8dcae.png)

**Comment by jinchengchenghh** [comment]
Can you also add this command to document? I always run one test by intellij, it is very fast. You can have a try.

**Comment by PHILO-HE** [comment]
Assume this issue is fixed. Please re-open it if needed. Thanks!
