### ISSUE TITLE
[VL] Unit case VeloxStringFunctionsSuite.sha1 and sha2 failed on CentOS 7

### ISSUE THREAD

**Issue by jackylee-ch** [oap-project/gluten#1232]
**Describe the bug**
We are running unit tests with spark 3.3 on CentOS 7 and we found the `VeloxStringFunctionsSuite.sha1` and `VeloxStringFunctionsSuite.sha2` tests are failed with `malloc(): invalid size (unsorted)`.

**To Reproduce**
run unit tests on CentOS7

**Expected behavior**
pass unit tests.

**Comment by jinchengchenghh** [comment]
Can you try https://github.com/oap-project/gluten/blob/main/docs/developers/MicroBenchmarks.md to run the benchmark in cpp side? And use Valgrind to detect the memory issue.

We don't have centos7 environment, and centos7 is not officially supported in gluten

**Comment by zhouyuan** [comment]
closed by recent fixes on string related functions, feel free to re-open if this still stands
