### ISSUE TITLE
Support parquet write in Gluten with velox backend

### ISSUE THREAD

**Issue by JkSelf** [oap-project/gluten#1245]
**Is your feature request related to a problem or challenge? Please describe what you are trying to do.**
(This section helps developers understand the context and *why* for this feature, in addition to  the *what*)

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by PengleiShi** [comment]
Hi @JkSelf  , is there a benckmark comparing gluten parquet write with vanilla spark write?

**Comment by JkSelf** [comment]
@PengleiShi  We haven't started doing performance comparisons yet. We compared arrow parquet write with vanilla spark parquet write on arrow backend before, and there will be a performance improvement of 1.28x. The parquet write of the velox backend essentially uses the arrow parquet write, so the performance improvement is expected to be similar to that of the parquet write of the arrow backend.

**Comment by zhouyuan** [comment]
closing as it's already done
