### ISSUE TITLE
Spend too many time logging while reading a large mount of files with soft-affinity is on

### ISSUE THREAD

**Issue by jackylee-ch** [oap-project/gluten#1357]
**Describe the bug**
The job gets stuck in log printing for a long time while trying to read a large amount of files.
<img width="1435" alt="image" src="https://user-images.githubusercontent.com/10897625/231964479-2c9deadf-867a-46b7-a567-113d74a66380.png">

**Expected behavior**
Use DEBUG log level as default, and user can choose whether to see it.

**Comment by zzcclp** [comment]
Done
