### ISSUE TITLE
Support first, last, nth_value functions

### ISSUE THREAD

**Issue by Yohahaha** [oap-project/gluten#1371]

**Comment by zhli1142015** [comment]
Hello @Yohahaha ,
Thanks for opening this, may I know when this will be completed, we need these functions also.

**Comment by Yohahaha** [comment]
Hi @zhli1142015 

first/last has already done in velox side, but I find some problems when implement first/last in gluten side, these will be support in next week when I back to office.

You could pick nth_value if you like, we have not start to support it.

**Comment by zhli1142015** [comment]
sure, thanks, let me check nth_value
