### ISSUE TITLE
Could we fix and run Velox UT when change oap/velox code?

### ISSUE THREAD

**Issue by Yohahaha** [oap-project/gluten#1398]
oap/velox does not have issue module, so I open it here.

I build and run basic UT for oap/velox with below command, and some UT were failed.
```
make EXTRA_CMAKE_FLAGS="-DVELOX_ENABLE_PARQUET=ON -DVELOX_BUILD_TESTING=ON -DVELOX_BUILD_TEST_UTILS=ON"
cd _build/release && ctest -j 32 --output-on-failure

# output
91% tests passed, 17 tests failed out of 195

Total Test time (real) =  56.85 sec

The following tests did not run:
         55 - */MemoryPoolTest.memoryLeakCheck/* (Disabled)

The following tests FAILED:
        114 - velox_type_test (Failed)
        121 - velox_row_test (Failed)
        122 - velox_expression_test (Failed)
        124 - velox_dwio_common_test (Failed)
        157 - velox_dwrf_e2e_filter_test (Failed)
        167 - velox_dwio_parquet_tpch_test (Failed)
        169 - velox_dwio_duckdb_parquet_table_scan_test (Failed)
        172 - velox_parquet_e2e_filter_test (SEGFAULT)
        182 - velox_windows_test (SEGFAULT)
        183 - velox_aggregates_test (SEGFAULT)
        184 - velox_functions_test (Failed)
        185 - velox_functions_spark_aggregates_test (Failed)
        186 - velox_functions_spark_test (Failed)
        189 - velox_hdfs_file_test (SEGFAULT)
        190 - velox_hive_connector_test (Failed)
        192 - velox_exec_test (Subprocess aborted)
        196 - velox_plan_conversion_test (Failed)
Errors while running CTest
```

I'm curious about why we does not run Velox UT when change related code.
CC @FelixYBW @zhouyuan

**Comment by zhejiangxiaomai** [comment]
@Yohahaha Thanks, we start to fix all UTs. Today I make a simple analysis. We are solving these problems. And they are stable recurring problems. 

<html xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:dt="uuid:C2F41010-65B3-11d1-A29F-00AA00C14882"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=OneNote.File>
<meta name=Generator content="Microsoft OneNote 15">
</head>

<body lang=zh-CN style='font-family:Calibri;font-size:11.0pt'>


<div style='direction:ltr'>



Case | Detail
-- | --
velox_type_test | [  FAILED    ] SubfieldTest.invalidPaths   [  FAILED    ] SubfieldTest.basic   [  FAILED    ] SubfieldTest.prefix   [  FAILED    ] DateTimeUtilTest.fromDateStrInvalid
velox_row_test | [  FAILED    ]   UnsafeRowComplexBatchDeserializerTests.UnsafeRowDeserializationRowsTests   [  FAILED    ] UnsafeRowComplexBatchDeserializerTests.UnsafeRowDeserializationTests   [  FAILED    ]   UnsafeRowComplexBatchDeserializerTests.UnsafeRowDeserializationRows2Tests
velox_expression_test | [  FAILED    ] CastExprTest.decimalToInt   [  FAILED    ] CastExprTest.varcharToDecimal
velox_dwio_common_test | [  FAILED    ] BitConcatenationTests.basic
velox_dwrf_e2e_filter_test | [  FAILED    ] E2EFilterTest.filterStruct   [  FAILED    ] E2EFilterTest.metadataFilter
velox_dwio_parquet_tpch_test | [  FAILED    ] ParquetTpchTestBase/MultiParquetTpchTest.Q1/0   [  FAILED    ] ParquetTpchTestBase/MultiParquetTpchTest.Q3/0   [  FAILED    ] ParquetTpchTestBase/MultiParquetTpchTest.Q5/0   [  FAILED    ] ParquetTpchTestBase/MultiParquetTpchTest.Q6/0   [  FAILED    ] ParquetTpchTestBase/MultiParquetTpchTest.Q7/0   [  FAILED    ] ParquetTpchTestBase/MultiParquetTpchTest.Q8/0   [  FAILED    ] ParquetTpchTestBase/MultiParquetTpchTest.Q9/0   [  FAILED    ] ParquetTpchTestBase/MultiParquetTpchTest.Q10/0   [  FAILED    ] ParquetTpchTestBase/MultiParquetTpchTest.Q12/0   [  FAILED    ] ParquetTpchTestBase/MultiParquetTpchTest.Q13/0   [  FAILED    ] ParquetTpchTestBase/MultiParquetTpchTest.Q14/0   [  FAILED    ] ParquetTpchTestBase/MultiParquetTpchTest.Q15/0   [  FAILED    ] ParquetTpchTestBase/MultiParquetTpchTest.Q16/0   [  FAILED    ] ParquetTpchTestBase/MultiParquetTpchTest.Q17/0   [  FAILED    ] ParquetTpchTestBase/MultiParquetTpchTest.Q18/0   [  FAILED    ] ParquetTpchTestBase/MultiParquetTpchTest.Q19/0   [  FAILED    ] ParquetTpchTestBase/MultiParquetTpchTest.Q20/0   [  FAILED    ] ParquetTpchTestBase/MultiParquetTpchTest.Q21/0   [  FAILED    ] ParquetTpchTestBase/MultiParquetTpchTest.Q22/0
velox_dwio_duckdb_parquet_table_scan_test | [  FAILED    ] ParquetTableScanTest.basic   [  FAILED    ] ParquetTableScanTest.countStar
velox_parquet_e2e_filter_test | [  FAILED    ] E2EFilterTest.boolean   [  FAILED    ] E2EFilterTest.integerDirect   [  FAILED    ] E2EFilterTest.compression   [  FAILED    ] E2EFilterTest.integerDictionary   [  FAILED    ] E2EFilterTest.floatAndDoubleDirect   [  FAILED    ] E2EFilterTest.floatAndDouble   [  FAILED    ] E2EFilterTest.shortDecimalDictionary   [  FAILED    ] E2EFilterTest.shortDecimalDirect   [  FAILED    ] E2EFilterTest.longDecimalDictionary   [  FAILED    ] E2EFilterTest.longDecimalDirect   [  FAILED    ] E2EFilterTest.stringDirect   [  FAILED    ] E2EFilterTest.stringDictionary   [  FAILED    ] E2EFilterTest.dedictionarize   [  FAILED    ] E2EFilterTest.filterStruct   [  FAILED    ] E2EFilterTest.list   [  FAILED    ] E2EFilterTest.metadataFilter   [  FAILED    ] E2EFilterTest.subfieldsPruning   [  FAILED    ] E2EFilterTest.map   [  FAILED    ] E2EFilterTest.varbinaryDirect   [  FAILED    ] E2EFilterTest.varbinaryDictionary   [  FAILED    ] E2EFilterTest.largeMetadata
velox_windows_test | nullptr   core
velox_aggregates_test | [  FAILED    ] AggregateFunctionAdapterTest.avgPartial   nullptr   core
velox_functions_test | [  FAILED    ] 5 tests, listed below:   [  FAILED    ] DateTimeFunctionsTest.year   [  FAILED    ] DateTimeFunctionsTest.yearDate   [  FAILED    ] DateTimeFunctionsTest.yearTimestampWithTimezone   [  FAILED    ] DecimalArithmeticTest.sparkMultiply   [  FAILED    ] StringFunctionsTest.substrNegativeStarts
velox_functions_spark_aggregates_test | [  FAILED    ] BloomFilterAggAggregateTest.bloomFilter
velox_functions_spark_test | [  FAILED    ] PmodTest: SetUpTestSuite or TearDownTestSuite   [  FAILED    ] RemainderTest: SetUpTestSuite or TearDownTestSuite   [  FAILED    ] ArithmeticTest: SetUpTestSuite or TearDownTestSuite   [  FAILED    ] CeilFloorTest: SetUpTestSuite or TearDownTestSuite   [  FAILED    ] ArraySortTest: SetUpTestSuite or TearDownTestSuite   [  FAILED    ] BitwiseTest: SetUpTestSuite or TearDownTestSuite   [  FAILED    ] EqualNullSafeTest: SetUpTestSuite or TearDownTestSuite   [  FAILED    ] DateTimeFunctionsTest: SetUpTestSuite or TearDownTestSuite   [  FAILED    ] ElementAtTest: SetUpTestSuite or TearDownTestSuite   [  FAILED    ] DateTimeTest: SetUpTestSuite or TearDownTestSuite   [  FAILED    ] HashTest: SetUpTestSuite or TearDownTestSuite   [  FAILED    ] InTest: SetUpTestSuite or TearDownTestSuite   [  FAILED    ] LeastTest: SetUpTestSuite or TearDownTestSuite   [  FAILED    ] GreatestTest: SetUpTestSuite or TearDownTestSuite   [  FAILED    ] MapTest: SetUpTestSuite or TearDownTestSuite   [  FAILED    ] RegexFunctionsTest: SetUpTestSuite or TearDownTestSuite   [  FAILED    ] SizeTest: SetUpTestSuite or TearDownTestSuite   [  FAILED    ] SortArrayTest: SetUpTestSuite or TearDownTestSuite   [  FAILED    ] SplitTest: SetUpTestSuite or TearDownTestSuite   [  FAILED    ] StringTest: SetUpTestSuite or TearDownTestSuite   [  FAILED    ] XxHash64Test: SetUpTestSuite or TearDownTestSuite   [  FAILED    ] MightContainTest: SetUpTestSuite or TearDownTestSuite
velox_hive_connector_test | [  FAILED    ] HiveConnectorTest.makeScanSpec_requiredSubfields_multilevel   [  FAILED    ] HiveConnectorTest.makeScanSpec_requiredSubfields_mergeFields   [  FAILED    ] HiveConnectorTest.makeScanSpec_requiredSubfields_mergeArray   [  FAILED    ] HiveConnectorTest.makeScanSpec_requiredSubfields_mergeMap   [  FAILED    ] HiveConnectorTest.makeScanSpec_requiredSubfields_allSubscripts
velox_exec_test | core dumped



</div>


</body>

</html>

**Comment by Yohahaha** [comment]
Thanks for clarify! @zhouyuan @zhejiangxiaomai

**Comment by FelixYBW** [comment]
@zhouyuan let's add UT check in our private velox repo when submitting PR. our velox repo is designed to hold tmp PR which will upstream eventually, but it doesn't mean our temp PR can bypass Velox UT.

**Comment by FelixYBW** [comment]
Let's keep this open until we fix the current Velox UTs.

**Comment by zhouyuan** [comment]
@FelixYBW yes, that's something we missed since the beginning, @zhejiangxiaomai is working hard to solve this

-yuan
