### ISSUE TITLE
[CH] cast function should cosider the input type 

### ISSUE THREAD

**Issue by shuai-xu** [oap-project/gluten#1431]
**Describe the bug**
Now all cast functions are translated without considering the input type. For example, cast a column to  int64 all use the toInt64 function in clickhouse, but if the input column contains null value, the default toInt64 funtion will throw exception.   

**Expected behavior**
We should use correct function such as toInt64OrNull according to the input type.

**Comment by shuai-xu** [comment]
select *
from xxx
where from_unixtime(cast(ts/1000000 as bigint),'yyyy-mm-dd') between date_sub(to_date('2023-03-15'), 360) and date_sub(to_date('2023-03-15'), 90+1)

**Comment by taiyang-li** [comment]
Let's do it
