### ISSUE TITLE
[VL] Support timestamp on Velox backend

### ISSUE THREAD

**Issue by rui-mo** [oap-project/gluten#1433]
Phase 1:
- [x] Timestamp data conversions, including r2c, c2r etc.
- [x] Timestamp split
- [x] Timestamp Scan (TODO: support timestamp int96 type)
https://github.com/oap-project/velox/pull/205

Phase 2:
- [ ] Timestamp functions
- ToUnixTimestamp
- UnixTimestamp
- GetTimestamp
- Hour
- Minute
- Second
- SecondWithFraction
- SecondsToTimestamp
- MillisToTimestamp
- MicrosToTimestamp
- Cast from timestamp
- Cast to timestamp
- CurrentTimestamp
- Now
- LocalTimestamp
- CurrentBatchTimestamp
- CastTimestampNTZToLong
- FromUnixTime
- TimeAdd
- DatetimeSub
- FromUTCTimestamp
- ToUTCTimestamp
- TimestampAddYMInterval
- ParseToTimestamp
- TruncTimestamp
- MakeTimestamp
- SubtractTimestamps
- SubtractTimestamps
- TimestampAdd
- TimestampDiff

- [ ] Timezone
- ConvertTimezone

Phase 3: 

- [ ] Enable operators including Filter/Project/Sort/Agg/Hash-partition Shuffle.

**Comment by FelixYBW** [comment]
@rui-mo do you have an update of this thread? couple of functions are already supported I think.

**Comment by rui-mo** [comment]
Updated the status on timestamp cast. Thanks.

**Comment by zhouyuan** [comment]
Cc: @Mariamalmesfer

**Comment by Mariamalmesfer** [comment]
did some  analysis on **SecondsToTimestamp**, and it looks like it may already be supported end-to-end.
@rui-mo can please confirm this ?

**Comment by rui-mo** [comment]
> did some analysis on **SecondsToTimestamp**, and it looks like it may already be supported end-to-end. [@rui-mo](https://github.com/rui-mo) can please confirm this ?

@Mariamalmesfer I updated the list, thanks.

**Comment by Mariamalmesfer** [comment]
@rui-mo I checked TruncTimestamp (date_trunc) and it looks supported.

There is already a test in DateFunctionsValidateSuite:
https://github.com/apache/incubator-gluten/blob/e3ba96191200878a4da8ed587b8d51562dc080c4/backends-velox/src/test/scala/org/apache/gluten/functions/DateFunctionsValidateSuite.scala#L131

**Comment by rui-mo** [comment]
@Mariamalmesfer Thanks. The list has been updated.

**Comment by Mariamalmesfer** [comment]
I’m currently working on `CurrentTimestamp` , `Now`, `LocalTimestamp`, and `Extract`.
Others can pick up any remaining functions
cc: @sh-shamsan
