### ISSUE TITLE
Align the expression doTransform method for different backends

### ISSUE THREAD

**Issue by rui-mo** [oap-project/gluten#1439]
**Is your feature request related to a problem or challenge? Please describe what you are trying to do.**

Currently, different doTransform logics can be used for different backends. But as we enlarge the coverage of functions support, cases like this will continue to increase. To have better code design and improve the maintainability, we suggest generating aligned Substrait plan for expressions.

**Describe the solution you'd like**

Gluten generates aligned Substrait plan for expressions, and each backend is in charge of solving the compatibilty issues during the conversion from Substrait to compute node.

**Additional context**

- Specially aligned with CH backend:

- [ ] Md5Transformer

- [ ] PosExplodeTransformer

- [ ] StringTranslateTransformer

- [ ] StringLocateTransformer

- [ ] RegExpReplaceTransformer

- [ ] GetMapValueTransformer

- [ ] DateDiffTransformer

- [ ] ToUnixTimestampTransformer

- [ ] LikeTransformer

- [ ] SequenceTransformer

- Specially aligned with Velox backend:

- [ ] CheckOverflowTransformer

- [ ] MakeDecimalTransformer

**Comment by rui-mo** [comment]
cc @zzcclp @PHILO-HE

**Comment by lgbo-ustc** [comment]
cc @taiyang-li

**Comment by rui-mo** [comment]
If it is really hard or nearly impossible to handle the compatibility issues for certain function in native backend, we would suggest conducting module separation by using `SparkPlanExecApi` to genrate different classes for each backend.
