### ISSUE TITLE
[CH] parquet and orc reader use the wrong settings for insensitive case

### ISSUE THREAD

**Issue by shuai-xu** [oap-project/gluten#1441]
**Describe the bug**
ORC and Parquet reader in gluten use the FormatSettings.use_lowercase_column_name to judge whether convert the column names to lower case, but this flag is not set and not used in clickhouse.

**Expected behavior**
Should use FormatSettings.parquet.case_insensitive_column_matching and FormatSettings.orc.case_insensitive_column_matching instead.

**Comment by taiyang-li** [comment]
It is fixed now.

**Comment by taiyang-li** [comment]
fixed by : 
- https://github.com/oap-project/gluten/pull/1390
- https://github.com/oap-project/gluten/pull/1578
- https://github.com/oap-project/gluten/pull/1991
