### ISSUE TITLE
[CH] columns may be different in type in union 

### ISSUE THREAD

**Issue by shuai-xu** [oap-project/gluten#1466]
**Describe the bug**
In a sql contains union, the two columns with same name may be differnt in type, one is nullalbe while the other not. It will throw exception when merge them.

**Expected behavior**
I think there are two possiable way to fix it. 1: judge the column type when merging in shuffle splitter. 2: check and uniform the column types when override the plan.

**Comment by taiyang-li** [comment]
fixed by https://github.com/oap-project/gluten/pull/1901
