### ISSUE TITLE
[VL] Unit tests with incorrect result

### ISSUE THREAD

**Issue by rui-mo** [oap-project/gluten#1478]
- [x] "cast from float"   --feilong
- [x] "cast from double"  --feilong
- [x] "from decimal"   --rui
- [x] "cast string to date #&#8203;2"  --feilong
- [x] "casting to fixed-precision decimals" --rui
- [x] "cast from date"  --feilong
- [x] "SPARK-32828: cast from a derived user-defined type to a base type" --rui
- [x] "Fast fail for cast string type to decimal type"  --rui
- [x] "missing cases - from boolean" --feilong
- [x] "Fast fail for cast string type to decimal type in ansi mode"  --rui
- [x] "Fast fail for cast string type to decimal type in ansi mode" --rui
- [x] "Fast fail for cast string type to decimal type in ansi mode" --rui
- [x] "Fast fail for cast string type to decimal type in ansi mode" --rui
- [x] "default" --jian
- [x] "decimal" --jian
- [x] "seconds" -- rong
- [x] "ANSI: extract days, hours, minutes and seconds" -- rong
- [x] "SPARK-30633: xxHash with different type seeds" -- rong
- [x] "Map Concat"   --ke
- [x] "Shuffle"         -- ke
- [x] "DayOfYear"   --ke
- [x] "Year"             --ke
- [x] "Quarter"       --ke 
- [x] "Month"        --ke
- [x] "Day / DayOfMonth"  --ke
- [x] "DayOfWeek"     --ke
- [x] "MakeDecimal"  --ke
- [x] "BinaryComparison: lessThan" --yan
- [x] "BinaryComparison: LessThanOrEqual" --yan
- [x] "BinaryComparison: GreaterThan" --yan
- [x] "BinaryComparison: GreaterThanOrEqual" ---yan
- [x] "SPARK-32764: compare special double/float values" --yan
- [x] "cos" --hongze
- [x] "cosh" --hongze
- [x] "toDegrees" --hongze
- [x] "toRadians" --hongze
- [x] "cbrt" --hongze
- [x] "exp" --hongze
- [x] "log10" --hongze
- [x] "log2" --hongze
- [x] "pow" --hongze
- [x] "atan2" --hongze
- [x] "Substring"
- [x] "string for ascii" ---izchen
- [x] "replace" ---izchen
- [x] "MonotonicallyIncreasingID"
- [x] "SparkPartitionID"
- [x] "random"
- [x] "SPARK-9127 codegen with long seed"
- [x] "CreateMap" --rui
- [x] "MapFromArrays" --rui

Rui:
- [x] "SPARK-35711: cast timestamp without time zone to timestamp with local time zone"
- [x] "SPARK-35719: cast timestamp with local time zone to timestamp without timezone"
- [x] "DATE_FROM_UNIX_DATE", "TIMESTAMP_MICROS"
- [x] "extract the seconds part with fraction from timestamps"

**Comment by rui-mo** [comment]
These tests are ignored in https://github.com/oap-project/gluten/pull/1465.

**Comment by rui-mo** [comment]
This is a list of failed unit tests after fixing the result check.
cc @FelixYBW @weiting-chen @zhouyuan @PHILO-HE

**Comment by rui-mo** [comment]
> thank you, @rui-mo Is the timestamp enabled?
> 
> "SPARK-35711: cast timestamp without time zone to timestamp with local time zone" "SPARK-35719: cast timestamp with local time zone to timestamp without timezone"

@FelixYBW The casting function is offloaded to Velox because of lacking specific validation.

**Comment by Ma-Jian1** [comment]
> > thank you, @rui-mo Is the timestamp enabled?
> > "SPARK-35711: cast timestamp without time zone to timestamp with local time zone" "SPARK-35719: cast timestamp with local time zone to timestamp without timezone"
> 
> @FelixYBW The casting function is offloaded to Velox because of lacking specific validation.


seems `TimestampNTZType` is not supported in `getTypeNode`.

**Comment by rui-mo** [comment]
@Ma-Jian1 Updated the UT list, and I will take a look on the timestamp related ones. Thanks.

**Comment by Ma-Jian1** [comment]
"cast from float": `checkCast(-5.0f, true)` failed caused by `kCastIntByTruncate` is `true`.
then how can we judge when `kCastIntByTruncate` should be set? need some rules.

**Comment by Ma-Jian1** [comment]
"cast from double" is the same behavior as "cast from float"

**Comment by izchen** [comment]
I submitted a velox pr (https://github.com/facebookincubator/velox/pull/4631) last month. maybe using this pr can fix the inconsistent `substring` results. I can test it.

Also I can fix the other two functions（`string for ascii`, `replace`） in `GlutenStringExpressionsSuite` if no one is working on this.

**Comment by rui-mo** [comment]
> I submitted a velox pr ([facebookincubator/velox#4631](https://github.com/facebookincubator/velox/pull/4631)) last month. maybe using this pr can fix the inconsistent `substring` results. I can test it.
> 
> Also I can fix the other two functions（`string for ascii`, `replace`） in `GlutenStringExpressionsSuite` if no one is working on this.

@izchen That would be great. We can enable the related tests in Gluten after fixing incorrect result issue.

**Comment by PHILO-HE** [comment]
> "cast from float": `checkCast(-5.0f, true)` failed caused by `kCastIntByTruncate` is `true`. but if we close `kCastIntByTruncate`, then `checkCast(1.5f, 1.toByte), checkCast(1.5f, 1.toShort), checkCast(1.5f, 1), checkCast(1.5f, 1.toLong)` will failed. then how can we judge when `kCastIntByTruncate` should be set? need some rules.

It's just a semantic issue and cannot be fixed by setting config dynamically. We need to have a discussion with Velox community on such semantic conflicts. Please skip it. I will track it.

**Comment by yma11** [comment]
`"BinaryComparison: lessThan"
 "BinaryComparison: LessThanOrEqual"
 "BinaryComparison: GreaterThan"
 "BinaryComparison: GreaterThanOrEqual"`
I will look at these ones.

**Comment by Ma-Jian1** [comment]
working on `"default"` and will fix half of it.

**Comment by zhztheplayer** [comment]
Will pick GlutenMathExpressionsSuite

**Comment by marin-ma** [comment]
`"seconds"`, `"ANSI: extract days, hours, minutes and seconds"` in `GlutenIntervalExpressionsSuite` can be fixed with https://github.com/oap-project/gluten/pull/1697

**Comment by Ma-Jian1** [comment]
"decimal" wa fixed and opend by https://github.com/oap-project/gluten/pull/1735

**Comment by rui-mo** [comment]
Thanks for the work. Close this issue.
