### ISSUE TITLE
OneRowRelation will cause fallback

### ISSUE THREAD

**Issue by liujiayi771** [oap-project/gluten#1482]
**Describe the bug**
Some queries like `select length("gluten");` or `select md5("gluten")` will fallback because of the child whose output is empty. This code logic is in FallbackEmptySchemaRelation. If we make this situation bypass the detection of FallbackEmptySchemaRelation through some matching, an exception will be thrown in GlutenColumnarBatches and ArrowColumnarBatches because the column is 0. gluten need to support this kind of queries.

https://github.com/oap-project/gluten/blob/d9c38e6897f0b94687934cbf5ac68c12cda2bc96/gluten-data/src/main/java/io/glutenproject/columnarbatch/GlutenColumnarBatches.java#L56

https://github.com/oap-project/gluten/blob/d9c38e6897f0b94687934cbf5ac68c12cda2bc96/gluten-data/src/main/java/io/glutenproject/columnarbatch/ArrowColumnarBatches.java#L56
**To Reproduce**
`select length("gluten");`

**Expected behavior**
not fallback

**Comment by liujiayi771** [comment]
@rui-mo Is this by design?

**Comment by rui-mo** [comment]
> @rui-mo Is this by design?

@liujiayi771 I think this rule was added to enhance the robustness when the child's output is empty. Because in that case, we cannot know the if the child's output is from Velox, Arrow or vanilla Spark.

@zhztheplayer Do you have anything to add?

**Comment by zhztheplayer** [comment]
> @liujiayi771 I think this rule was added to enhance the robustness when the child's output is empty. Because in that case, we cannot know if the child's output is from Velox, Arrow or vanilla Spark.

Yes this explained the reason accurately. 

An intermediate columnar batch (aka native columnar batch) in Java should at least have one column: Because the first column should maintain the metadata of the whole batch. Because Spark (until 3.2) doesn't allow us to store metadata in the ColumnarBatch instance.

See also an unresolved issue https://github.com/oap-project/gluten/issues/540

**Comment by liujiayi771** [comment]
> > @rui-mo Is this by design?
> 
> @liujiayi771 I think this rule was added to enhance the robustness when the child's output is empty. Because in that case, we cannot know if the child's output is from Velox, Arrow or vanilla Spark.
> 
> @zhztheplayer Do you have anything to add?

Ok, although the two examples I mentioned above can be calculated natively, since the returned data has no column information, we should fallback to enhance the robustness.
