### ISSUE TITLE
[VL] break missed in https://github.com/oap-project/velox/blob/main/velox/type/Filter.cpp#L93

### ISSUE THREAD

**Issue by zhli1142015** [oap-project/gluten#1489]
**Describe the bug**
https://github.com/oap-project/velox/blob/main/velox/type/Filter.cpp#L93
is `break;` missed in line 93?

**Comment by zhli1142015** [comment]
@JkSelf  and @zhejiangxiaomai, CC.

**Comment by zhejiangxiaomai** [comment]
Thanks,  just fixed it. https://github.com/oap-project/velox/pull/217
