### ISSUE TITLE
[CH] parse null to nothing may cause problems

### ISSUE THREAD

**Issue by shuai-xu** [oap-project/gluten#1525]
**Describe the bug**
For a subtrait plan as:
<img width="511" alt="image" src="https://user-images.githubusercontent.com/20960838/234793224-b433f821-8ecb-4ed8-9762-a2ffa7873bf8.png">
gluten now convert the column to ColumnNothing, but ColumnNothing does not support many operation such as get64() and insertRangeSelective()

**Expected behavior**
It may need to covert the nothing to a nullable column accoding to the output type.

**Comment by taiyang-li** [comment]
Need to list reproducable steps.
