### ISSUE TITLE
Does gluten support other TPC-H SQL more than Q1/Q6 ?

### ISSUE THREAD

**Issue by frankliee** [oap-project/gluten#155]

**Comment by frankliee** [comment]
When only a part of query (e.g., the first level stage of scan-filter-project) is run by Velox, how much is faster than vanilla Spark?

**Comment by zhanglistar** [comment]
@zhouyuan What's the benchmark result? Can you share with us? Thanks.

**Comment by zhouyuan** [comment]
@zhanglistar yes, the results on example TPCH quereis will be published soon.

CC: @weiting-chen

**Comment by zhanglistar** [comment]
> @zhanglistar yes, the results on example TPCH quereis will be published soon.
> 
> CC: @weiting-chen

@zhouyuan Thanks for your information. Willing to see the results!

**Comment by zhanglistar** [comment]
@zhouyuan Have the TPC-H compare results now?

**Comment by zhouyuan** [comment]
@zhanglistar yes, the results are published here:
https://github.com/oap-project/gluten#performance
