### ISSUE TITLE
HDFS Support

### ISSUE THREAD

**Issue by frankliee** [oap-project/gluten#158]
The current version of velox seems only support S3, and does not support HDFS.
So, does gluten support HDFS path? or leverage fused HDFS as an alternative?

**Comment by zhanglistar** [comment]
Velox supports hive.

**Comment by jinchengchenghh** [comment]
Relevant to https://github.com/oap-project/gluten/issues/388

**Comment by mimitoling** [comment]
@rui-mo Can the master branch support hdfs parquet?

**Comment by mimitoling** [comment]
@rui-mo 
Can the master branch support hdfs parquet?

**Comment by rui-mo** [comment]
@mimitoling There are two pending PRs on hdfs support, [PR#388](https://github.com/oap-project/gluten/issues/388) and [PR#152](https://github.com/oap-project/gluten/pull/152). Some verification and testing work are still WIP.

**Comment by FelixYBW** [comment]
Velox already has libhdfs support, but the problem is that the we either needs to put all dependency libraries in jar or we need to manually install them on each worker node. Currently we have to create the script.
