### ISSUE TITLE
Fix readme files

### ISSUE THREAD

**Issue by dh20** [oap-project/gluten#1593]
**Describe the bug**

The current guidance will not allow users to find the correct document.
**To Reproduce**
no

**Expected behavior**
no

**Additional context**
The current user will encounter the following scenarios when querying documents, which will affect the experience
![image](https://user-images.githubusercontent.com/65940415/237057353-22c1c5b8-ccaa-4f53-ad6a-e6327a616584.png)

**Comment by zhouyuan** [comment]
closing by #1590
