### ISSUE TITLE
lint #include list in ch local-engine

### ISSUE THREAD

**Issue by taiyang-li** [oap-project/gluten#1612]
Currently, #include list in ch local-engine are sort of misorder.
- some headers files are quoted with "", while others are quoted with <>
- header files are not grouped by modules
- some headers files are included unnecessaryly.

**Comment by baibaichen** [comment]
@taiyang-li @liuneng1994  

I think we use clang format of clickhouse,  add this to  `cpp-ch/CMakelists.txt` 

```bash
find ./local-engine -regex '.*\.\(cc\|hpp\|cu\|c\|cpp\|h\)' -exec clang-format-15 --verbose --dry-run -i --style=file:./ClickHouse/.clang-format -i {} \;
```

We also need update [Docker](https://github.com/jidicula/clang-format-action/blob/main/clang-format-docker/Dockerfile) to include clang-format.

Developers should install  clang-format and run above command without `--dry-run`(should update doc)
