### ISSUE TITLE
_build/release/_deps: Np such file or directory

### ISSUE THREAD

**Issue by jiangjiguang** [oap-project/gluten#1615]
**Describe the bug**

**To Reproduce**
- git clone https://github.com/oap-project/gluten.git
- git checkout e6def13f50d86353e7e059b1bb881bf8c5ef66b5
- ./dev/builddeps-veloxbe.sh

**Expected behavior**

**Additional context**

**Comment by zhouyuan** [comment]
Hi @jiangjiguang,
can you please try the main branch today? It's due to some changes included in https://github.com/oap-project/gluten/pull/1384

-yuan

**Comment by zhouyuan** [comment]
closing, should be fixed in main branch
