### ISSUE TITLE
CI velox-backend-static-build-test failed.

### ISSUE THREAD

**Issue by Yohahaha** [oap-project/gluten#1617]
[velox-backend-static-build-test](https://github.com/oap-project/gluten/pull/1606#issuecomment-1545019687)

**Comment by Yohahaha** [comment]
@zhouyuan @zhejiangxiaomai @ccat3z

**Comment by ccat3z** [comment]
It caused by a linking issue in UT after https://github.com/oap-project/gluten/commit/f70b2c518c6109477e0f8e3c373d23227d8d42d4. I will open a new pr to fix it. We can disable tests in static build workflow temporary.

**Comment by zhouyuan** [comment]
@ccat3z 
https://github.com/oap-project/gluten/pull/1619
