### ISSUE TITLE
core dump in TPC-DS 99 Queries

### ISSUE THREAD

**Issue by fq-zhaang** [oap-project/gluten#1622]
**Describe the bug**
core dump happened in TPC-DS 99: sql04, sql11, sql23a, sql23b, q50, q67, q78, q80, 2 types of error:
1. Java out of direct memory
![image](https://github.com/oap-project/gluten/assets/11953339/312b4dec-e758-48c5-826f-531a6d045289)
2. memory leak
![20230512-153439(WeLinkPC)](https://github.com/oap-project/gluten/assets/11953339/deb2e465-10a0-4749-b637-e4fd77a41e5b)

**To Reproduce**
ubuntu 22.04
master: x86 40 cores CPU, memory 3765B
3 workers: x86 40 cores CPU, memory 375GB
Data scale: 3T
Run with :
```bash
spark-sql --master yarn \
--deploy-mode client \
--driver-cores 1 \
--driver-memory 5g \
--num-executors 6 \
--executor-cores 20 \
--executor-memory 5g \
--conf spark.task.cpus=1 \
--conf spark.memory.offHeap.enabled=true \
--conf spark.memory.offHeap.size=100g \
--conf spark.plugins=io.glutenproject.GlutenPlugin \
--conf spark.gluten.sql.columnar.backend.lib=velox \
--conf spark.driver.extraClassPath=/opt/gluten/gluten-velox-bundle-spark3.3_2.12-ubuntu_22.04-0.5.0-SNAPSHOT.jar \
--conf spark.executor.extraClassPath=/opt/gluten/gluten-velox-bundle-spark3.3_2.12-ubuntu_22.04-0.5.0-SNAPSHOT.jar \
--conf spark.gluten.sql.columnar.forceshuffledhashjoin=true \
--conf spark.shuffle.manager=org.apache.spark.shuffle.sort.ColumnarShuffleManager \
--database tpcds_parquet_3000
```

**Expected behavior**
All TPC-DS queries get executed successfully.

**Additional context**

**Comment by zhouyuan** [comment]
Hi @fq-zhaang 
Thanks for reporting, The bug fix on netty out of memory merged https://github.com/oap-project/gluten/commit/4bec2eb2f9a62ca50757b4413eca99d4ab1fa68d
can you please have a try with this commit included?

Thanks, -yuan

**Comment by fq-zhaang** [comment]
Hi @zhouyuan
Thanks for the quick response. But I got this error during the compilation: `./build_velox.sh: line 75: cd: _build/release/_deps: No such file or directory`
```log
[536/536] Linking CXX static library velox/substrait/libvelox_substrait_plan_converter.a
make[1]: Leaving directory '/data/projects/gluten/ep/build-velox/build/velox_ep'
+ echo 'INSTALL xsimd gtest.'
INSTALL xsimd gtest.
+ cd _build/release/_deps
./build_velox.sh: line 75: cd: _build/release/_deps: No such file or directory
```

**Comment by fq-zhaang** [comment]
@zhouyuan it works fine now. Thanks!
