### ISSUE TITLE
Convert ColumnarToRowExec to native implemention mistakenly

### ISSUE THREAD

**Issue by exmy** [oap-project/gluten#1645]
**Describe the bug**
Such the plan, we can not convert `ColumnarToRowExec` to native implemention since `CHNativeColumnarToRow` is not able to handle `ColumnBatch` produced by FileScanExec.

```shell
Filter (isnotnull(l_shipdate#845) AND (l_shipdate#845 = 1996-05-07))
+- CHNativeColumnarToRow
   +- FileScan parquet default.lineitem[l_shipdate#845] Batched: true, DataFilters: [isnotnull(l_shipdate#845), (l_shipdate#845 = 1996-05-07)], Format: Parquet, Location: InMemoryFileIndex(1 paths)[..., PartitionFilters: [], PushedFilters: [IsNotNull(l_shipdate), EqualTo(l_shipdate,1996-05-07)], ReadSchema: struct<l_shipdate:date>
```

**To Reproduce**
```sql
set spark.gluten.sql.columnar.filescan=false
set spark.gluten.sql.columnar.filter=false
select l_shipdate from lineitem where l_shipdate = '1996-05-07'
```

**Expected behavior**
We should keep `ColumnarToRowExec` as it is.

**Comment by exmy** [comment]
@rui-mo I had the issue on gluten+CH backend, could you help confirm whether Velox also has this issue? Thanks!

**Comment by rui-mo** [comment]
hi @exmy, vectorized reading of Spark is disabled in Gluten for Velox backend. See [GlutenPlugin.scala#L80-L90](https://github.com/oap-project/gluten/blob/main/gluten-core/src/main/scala/io/glutenproject/GlutenPlugin.scala#L80-L90).
Is vectorized reading needed by CH backend? There are some discussions before in https://github.com/oap-project/gluten/pull/1300.
cc @PHILO-HE

**Comment by exmy** [comment]
Thank you both @rui-mo @PHILO-HE  for the detailed explanation. Perhaps we can also disable vectorized reading for CH backend.  @zzcclp @liuneng1994  Do you think so?

**Comment by zzcclp** [comment]
+1 for disabled vectorized reading of vanilla Spark when fallback.

**Comment by PHILO-HE** [comment]
@exmy, recently, vectorized reader is supported in https://github.com/oap-project/gluten/pull/1931.  Please note if vanilla columnar read is followed by gluten columnar plan, a vanilla columnar to row and a native row to columnar will be used for data transition, which may result in visible perf. regression.
Just tested on velox backend. Not sure whether there is any issue for CH backend. Please have a try if you are interested in.
