### ISSUE TITLE
Is the nothing type of substrait will be stable?

### ISSUE THREAD

**Issue by Yohahaha** [oap-project/gluten#1653]
I find a problem due to oap-velox does not implement substrait nothing type.
https://github.com/oap-project/velox/blob/e26f9ef2ea7db338c47e5a2fb14f4d9da44d91c1/velox/substrait/SubstraitParser.cpp#L23-L24

PR #791 add nothing type in substrait for Spark nullType, but I see https://github.com/substrait-io/substrait/blob/main/proto/substrait/type.proto does not sync this change, and I can not find any background information for this.

Is community decide to use nothing type for nullType?

**Comment by rui-mo** [comment]
@taiyang-li Do we have any plan to upstream this change to Substrait?

**Comment by taiyang-li** [comment]
@Yohahaha substrait nothing type is used to represent spark null literals whose types can't be deduced exactly. For example: `select null`. Without nothing type, we can't transform spark nullType to substrait type. It is necessary for gluten, but I'm not sure for substrait upstream. 

I will create a PR to upstream later. @rui-mo

**Comment by PHILO-HE** [comment]
FYI, I am supporting spark NullType at https://github.com/oap-project/gluten/pull/2996. Thanks!
