### ISSUE TITLE
Header Search Paths do not include the complete velox directory during development

### ISSUE THREAD

**Issue by kerwin-zk** [oap-project/gluten#1690]
**Describe the bug**
In the process of using Clion to develop, the velox path in Header Search Paths only points to velox/external/xxhash, so that the velox-related .h files in the project cannot be found during the development process.

![image](https://github.com/oap-project/gluten/assets/107825064/809ac6ee-2699-43d3-966c-ff672e78a8ae)
![image](https://github.com/oap-project/gluten/assets/107825064/9c3abf1b-b592-4b25-a303-f7d590f223a9)

**Comment by zhouyuan** [comment]
closing #1691
