### ISSUE TITLE
missing lz4 library when using 0.5.0 release binary jar

### ISSUE THREAD

**Issue by weiting-chen** [oap-project/gluten#1700]
**Describe the bug**
The testing env. is CentOS7.4 and report lz4 missing during running 0.5.0 release binary jar.
lz4 library does not include in 3rd party library jar file.

**To Reproduce**
Run 0.5.0 release binary on CentOS7.4.

**Expected behavior**
Assume 3rd party jar file should be included in 3rd party library jar file.

**Comment by PengleiShi** [comment]
@weiting-chen i add liblz4 to gluten third-party jar, but it still failed to load liblz4. How could i fix it?
