### ISSUE TITLE
[VL] An exception occurred when compiling velox with --build_benchmarks=ON on alinux3 

### ISSUE THREAD

**Issue by kerwin-zk** [oap-project/gluten#1760]
**Describe the bug**
An exception occurred when compiling velox with --build_benchmarks=ON on alinux3.

**To Reproduce**
build_velox.sh --build_benchmarks=ON

**Expected behavior**
c++: 错误：third_party/arrow_ep/install//libarrow.a：没有那个文件或目录

**Comment by zhouyuan** [comment]
close by #1761
