### ISSUE TITLE
[VL] spark.gluten.sql.columnar.maxBatchSize is not passed to Velox

### ISSUE THREAD

**Issue by zhli1142015** [oap-project/gluten#1772]
**Describe the bug**

We set "spark.gluten.sql.columnar.maxBatchSize" as 32768, but this value is not passed to velox. Looks we still use old arrow batch rows config.
https://github.com/oap-project/gluten/blob/main/shims/common/src/main/scala/io/glutenproject/GlutenConfig.scala#LL325C16-L325C53

**Comment by zhli1142015** [comment]
cc @rui-mo , thanks

**Comment by rui-mo** [comment]
It should be noted that the real batch size of a Velox operator is not fully controlled by this config. This config onlys sets the preferred and max rows, and below is the logic in Velox.
https://github.com/oap-project/velox/blob/main/velox/exec/Operator.cpp#L291-L312
