### ISSUE TITLE
[VL] Insanely slow on executing TPC-DS Q_72

### ISSUE THREAD

**Issue by fq-zhaang** [oap-project/gluten#1775]
**Describe the bug**
It took more than **8435.907** seconds to execute Q_72 against TPC-DS 3T dataset. Same env, Spark only took **619.319** seconds.

**Env:**
1 master + 3 workers, with same CPU, memory and disk layout.

**Q_72**
```sql
--TPC-DS Q_72
SELECT
  i_item_desc,
  w_warehouse_name,
  d1.d_week_seq,
  count(CASE WHEN p_promo_sk IS NULL
    THEN 1
        ELSE 0 END) no_promo,
  count(CASE WHEN p_promo_sk IS NOT NULL
    THEN 1
        ELSE 0 END) promo,
  count(*) total_cnt
FROM catalog_sales
  JOIN inventory ON (cs_item_sk = inv_item_sk)
  JOIN warehouse ON (w_warehouse_sk = inv_warehouse_sk)
  JOIN item ON (i_item_sk = cs_item_sk)
  JOIN customer_demographics ON (cs_bill_cdemo_sk = cd_demo_sk)
  JOIN household_demographics ON (cs_bill_hdemo_sk = hd_demo_sk)
  JOIN date_dim d1 ON (cs_sold_date_sk = d1.d_date_sk)
  JOIN date_dim d2 ON (inv_date_sk = d2.d_date_sk)
  JOIN date_dim d3 ON (cs_ship_date_sk = d3.d_date_sk)
  LEFT OUTER JOIN promotion ON (cs_promo_sk = p_promo_sk)
  LEFT OUTER JOIN catalog_returns ON (cr_item_sk = cs_item_sk AND cr_order_number = cs_order_number)
WHERE d1.d_week_seq = d2.d_week_seq
  AND inv_quantity_on_hand < cs_quantity
  AND d3.d_date > (cast(d1.d_date AS DATE) + interval 5 days)
  AND hd_buy_potential = '>10000'
  AND d1.d_year = 1999
  AND hd_buy_potential = '>10000'
  AND cd_marital_status = 'D'
  AND d1.d_year = 1999
GROUP BY i_item_desc, w_warehouse_name, d1.d_week_seq
ORDER BY total_cnt DESC, i_item_desc, w_warehouse_name, d_week_seq
LIMIT 100
```

**To Reproduce**
1. Run Q_72 with Velox
2. Run Q_72 with Spark

**Expected behavior**
time cost less is than Spark's

**Comment by zhouyuan** [comment]
Hi @fq-zhaang thanks for reporting, Q72 is an alien in TPCDS 99 queries in some degree and maybe not working well now on gluten, let me explain a bit here: 

- the 1st inner join has many redundant values in both build/probe table, so it will emit much bigger number of rows than the original table, also gluten are using hash join by default - it may not perf well as sort merge join as it can skip the redundant values 
- it also has the following 10+ broadcast joins, each joins on different keys - which maybe more friendly for row-based impl as it's more cache friendly vs. columnar impl

For the performance turning, if you are able to try below settings:
- enable CBO join reorder, with this setting the smaller joins will be promoted such that the "big sized inner join" will be a "middle sized one"

- enable runtime filter if running with Spark 3.3 with below settings, with these the input of 1st join will smaller thus the impact of "redundant values" can be smaller
```
  --conf spark.sql.optimizer.runtime.bloomFilter.enabled=true \
  --conf spark.sql.optimizer.runtime.bloomFilter.applicationSideScanSizeThreshold=0
```
- gluten has a soft-fallback policy to use vanilla spark to run stages with many joins inside. With below configurations, Q72 can run with vanilla SMJ for the big inner join and the following joins 
```
  --conf spark.gluten.sql.columnar.joinOptimizationLevel=18 \
  --conf spark.gluten.sql.columnar.physicalJoinOptimizeEnable=true \
  --conf spark.gluten.sql.columnar.physicalJoinOptimizationLevel=18 \
  --conf spark.gluten.sql.columnar.logicalJoinOptimizeEnable=true \
  --conf spark.gluten.sql.columnar.logicalJoinOptimizationLevel=18 \
```
please check if these turnings can fix the performance gap, and report back if there are further issues. 

Thanks, -yuan

**Comment by fq-zhaang** [comment]
@zhouyuan thanks for the quick response, really appreciated! I have tried with cbo on, join reorder on, and wscg off. But based on the SQL plan diagram in Spark history UI page, it's still using wscg, therefore, the reorder didn't take effect. Time cost still more than 8000 seconds. I'm wondering if there is a switch in Gluten to turn off the wscg?
