### ISSUE TITLE
error: cannot convert 'const xsimd::fma3<xsimd::avx>' to 'const xsimd::sse4_1&'

### ISSUE THREAD

**Issue by jinwenjie123** [oap-project/gluten#1854]
**Describe the bug**
Hi,

When I was trying to follow the following docker_ubuntu page to compile the Gluten project. 
https://github.com/oap-project/gluten/blob/e012b50e3dc2f082c82b324f0be2b1d6f277511b/docs/developers/docker_ubuntu22.04.md, after running this command ./dev/buildbundle-veloxbe.sh.

I got the following error:  

ep/build-velox/build/velox_ep/./velox/common/base/SimdUtil.h:333:63: error: cannot convert 'const xsimd::fma3<xsimd::avx>' to 'const xsimd::sse4_1&'

**Comment by jinwenjie123** [comment]
Issue was solved by editing the .sh file.

**Comment by zhangnew** [comment]
> Issue was solved by editing the .sh file.

which file? and how?
