### ISSUE TITLE
[VL] Optimize columnartorow to reuse the allocated buffer in native side.

### ISSUE THREAD

**Issue by JkSelf** [oap-project/gluten#1868]
**Is your feature request related to a problem or challenge? Please describe what you are trying to do.**
(This section helps developers understand the context and *why* for this feature, in addition to  the *what*)

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by zhouyuan** [comment]
closed by https://github.com/oap-project/gluten/pull/1869
