### ISSUE TITLE
[VL]Vector encoding type check failed in DecimalSumAggregate

### ISSUE THREAD

**Issue by CLTFOREVER** [oap-project/gluten#1870]
**Describe the bug**
java.lang.RuntimeException: Exception: VeloxRuntimeError
Error Source: RUNTIME
Error Code: INVALID_STATE
Reason: (FLAT vs. ROW)
Retriable: False
Expression: decodedPartial_.base()->encoding() == VectorEncoding::Simple::ROW
Function: addSingleGroupIntermediateResults
File: gluten/ep/build-velox/build/velox_ep/./velox/functions/sparksql/aggregates/DecimalSumAggregate.h
Line: 317

**To Reproduce**
select sum(xxx) from table; xxx's type is decimal.

**Comment by CLTFOREVER** [comment]
@zhouyuan please have a look.

**Comment by liujiayi771** [comment]
@CLTFOREVER Could you post your Spark UI Plan graph? And post the results of `desc formatted table;`

**Comment by CLTFOREVER** [comment]
@liujiayi771  The table is very simple ,just create with sql:create table orc_decimal_test(t1 decimal(20,4)) stored as orc;
I just insert into three pieces of data:1.000,2.0000,3.0000;

**Comment by CLTFOREVER** [comment]
@liujiayi771 yes，the code is latest，but using our Spark version: 3.0.2，what‘s your spark version.

**Comment by CLTFOREVER** [comment]
@liujiayi771  I guess there were some differences when integrating the community Gluten with our Spark. I will use the community version for verification later. Thank you

**Comment by liujiayi771** [comment]
> @liujiayi771 yes，the code is latest，but using our Spark version: 3.0.2，what‘s your spark version.

I use Spark 3.3.1, maybe your Spark have some optimizations that will change the plan.

**Comment by CLTFOREVER** [comment]
@liujiayi771  The problem has been resolved，thank you so much.
The reason for this issue is that the variable aggBufferAttributes in the sum function has a different number of parameters in Spark3.0 and Spark3.2. This issue causes the output of the HashAggregateTransformer operator to be different, resulting in a missing parameter when converting to a Substrate plan, as you mentioned earlier
