### ISSUE TITLE
[VL] duplicate sort in window op

### ISSUE THREAD

**Issue by zhli1142015** [oap-project/gluten#2025]
**Describe the bug**
Rows are sorted twice in  orderBy op and window op (https://github.com/facebookincubator/velox/blob/main/velox/exec/Window.cpp#L242). In spark, planner would take care the partitioning and sortting for window op. The window op only calculates and outputs (windowed) aggregates over the rows in a single (sorted) partition. So, the second sort in window op should be skipped.
Before:
![image](https://github.com/oap-project/gluten/assets/10524738/7921ae86-a7e9-420c-abb4-b8604d5450d5)

After:
![image](https://github.com/oap-project/gluten/assets/10524738/39a50089-5d83-4345-98c5-90b30374f8d5)

**Comment by zhli1142015** [comment]
cc @zhouyuan , thanks.

**Comment by zhouyuan** [comment]
@zhli1142015 Thanks for this patch! Indeed it's not necessary, looks like we missed this when implemented `Window `operator

-yuan
