### ISSUE TITLE
[Gluten-Velox] Function list to be check or add

### ISSUE THREAD

**Issue by Ma-Jian1** [oap-project/gluten#2031]
Here listed some functions we need to support in Gluten and Velox, will keep updated in the future. You may reply in the thread if you'd like to work on anyone.

- [x] size https://github.com/facebookincubator/velox/pull/5461 fix return type
- [ ] percentile_approx
- [ ] explode
- [ ] concat_ws
- [x] collect_list (velox supported, needs Gluten to enable array for project plan node)
- [ ] date_sub (one velox upstream PR near to merge)
- [ ] date_format: can map to format_datatime https://github.com/facebookincubator/velox/issues/5734
- [x] regexp_replace (supported, only few incompatible issue from RE2 used by velox)
- [x] collect_set
- [x] current_timestamp (foldable expression, optimized by spark, no need to offload)
- [ ] unix_timestamp: "Only supports string type, with session timezone considered, todo: support date type"
- [ ] to_json
- [x] str_to_map https://github.com/facebookincubator/velox/pull/5842
- [ ] json_tuple
- [ ] to_date
- [x] rank
- [ ] hour
- [ ] locate
- [ ] mod
- [ ] conv: "PR ready“
- [ ] parse_url
- [ ] pow
- [ ] ifnull
- [ ] translate (upstream velox PR merged, Gluten PR pending for future velox rebase)
- [ ] urldecoder: "UDF, supported by spark as a built-in funciton since 3.4.0."
- [ ] distinct
- [ ] normalizenanandzero
- [ ] isarrayintersects
- [ ] default.json_split (udf, no need to impl.): "external UDF"
- [ ] parsejsonarray: "external UDF"
- [x] <=> (EqualNullSafe) https://github.com/oap-project/velox/pull/357 https://github.com/oap-project/gluten/pull/2259
- [ ] struct
- [ ] rand (supported except seed is provided)
- [x] now (foldable expression, optimized by spark, no need to offload)
- [ ] lead: "PR ready"
- [ ] add_months
- [ ] percentile
- [ ] last_day
- [ ] lag: "PR ready"
- [ ] minute
- [ ] year
- [ ] month
- [ ] weekofyear
- [ ] next_day
- [ ] posexplode
- [ ] trunc
- [ ] months_between
- [ ] array_min
- [ ] dense_rank
- [x] current_date (foldable expression, optimized by spark, no need to offload)
- [ ] day
- [ ] approx_percentile: "Third argument accuracy is different with velox, velox is double but spark is long"
- [ ] reflect
- [ ] date_trunc
- [ ] dayofweek
- [ ] stack
- [ ] nullif
- [ ] grouping_id
- [ ] printf
- [ ] space
- [x] bin
- [ ] find_in_set
- [ ] inline
- [ ] hex
- [ ] dayofmonth
- [ ] to_unix_timestamp: "Only supports string type, with session timezone considered. todo: support date type"

**Comment by weixiuli** [comment]
How is the development of these functions going, especially the  collect_list and collect_set ?

**Comment by zuochunwei** [comment]
mark
