### ISSUE TITLE
[VL] Extra copy introduced to workaround the non-16B aligned crash

### ISSUE THREAD

**Issue by zhztheplayer** [oap-project/gluten#2048]
@jinchengchenghh @zuochunwei Let's have this issue as a memo for the current workarounds:

1. https://github.com/oap-project/velox/commit/48ea6d44db178e42e853f87ca8e95e0690a83acd
2. ~~https://github.com/oap-project/velox/compare/b1f131866440bc38bc867cf9c9b8a48e489d98a5..3fbd0e16c48d4dbb767d34333a74c5203e3998bc#diff-18f40fd475b73232f0933d6fd661435a99d50aac55d6ab280f97d95b252df1a0R168~~ (reverted)
3. https://github.com/oap-project/gluten/pull/2159

**Comment by zuochunwei** [comment]
OK

**Comment by zhztheplayer** [comment]
I suppose the issue was fixed. Please reopen if still existing any.
