### ISSUE TITLE
[CH] Refactor HiveTableScanExecTransformer

### ISSUE THREAD

**Issue by exmy** [oap-project/gluten#2098]
**Describe the solution you'd like**

refactor the code related to `HiveTableScanExecTransformer`

* `CHHiveTableScanExecTransformer` rename to `HiveTableScanExecTransformer`, make it shared on CH and velox backend
* add config to enable or disable transform `HiveTableScanExec`
* refactor some code sections with not so good coding style to adopt a more elegant and scala-style approach

**Comment by baibaichen** [comment]
Would you please describe more details?
