### ISSUE TITLE
[DOC] Outdated velox backend build documentation

### ISSUE THREAD

**Issue by wForget** [oap-project/gluten#2131]
**Describe the bug**

`build_arrow_from_source` and `build_velox_from_source` have been removed in #811

https://github.com/oap-project/gluten/blob/26e2f831f65aeba465e26f5c8d92cc47af63b315/docs/get-started/Velox.md?plain=1#L58

**Comment by PHILO-HE** [comment]
I will correct this issue. Thanks for the feedback!

**Comment by PHILO-HE** [comment]
Fixed.
