### ISSUE TITLE
[CH] `date_trunc`:  support specified timezone and `foldable` `format` expression

### ISSUE THREAD

**Issue by zzcclp** [oap-project/gluten#2144]
**Describe the bug**
Currently, the spark function `date_trunc` is mapping to the ch `date_trunc` function, but in ch, it can not support to trunc date with 'year/month/quarter/week' format by the specified time zone, for example:

```
# The default time zone of ch is 'America/Los_Angeles'

    DateTimeTestUtils.withDefaultTimeZone(DateTimeTestUtils.UTC) {
      val inputDate = Timestamp.valueOf("2015-07-22 05:30:06")

      import testImplicits._
      val df = Seq(
        (1, Timestamp.valueOf("2015-07-22 05:30:06")),
        (2, Timestamp.valueOf("2014-12-31 05:29:06.123456"))
      ).toDF("i", "t")

      df.createOrReplaceTempView("date_trunc_tmp1")
      val sql2 =
        s"""
           |select t,
           |       date_trunc('YEAR', t) a,
           |       date_trunc('WEEK', t) b,
           |       date_trunc('month', t) c
           |from date_trunc_tmp1
           |""".stripMargin
      compareResultsAgainstVanillaSpark(sql2, true, { _ => }, false)
    }

```
When the default time zone is changed, and execute the `date_trunc('YEAR/MONTH/QUARTER/WEEK', t)`, CH can not use the new time zone value to handle the datetime.

**To Reproduce**

**Expected behavior**

**Additional context**

**Comment by baibaichen** [comment]
In addition, if `format` expression is not `foldable`, CH also doesn't support it yet.

![image](https://github.com/oap-project/gluten/assets/3688732/2c1b62d2-654e-4068-a567-a10b3edffb6b)
