### ISSUE TITLE
[CH] Expect the performance of handling ORC files is on par with Parquet

### ISSUE THREAD

**Issue by fuhaiq** [oap-project/gluten#2162]
**Expect the performance of handling ORC files is on par with Parquet**

**Comment by taiyang-li** [comment]
I'll finish it.

**Comment by taiyang-li** [comment]
https://github.com/ClickHouse/ClickHouse/pull/51870

**Comment by taiyang-li** [comment]
Seems no performance improvement... 
![image](https://github.com/oap-project/gluten/assets/8181003/7dfbc3bb-19db-49e1-ace7-50f7f46ea6b9)

**Comment by taiyang-li** [comment]
@fuhaiq can you close this pr, the tests shows no benefits on performance.

**Comment by baibaichen** [comment]
let's keep it, we need invest it in our enviorment.
