### ISSUE TITLE
[CH] Support read file from alluxio

### ISSUE THREAD

**Issue by loneylee** [oap-project/gluten#2203]
**Describe the solution you'd like**
In order to speed up access to s3, we used alluxio for file caching. The current CH backend does not support reading schema of alluxio 

**Describe alternatives you've considered**
Support `alluxio://host1:80,host2:81/test/file.parquet`

Note: Host maybe has more than one.

**Comment by baibaichen** [comment]
We don't fix this isue in the near future. let's reopen it if needed.
