### ISSUE TITLE
[CH] support ansi cast used in native writer scenario

### ISSUE THREAD

**Issue by taiyang-li** [oap-project/gluten#2228]
solve ansi cast problem in https://github.com/oap-project/gluten/issues/1925

**Comment by binmahone** [comment]
accurrateCast in CH is comparable to ansicast in Spark, just like CAST in CH is comparable to cast in Spark.
Even though we can't guarantee 100% behavior match, it would be sufficient for current use.

**Comment by binmahone** [comment]
after finishing the first PR (https://github.com/oap-project/gluten/pull/2577/files) we found that CH accurateCast still has many behavior mismatch with ansi_cast. This will cause some spark UT to fail, .e.g. AnsiCastSuiteWithAnsiModeOff (Off here means spark.sql.ansi.enabled, but for write command, ansi_cast is still used in the Spark query plan)

The effort of tweaking CH accurateCast to behave exactly like ansi_cast is potentially huge. so we'll give up claiming  ANSI support in write scenario (at least for now). We'll print warning if user use Gluten for writing tasks without setting `spark.sql.storeAssignmentPolicy` to `legacy`. (https://github.com/oap-project/gluten/pull/2592)

When spark.sql.storeAssignmentPolicy is not set to legacy, unexpected behavior may be observed: Consider a query like stage1->stage2->write, and stage2 contains ansi_cast, then we may have stage1(in Java)->stage2(in Native). CH backend may not well handle this case and throw exceptions.

**Comment by taiyang-li** [comment]
Currently we won't officially support ansi cast, close it now.
