### ISSUE TITLE
[CH] Empty data using agg cause different result betweem gluten and spark

### ISSUE THREAD

**Issue by loneylee** [oap-project/gluten#2233]
**Describe the bug**
In spark3.2's ut,  `GlutenDataFrameAggregateSuite.zero average` and `GlutenDataFrameAggregateSuite.zero stddev`.

An empty data use agg function will return empty row. In spark3.2, return a row with null value instead empty row.

Related to #2216, [#161](https://github.com/Kyligence/ClickHouse/issues/161)

**Comment by baibaichen** [comment]
We once implemented an `EmptyRDD` to work around this issue, but it introduced #2210, so that we have to remove it, see #2216
