### ISSUE TITLE
[CH] libch.so too large needed to be reduced

### ISSUE THREAD

**Issue by zhanglistar** [oap-project/gluten#2248]
As title.

**Comment by zhanglistar** [comment]
1. strip so
2.  gc sections
  `-ffunction-sections`, `-fdata-sections`, `-fmerge-all-constants`,
  `-Wl,--gc-sections`, `-Wl,-z,norelro`
3. zstd compression

**Comment by taiyang-li** [comment]
some build options could be closed

- ENABLE_BCRYPT: related to CH client authentication, useless for us.
- ENABLE_ULID:  depended by function `ULIDStringToDateTime` and `generateULID`
- ENABLE_OPENSSL_DYNAMIC/ENABLE_OPENSSL: used by clickhouse-server for opensslconf
- ENABLE_RUST: include skim(for cmd line history) and blake3(for ch function blake3)
- ENABLE_ODBC: used by clickhouse-odbc-bridge
- USE_FILELOG: use by StorageFileLog

**Comment by zhanglistar** [comment]
After strip:   
 FILE SIZE        VM SIZE
 --------------  --------------
  69.9%   239Mi  69.0%   239Mi    .text
  12.2%  41.7Mi  12.0%  41.7Mi    .rodata
   6.2%  21.1Mi   6.1%  21.1Mi    .rela.dyn
   5.8%  20.0Mi   5.7%  20.0Mi    .eh_frame
   2.4%  8.32Mi   2.4%  8.32Mi    .data.rel.ro
   2.1%  7.14Mi   2.1%  7.14Mi    .gcc_except_table
   0.0%       0   1.3%  4.67Mi    .bss
   0.9%  3.22Mi   0.9%  3.22Mi    .eh_frame_hdr
   0.5%  1.60Mi   0.5%  1.60Mi    .data
   0.0%  13.3Ki   0.0%  8.50Ki    .init_array
   0.0%  13.0Ki   0.0%  13.0Ki    .dynsym
   0.0%  10.4Ki   0.0%  10.4Ki    .rela.plt
   0.0%  10.1Ki   0.0%  10.1Ki    .dynstr
   0.0%  6.92Ki   0.0%  6.92Ki    .plt
   0.0%  6.70Ki   0.0%  6.70Ki    .tdata
   0.0%  5.79Ki   0.0%  3.38Ki    [15 Others]
   0.0%       0   0.0%  4.80Ki    .tbss
   0.0%  3.48Ki   0.0%  3.48Ki    .got.plt
   0.0%  2.36Ki   0.0%  2.36Ki    malloc_hook
   0.0%  2.15Ki   0.0%  2.15Ki    .got
   0.0%  2.07Ki   0.0%  2.07Ki    [LOAD #1 [R]]
 100.0%   343Mi 100.0%   347Mi    TOTAL
