### ISSUE TITLE
[VL] ShuffleWrite: Larger shuffle size than vanilla spark and long compression time

### ISSUE THREAD

**Issue by Guhaiyan** [oap-project/gluten#2343]
Zstd is chosen as shuffle codec.

1. For columns of string type, with low cardinality, we will see larger shuffle size than vanilla spark. Low compress ratio(~1.62) for arrow::ipc offsets array account for this。One of the possible solution is storing length(delta of offset) of string instead of offset, which will significantly reduce compressed size。

2. The other issue seen is arrow::IpcPayload.body_buffers' long compression time. Body buffers are compressed in a for loop , one buffer at a time, in a single thread, leading to low effciency. Make body buffers continous as a large buffer before compression, so the arrow::RecordBatch will be compressed in one shot. we see 4/5 time reduction in a test scenario with 3 columns, one string (~30bytes) and 2 long type.

**Comment by jinchengchenghh** [comment]
For 1: the delta of offset should still be int64_t, why it can reduce compressed size? The store type should align with velox `BufferPtr` size.

For 2: this is a good idea, we also have the plan to move compression to gluten side, then we don't need the offset buffer in the  binary `RecordBatch` and can compress them to a very big buffer. Welcome to help implement it. @FelixYBW

**Comment by marin-ma** [comment]
For 1, I guess the reason is it's much more likely to get duplicated values using string length.
For 2, Making buffers contiguous may introduce extra memcpy. .Like  @jinchengchenghh  said, we can compress multiple buffers into one buffer.

**Comment by jinchengchenghh** [comment]
For 1: I think it's OK.

**Comment by jinchengchenghh** [comment]
I will try to compress IPCPayload buffers to one buffer.

**Comment by FelixYBW** [comment]
About 1)
what's the raw shuffle size of Vanilla spark and Gluten? Currently after split, the reducer string column still use Arrow format, it's one value buffer to store all strings and one int32_t buffer to store the offset. Except we use dictionary encoding for value buffer, looks we shouldn't be larger than Vanilla Spark

About 2) Did you try to input multiple buffer to compression function and compress into single buffer? Not sure if it works
