### ISSUE TITLE
[VL]std::bad_cast under v1.0.0

### ISSUE THREAD

**Issue by yonger001** [oap-project/gluten#2361]
**Describe the bug**
when running the 1.sql of tpch, there throws the following error:
...
caused by :org.apache.spark.SparkException: Job aborted due to stage failure: Task 0 in stage 9.0 failed 1 times, ...
...
caused by : java.lang.RuntimeException: std::bad_cast
...

**To Reproduce**
use the following jars, start the spark server and run 1.sql:
/v1.0.0/gluten-velox-bundle-spark3.2_2.12-centos_7-1.0.0.jar
/0.5.0/gluten-thirdparty-lib-centos-7.jar
spark-3.2.2-bin-hadoop3.2.tgz

**Comment by PHILO-HE** [comment]
Hi @yonger001, 1.0.0 release has no third party jar published, as third party dependencies are statically linked. You can just use one corresponding gluten 1.0.0 release jar for test and to see whether the issue still exists.
BTW, could you please let us know which company you are from?

**Comment by hailiang9615** [comment]
I have the same problem, is this the CPU type limit? The type of CPU I'm having trouble with is hygon？

**Comment by loukey-lj** [comment]
java.lang.RuntimeException: std::bad_cast
	at io.glutenproject.vectorized.PlanEvaluatorJniWrapper.nativeCreateKernelWithIterator(Native Method)
	at io.glutenproject.vectorized.NativePlanEvaluator.createKernelWithBatchIterator(NativePlanEvaluator.java:79)
	at io.glutenproject.backendsapi.velox.IteratorHandler.genFinalStageIterator(IteratorHandler.scala:292)
	at io.glutenproject.execution.WholeStageZippedPartitionsRDD.$anonfun$genFinalStageIterator$1(WholeStageZippedPartitionsRDD.scala:61)
	at io.glutenproject.execution.WholeStageZippedPartitionsRDD.compute(WholeStageZippedPartitionsRDD.scala:70)

**Comment by hailiang9615** [comment]
> java.lang.RuntimeException: std::bad_cast at io.glutenproject.vectorized.PlanEvaluatorJniWrapper.nativeCreateKernelWithIterator(Native Method) at io.glutenproject.vectorized.NativePlanEvaluator.createKernelWithBatchIterator(NativePlanEvaluator.java:79) at io.glutenproject.backendsapi.velox.IteratorHandler.genFinalStageIterator(IteratorHandler.scala:292) at io.glutenproject.execution.WholeStageZippedPartitionsRDD.$anonfun$genFinalStageIterator$1(WholeStageZippedPartitionsRDD.scala:61) at io.glutenproject.execution.WholeStageZippedPartitionsRDD.compute(WholeStageZippedPartitionsRDD.scala:70)

Do you know how to solve this problem? Thank you

**Comment by PHILO-HE** [comment]
If you are using our posted 1.0.0 release jar, please don't deploy third-party jar and disable the below config property:
`spark.gluten.loadLibFromJar=false`. Then, the std::bad_cast can be avoided, according to some user's feedback.

**Comment by loukey-lj** [comment]
@PHILO-HE  yes  spark.gluten.loadLibFromJar=false  sometimes in effect。 I am in the ubuntu environment, and I will still report this error after disabling this configuration after replacing it with the arrow compiled by myself.

**Comment by guobj** [comment]
@loukey-lj @hailiang9615 I encountered the same problem, did you solve it?
