### ISSUE TITLE
[VL] Writing parquet table still use vanilla spark InsertIntoHadoopFsRelationCommand

### ISSUE THREAD

**Issue by PengleiShi** [oap-project/gluten#2378]
**Describe the bug**
Maybe it's not a bug.  I  create a parquet table `create table t1 (id int, name string) using parquet` and then insert overwrite it using sql`insert into t1 select * from t2`, i found there is still `InsertIntoHadoopFsRelationCommand`.
I'm not sure whether there should be a gluten operator instead of  `InsertIntoHadoopFsRelationCommand`, and also I'm confused about VeloxParquetFileFormat and the usage like  spark.range(100).toDF("id").write.**format("velox")**.
I don't find any information in doc, anyone can help me?

**To Reproduce**

**Expected behavior**

**Additional context**

**Comment by PengleiShi** [comment]
ping @JkSelf @ulysses-you

**Comment by Yohahaha** [comment]
> i found there is still InsertIntoHadoopFsRelationCommand. I'm not sure whether there should be a gluten operator instead of InsertIntoHadoopFsRelationCommand

`InsertIntoHadoopFsRelationCommand` is expected.

> I'm confused about VeloxParquetFileFormat and the usage like spark.range(100).toDF("id").write.format("velox").

It use Spark DSv1 interface to test write code, Gluten does not support parquet writer with your origin parquet table currently.

**Comment by ulysses-you** [comment]
yes, it is not supported yet, see https://github.com/oap-project/gluten/blob/main/docs/velox-backend-limitations.md#parquet-write

Recently, I'm looking at parquet write things. I think this pr is what you want https://github.com/oap-project/gluten/pull/2379

**Comment by PengleiShi** [comment]
@ulysses-you @Yohahaha thx.  So on condition of using code `df.write.format("velox").save("hdfs://xxx")`, it will use velox parquet write. If using sql `insert into parquet_table xxx`, it will not use velox parquet write at present , am i right? 
I just have a test using `df.write.format("velox").save("hdfs://")` , i found there was `VeloxParquetFileFormat` in `InsertIntoHadoopFsRelationCommand`

**Comment by JkSelf** [comment]
> @ulysses-you @Yohahaha thx. So on condition of using code `df.write.format("velox").save("hdfs://xxx")`, it will use velox parquet write. If using sql `insert into parquet_table xxx`, it will not use velox parquet write at present , am i right? I just have a test using `df.write.format("velox").save("hdfs://")` , i found there was `VeloxParquetFileFormat` in `InsertIntoHadoopFsRelationCommand`

Gluten only offload the write action to velox writer not the operator. And currently only support the following two cases sql:
  `df.write.format("velox").save("hdfs://")` and `insert overwrite local directory 'file:///tmp/parquet_insert/' STORED AS parquet select * from date_dim` .

**Comment by PengleiShi** [comment]
Got it，thx
