### ISSUE TITLE
[VL] Invalid regular expression ^0+(?!$)

### ISSUE THREAD

**Issue by loukey-lj** [oap-project/gluten#2417]
**Describe the bug**
2023-07-16 02:42:26,728 [task-result-getter-1] INFO  - TaskSetManager: Lost task 1.1 in stage 3.0 (TID 77) on cnsz26plb2xl, executor 4: java.lang.RuntimeException (Exception: VeloxUserError
Error Source: USER
Error Code: INVALID_ARGUMENT
Reason: Invalid regular expression ^0+(?!$): invalid perl operator: (?!.
Retriable: False
Function: initialize
File: ../.././velox/functions/lib/Re2Functions.h
Line: 170

select
	if(length(regexp_replace(qcs_emp_code,"^0+(?!$)","")) <= 6,lpad(regexp_replace(qcs_emp_code,"^0+(?!$)",""),6,'0'),lpad(regexp_replace(qcs_emp_code,"^0+(?!$)",""),8,'0')) AS emp_code
	,inc_day
from  xxx
group by
if(length(regexp_replace(qcs_emp_code,"^0+(?!$)","")) <= 6,lpad(regexp_replace(qcs_emp_code,"^0+(?!$)",""),6,'0'),lpad(regexp_replace(qcs_emp_code,"^0+(?!$)",""),8,'0')),inc_day

**Comment by PHILO-HE** [comment]
Hi @loukey-lj, thanks for reporting this issue. It looks like a limitation issue of RE2. The RE2 used by velox has a few incompatible issues with JDK's regular expression lib. We encountered a similar issue before. Maybe, we have to block the offloading for such case and let the execution fall back to vanilla spark. I will handle it.

**Comment by PHILO-HE** [comment]
There is a fix to let such function fall back for all unsupported regexp pattern.
https://github.com/oap-project/gluten/pull/2714

**Comment by PHILO-HE** [comment]
Suppose this issue has been fixed by the mentioned PR. Please re-open it if still exists. Thanks!
