### ISSUE TITLE
[VL] ProjectExecTransformer: Validation failed for class io.glutenproject.execution.ProjectExecTransformer due to key not found: transform

### ISSUE THREAD

**Issue by sandeep-biddala** [oap-project/gluten#2424]
**Describe the bug**
I get the following warning when running Gluten with Velox backend on standalone mode.
`ProjectExecTransformer: Validation failed for class io.glutenproject.execution.ProjectExecTransformer due to key not found: transform`
I am using version 0.5.0 with Spark 3.2.2 on Ubuntu 20.04

**To Reproduce**
- Start Spark with Gluten and issue count command.

**Comment by PHILO-HE** [comment]
Hi @sandeep-biddala, gluten has a fallback mechanism, which blocks the offloading and makes unsupported execution go back to vanilla spark. And gluten will log such cases with message like "validation failed for ...". I am assuming what you mentioned is a normal fallback situation. Feel free to let me know if I'm missing something.

BTW, could you please tell us which company you are from? Thanks!

**Comment by sandeep-biddala** [comment]
@PHILO-HE Thanks for the response and explaining the default behaviour. Does this mean that when this warning message appears, we are falling to vanilla spark for the entire job or only for unsupported operations? And how could I get information about the unsupported execution?

P.S. I am from [liftoff.io](liftoff.io)

**Comment by PHILO-HE** [comment]
By default, Gluten's validation log just gives user a hint that an operator is not supported, not the entire query job. In you case, it means project operator falls back. In Gluten's default fallback mechanism, assuming one unsupported operator falls back to vanilla spark, the next operator can still be offloaded to gluten if it is supported (only few exceptional cases will not). And there is a data transition node (ColumnarToRow/RowToColumnar) playing a bridge role between spark plan and gluten plan.
In spark UI, you can check DAG to easily find which operator is offloaded to gluten. Gluten's plan is mostly named `**Transformer` or `Columnar**`.

**Comment by Yohahaha** [comment]
See GlutenConfig.scala then find all log related config and open these, you will see the whole fallback information.

**Comment by sandeep-biddala** [comment]
@Yohahaha and @PHILO-HE  Thanks for the response. I will follow your suggestion and check the DAG to see what operations are being optimised by Gluten. Thanks!

**Comment by PHILO-HE** [comment]
Closing this issue. Please re-open it if needed.
