### ISSUE TITLE
CMake Error at CMake/resolve_dependency_modules/re2.cmake:38

### ISSUE THREAD

**Issue by dgriffiths-undo** [oap-project/gluten#2438]
**Describe the bug**

I checked out the latest version today and tried to follow the Velox build instructions. That resulted in a build failure:
```
-- Setting re2 source to AUTO
-- Could NOT find re2 (missing: re2_lib re2_include)
-- Building re2 from source
-- Found Threads: TRUE
CMake Error at CMake/resolve_dependency_modules/re2.cmake:38 (if):
  if given arguments:

    "STREQUAL" "BUNDLED"

  Unknown arguments specified
Call Stack (most recent call first):
  CMake/ResolveDependency.cmake:43 (include)
  CMake/ResolveDependency.cmake:75 (build_dependency)
  CMakeLists.txt:389 (resolve_dependency)
```

**To Reproduce**
Follow steps in https://github.com/oap-project/gluten/blob/main/docs/get-started/Velox.md

**Expected behavior**
Expected it to build.

**Additional context**

**Comment by dgriffiths-undo** [comment]
Ouch, gets further now but seems to consume huge amounts of swap space (I have 8GB RAM) and eventually got
```
c++: fatal error: Killed signal terminated program cc1plus
compilation terminated.
make[2]: *** [velox/CMakeFiles/velox.dir/build.make:90: velox/CMakeFiles/velox.dir/jni/VeloxJniWrapper.cc.o] Error 1
make[2]: *** Waiting for unfinished jobs....
make[1]: *** [CMakeFiles/Makefile2:170: velox/CMakeFiles/velox.dir/all] Error 2
make: *** [Makefile:136: all] Error 2
```

**Comment by Yohahaha** [comment]
Could you post your machine environment and more build information? re2 should be installed when build velox.

**Comment by dgriffiths-undo** [comment]
Hi, I am using "Ubuntu 22.04.1 LTS" on a VM partition on my Mac. I increased my RAM to 12GB and reduced the number of cores to 2 (because it seemed to launch lots of parallel processes?) and installed re2 and then it built.

I couldn't see anywhere in the build instructions where it says you have to install re2?

**Comment by Yohahaha** [comment]
> I couldn't see anywhere in the build instructions where it says you have to install re2?

In Ubuntu, re2 will be build/installed with Velox, see https://github.com/oap-project/velox/blob/main/scripts/setup-ubuntu.sh.

> "Ubuntu 22.04.1 LTS" on a VM partition on my Mac

I'm not sure this case could work, gluten has not tested on Max or VM hosted on Mac.

You could find more helpful build information from Gluten's CI.
