### ISSUE TITLE
[CH] permission denied during native insert

### ISSUE THREAD

**Issue by taiyang-li** [oap-project/gluten#2450]
java.lang.RuntimeException: Cannot create dir for /apps/hive/warehouse/tmp.db/tmp_zhixu_likee_video_underage_expired2release/.hive-staging_hive_2023-07-20_15-03-20_051_4390947598066022712-1/-ext-10000/_temporary/0/_temporary/attempt_202307201503209198084002477869554_0000_m_000000_0 because Permission denied: user=yarn, access=WRITE, inode="/apps/hive/warehouse/tmp.db/tmp_zhixu_likee_video_underage_expired2release/.hive-staging_hive_2023-07-20_15-03-20_051_4390947598066022712-1/-ext-10000/_temporary/0":liyang:hdfs:drwxr-xr-x

**Comment by taiyang-li** [comment]
原因：executor进程中，通过libhdfs3初始化hdfs环境时未指定user，于是libhdfs3使用当前系统用户即yarn container的启动用户，作为执行mkdir rpc的用户，因此namenode报错permission denied

解决：在executor中，首先获取环境变量SPARK_USER, 将其附加到hdfs uri中，使得正确的用户名传递给mkdir rpc，避免报错。

**Comment by taiyang-li** [comment]
Fixed by https://github.com/oap-project/gluten/pull/2205

**Comment by baibaichen** [comment]
@binmahone, a seperate pr would be better.

**Comment by baibaichen** [comment]
>  解决：在executor中，首先获取环境变量SPARK_USER, 将其附加到hdfs uri中，使得正确的用户名传递给mkdir rpc，避免报错

@taiyang-li 需要读取 HADOOP_USER_NAME，这里要和 vanilla spark 一致

**Comment by taiyang-li** [comment]
使用账户liyang创建的hive表。表目录权限如下：
drwxr-xr-x - liyang hdfs 0 2023-07-24 18:28 hdfs://bigocluster/apps/hive/warehouse/tmp.db/tmp_zhixu_likee_video_underage_expired2release

disable gluten后，执行insert操作：
1. spark_user未设置， hadoop_user_name=yarn: 权限报错
2. spark_user未设置， hadoop_user_name未设置：成功
3. spark_user未设置， hadoop_user_name=liyang: 成功
4. spark_user为yarn, hadoop_user_name未设置：权限报错
5. spark_user为yarn, hadoop_user_name=liyang: 权限报错
6. spark_user=liyang, hadoop_user_name=yarn: 权限报错
7. spark_user=liyang, hadoop_user_name未设置：成功

结论：这俩环境变量都显式设置的话，如果其中有一个值不对，都会造成权限校验失败。
综上，最终采用SPARK_USER作为hadoop auth user
