### ISSUE TITLE
Is there any roadmap?

### ISSUE THREAD

**Issue by zhanglistar** [oap-project/gluten#246]
We are looking the native execution engine of apache spark, and I see this project is very good.
So what's the status of this project, and any roadmap?
We can involve to develop it.

**Comment by Narcasserun** [comment]
+1

**Comment by icejoywoo** [comment]
+1

**Comment by FelixYBW** [comment]
It will be great if you can contribute. You may refer to https://databricks.com/dataaisummit/session/gazelle-jni-middle-layer-offload-spark-sql-native-engines-execution for latest status and high level roadmap.  

We are working to pass 103 TPCDS queries in this quarter. If you are interested, you may take some queries and start to contribute.

**Comment by zhanglistar** [comment]
> It will be great if you can contribute. You may refer to https://databricks.com/dataaisummit/session/gazelle-jni-middle-layer-offload-spark-sql-native-engines-execution for latest status and high level roadmap.
> 
> We are working to pass 103 TPCDS queries in this quarter. If you are interested, you may take some queries and start to contribute.

@FelixYBW Thanks for your reply. We are investigating this project to improve spark performance, and we will contribute code back if we have improvements. Thanks for the great project gluten and velox.

**Comment by zhanglistar** [comment]
@FelixYBW We are from China, and you are in Shanghai, so do you have wechat group, we can communicate more convenient, and we want to evolve to develop this project and apply to our cluster. Thanks.
