### ISSUE TITLE
[CH] unequal result with spark 

### ISSUE THREAD

**Issue by shuai-xu** [oap-project/gluten#2474]
**Describe the bug**
When run sql 
```
select count(1) from xxxx
    where from_unixtime(bigint(post_id / 4294967296), 'yyyy-mm-dd') >= date_sub('2023-03-14',63)
```
, the result of gluten is no equal to spark.

**Comment by lgbo-ustc** [comment]
It's the difference on date comparition.

**Comment by lgbo-ustc** [comment]
may be fixed by https://github.com/ClickHouse/ClickHouse/issues/53140
