### ISSUE TITLE
[VL] gluten not support alios 7

### ISSUE THREAD

**Issue by ztreble** [oap-project/gluten#2476]
error: java.lang.ClassCastException: scala.runtime.BoxedUnit cannot be cast to io.glutenproject.utils.VeloxSharedlibraryLoader

OS version：
NAME="Alibaba Group Enterprise Linux Server"
VERSION="7.2 (Paladin)"
ID="alios"
ID_LIKE="fedora"
VERSION_ID="7.2"
PRETTY_NAME="Alibaba Group Enterprise Linux Server 7.2 (Paladin)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:alibaba:enterprise_linux:7.2:GA:server"

**Comment by Yohahaha** [comment]
Hi, we have fully tested in Alinux3, could you describe more about your usage? BTW are you an employee of Alibaba or just a ECS user?

**Comment by ztreble** [comment]
> Hi, we have fully tested in Alinux3, could you describe more about your usage? BTW are you an employee of Alibaba or just a ECS user?

I'm ECS user.It was clear that gluten supported the new Anolis and alinux did not support the old alios.But I can't change the os version right now.

**Comment by Yohahaha** [comment]
OK, we have published BETA version of Gluten support in AliCloud EMR since 5.11.1, email me if you interested.

**Comment by ztreble** [comment]
> OK, we have published BETA version of Gluten support in AliCloud EMR since 5.11.1, email me if you interested.
Can you fix it? It looks like you only need to add two lines of code. Thank you very much

**Comment by ztreble** [comment]
> OK, we have published BETA version of Gluten support in AliCloud EMR since 5.11.1, email me if you interested.

Can you fix it? It looks like you only need to add two lines of code. Thank you very much
