### ISSUE TITLE
[CH] read from hdfs may cost miniutes

### ISSUE THREAD

**Issue by shuai-xu** [oap-project/gluten#2503]
**Describe the bug**
When running gluten sqls, we found some jobs spend a lot of time on reading from hdfs, such as bellow:
<img width="881" alt="image" src="https://github.com/oap-project/gluten/assets/20960838/9c26ecde-316f-4b6d-b684-a9c9efa3269c">
This task has no complex compution, the time between tow read is mainly spent on reading from hdfs.
<img width="561" alt="image" src="https://github.com/oap-project/gluten/assets/20960838/9f032934-9573-4110-83ef-26e1d1802584">

**Expected behavior**
LibHDFS should have logs to show where this time spend on and improve the preformance.

**Comment by taiyang-li** [comment]
fixed by https://github.com/oap-project/gluten/pull/2551
