### ISSUE TITLE
[VL][Discussion] Better way to deploy UDF libraries

### ISSUE THREAD

**Issue by marin-ma** [oap-project/gluten#2504]
### Problem Description
We have enabled Velox UDF in https://github.com/oap-project/gluten/pull/2427. Our current solution requires the UDF libraries being placed within the same paths on driver and executors, which is not a very good practice. We're planning on open a new patch to optimize the configuration. Here we list two proposals for how to configure UDF libraries.

### Proposal 1: Build UDF Libraries into Gluten Jar

In this approach, we'll pack the UDF libraries directly into the gluten jar when building Gluten. Users can create their UDF libraries inside Gluten cpp, like the given [UDF example](https://github.com/oap-project/gluten/tree/main/cpp/velox/udf/examples). The compilation of their UDF libraries will be embedded in Gluten build process and the libraries will be packed into Gluten jar. In this way, users can directly use current Gluten building command without any extra steps.

### Proposal 2: Build and Upload Libraries Separately

Users need to create standalone UDF libraries and upload them using the "--file" option when starting Spark. In this way, users can still create their UDF libraries inside Gluten cpp, but they need to build and maintain the UDF libraries separately. The advantage is that users can add or replace UDF libraries without rebuild and repack Gluten jar.

cc @zhouyuan @FelixYBW

**Comment by jackylee-ch** [comment]
The second way sounds good to me. User need to create and build their own UDF libraries and pass them to Spark.

BTW, the `udfLibraryPaths` in #2427 can be same relative path if user use `--files` or `--archives` to pass their UDF libraries, and this actually is highly recommended for users to do.

**Comment by marin-ma** [comment]
> The second way sounds good to me. User need to create and build their own UDF libraries and pass them to Spark.
> 
> BTW, the `udfLibraryPaths` in #2427 can be same relative path if user use `--files` or `--archives` to pass their UDF libraries, and this actually is highly recommended for users to do.

I'm not sure if I understand you correctly. Here's what I'm thinking: `--files /path/to/libmyudfs.so --conf spark.gluten.sql.columnar.backend.velox.udfLibraryPaths=libmyudf.so`
Or can you give an example to describe what "same relative path" refer to?

**Comment by marin-ma** [comment]
@jackylee-ch Please let me know if any suggestions.

**Comment by jackylee-ch** [comment]
> I'm not sure if I understand you correctly. Here's what I'm thinking: --files /path/to/libmyudfs.so --conf spark.gluten.sql.columnar.backend.velox.udfLibraryPaths=libmyudf.so
> Or can you give an example to describe what "same relative path" refer to?

@marin-ma Yeap and add a `--archives` example.
```
# user packaged libudf.so into udf_archives.zip
--archives /path/to/udf_archives.zip#udf_archives --conf spark.gluten.sql.columnar.backend.velox.udfLibraryPaths=./udf_archives
```
