### ISSUE TITLE
Is Gluten limited by CPU type?

### ISSUE THREAD

**Issue by hailiang9615** [oap-project/gluten#2509]
**Describe the bug**
When starting Spark-sql or Spark-thrift, there is a Java JVM crash all the time. Does the use of Gluten limit CPU types?

**To Reproduce**
**Exception information**：
Exception information:
```
23/07/28 15:55:50 WARN util.Utils: Service 'SparkUI' could not bind on port 4040. Attempting port 4041.
#
# A fatal error has been detected by the Java Runtime Environment:
#
#  SIGILL (0x4) at pc=0x00007ff24ac6d4bd, pid=231955, tid=0x00007ff608105700
#
# JRE version: OpenJDK Runtime Environment (8.0_362-b09) (build 1.8.0_362-362-b09)
# Java VM: OpenJDK 64-Bit Server VM (25.362-b09 mixed mode linux-amd64 compressed oops)
# Problematic frame:
# C  [libgluten.so+0x4184bd]  gluten::SetBackendFactory(std::function<std::shared_ptr<gluten::Backend> ()>)+0xd
#
# Failed to write core dump. Core dumps have been disabled. To enable core dumping, try "ulimit -c unlimited" before starting Java again
#
# An error report file with more information is saved as:
# /usr/lib/cluster001/spark-3.2.2-bin-hadoop3.2/hs_err_pid231955.log
#
# If you would like to submit a bug report, please visit:
#   http://bugreport.java.com/bugreport/crash.jsp
# The crash happened outside the Java Virtual Machine in native code.
# See problematic frame for where to report the bug.
```
![Uploading image.png…]()

**Expected behavior**
shell：
    ```    ./bin/spark-sql --name run_gluten  --master spark://xx.xx.xx.xx:7077 --deploy-mode client  --conf spark.plugins=io.glutenproject.GlutenPlugin --conf spark.gluten.sql.columnar.backend.lib=velox --conf spark.memory.offHeap.enabled=true --conf spark.memory.offHeap.size=20g --conf spark.gluten.loadLibFromJar=true --conf spark.driver.maxResultSize=10g --conf spark.shuffle.manager=org.apache.spark.shuffle.sort.ColumnarShuffleManager --jars /usr/lib/cluster001/spark-3.2.2-bin-hadoop3.2/glutenJar/gluten-velox-bundle-spark3.2_2.12-centos_7-0.5.0-SNAPSHOT.jar,/usr/lib/cluster001/spark-3.3.1-bin-hadoop3/glutenJar/gluten-thirdparty-lib-centos-7.jar --conf spark.driver.extraClassPath=/usr/lib/cluster001/spark-3.2.2-bin-hadoop3.2/glutenJar/gluten-velox-bundle-spark3.2_2.12-centos_7-0.5.0-SNAPSHOT.jar:/usr/lib/cluster001/spark-3.3.1-bin-hadoop3/glutenJar/gluten-thirdparty-lib-centos-7.jar --conf spark.executor.extraClassPath=/usr/lib/cluster001/spark-3.2.2-bin-hadoop3.2/glutenJar/gluten-velox-bundle-spark3.2_2.12-centos_7-0.5.0-SNAPSHOT.jar:/usr/lib/cluster001/spark-3.3.1-bin-hadoop3/glutenJar/gluten-thirdparty-lib-centos-7.jar --driver-memory 10g --executor-memory 20g --executor-cores 10 --num-executors 5 --conf spark.gluten.sql.columnar.maxBatchSize=12288 --conf spark.default.parallelism=200 --conf spark.sql.shuffle.partitions=200   ```

**Additional context**
os=centos7.9  X86_64
cpu=hygon c86
spark：3.2.2
gluten：0.5.0

**Comment by hailiang9615** [comment]
When I adjust the gluten version to 1.0.0, I get the java.lang.RuntimeException: std::bad_cast error message. Like [2361](https://github.com/oap-project/gluten/issues/2361)

**Comment by loukey-lj** [comment]
java.lang.RuntimeException: std::bad_cast
	at io.glutenproject.vectorized.PlanEvaluatorJniWrapper.nativeCreateKernelWithIterator(Native Method)
	at io.glutenproject.vectorized.NativePlanEvaluator.createKernelWithBatchIterator(NativePlanEvaluator.java:79)
	at io.glutenproject.backendsapi.velox.IteratorHandler.genFinalStageIterator(IteratorHandler.scala:292)
	at io.glutenproject.execution.WholeStageZippedPartitionsRDD.$anonfun$genFinalStageIterator$1(WholeStageZippedPartitionsRDD.scala:61)
	at io.glutenproject.execution.WholeStageZippedPartitionsRDD.compute(WholeStageZippedPartitionsRDD.scala:70)

**Comment by hailiang9615** [comment]
@rui-mo， @weiting-chen Have time to help look at it, thank you！

**Comment by hailiang9615** [comment]
The error message in Executor is: 
```
# JRE version: Java(TM) SE Runtime Environment (8.0_261-b12) (build 1.8.0_261-b12)
# Java VM: Java HotSpot(TM) 64-Bit Server VM (25.261-b12 mixed mode linux-amd64 compressed oops)
# Problematic frame:
# C  [libgluten.so+0x264b62]  JniColumnarBatchIterator::next()+0xe2
#
# Failed to write core dump. Core dumps have been disabled. To enable core dumping, try "ulimit -c unlimited" before starting Java again
#
# An error report file with more information is saved as:
# /usr/lib/cluster001/spark-3.3.1-bin-hadoop3/work/app-20230829192924-0003/7/hs_err_pid323667.log
```
