### ISSUE TITLE
[fatal bug]  can't  query hive data

### ISSUE THREAD

**Issue by loukey-lj** [oap-project/gluten#2513]
**Describe the bug**
1、create table use hive 2.1.1
create table test_str_hive_p STORED AS PARQUET as select '12' as s union select '我我' as s union select '1我' as s;

2、query by spark3.2.1 with gluten 1.0
 select * from test_str_hive_p where s='1我';
no result
 select * from test_str_hive_p where s='12';
no result 
select * from test_str_hive_p where s='我我';
no result

== Physical Plan ==
VeloxColumnarToRowExec
+- ^(9) FilterExecTransformer (isnotnull(s#22) AND (s#22 = 12))
   +- ^(9) NativeFileScan parquet bdp@default.test_str_hive_p[s#22] Batched: true, DataFilters: [isnotnull(s#22), (s#22 = 12)], Format: Parquet, Location: InMemoryFileIndex(1 paths)[hdfs://sxxx/user/hive/warehouse/test_str_hive_p], PartitionFilters: [], PushedFilters: [IsNotNull(s), EqualTo(s,12)], ReadSchema: struct<s:string>

**Comment by loukey-lj** [comment]
create table all_f_hive_sn2 stored as PARQUET as
select '22323' as f1, 'abc'  as f2, '在在在'  as f3, 'abc'   as f4, '22323'  as f5, 'abc' as f6
union 
select '22323' as f1, 'abc'  as f2, '在在在'  as f3, '22323' as f4, '在在在' as f5, '在在在' as f6      f5 f6 query no result ,maybe parquert reader‘s bug

**Comment by loukey-lj** [comment]
https://github.com/apache/arrow/issues/37006

**Comment by zhouyuan** [comment]
@loukey-lj could this due to some GBK related encoding used on inserting data? it seems UTF8 based encoding can work here

CC: @weiting-chen 

thanks, -yuan

**Comment by loukey-lj** [comment]
https://github.com/facebookincubator/velox/issues/6088

**Comment by loukey-lj** [comment]
Especially when there are spaces in the value, it is also necessary to skip the maximum and minimum value filtering.
