### ISSUE TITLE
native shuffle reader seems has bug for array type

### ISSUE THREAD

**Issue by Ma-Jian1** [oap-project/gluten#2532]
**Describe the bug**
when using `array_agg` to support `collect_list` function (PR https://github.com/oap-project/gluten/pull/2526) . I can get array result from stage 1, but the shuffle reader seems can't identify the array type

**To Reproduce**
1. pull the pr #2526 
2. run ut in GlutenDataFrameAggregateSuite
3. print result from `array_agg` in `WholeStageResultIterator::next()`

```bash
gluten outputgluten output

[ROW ROW<n2_0:ARRAY<INTEGER>,n2_1:ARRAY<INTEGER>>: 1 elements, no nulls]
[ROW ROW<n2_0:ARRAY<INTEGER>,n2_1:ARRAY<INTEGER>>: 1 elements, no nulls]
0: {1 elements starting at 0 {1}, 1 elements starting at 0 {2}}
0: {2 elements starting at 0 {2, 3}, 2 elements starting at 0 {2, 4}}
```

**Expected behavior**

**Additional context**

**Comment by jinchengchenghh** [comment]
This may be not shuffle read bug.
write row vector write row vector [ROW ROW<n2_0:ARRAY<INTEGER>,n2_1:ARRAY<INTEGER>>: 1 elements, no nulls]
shuffle read type ROW<buf:VARBINARY,buf:VARBINARY>
Maybe this hasaggregate needs post projection.
 https://github.com/oap-project/gluten/blob/main/backends-velox/src/main/scala/io/glutenproject/execution/HashAggregateExecTransformer.scala#L857C23-L857C42

**Comment by PHILO-HE** [comment]
I caught the root reason. Will fix it. @jinchengchenghh, thank you for giving some clues.

**Comment by winningsix** [comment]
@PHILO-HE did we close this already? If so, we can paste PR link here and close this issue. Thanks!

**Comment by PHILO-HE** [comment]
We have one PR to fix this issue. This issue is fixed, but still have some inconsistent issue for some inputs.
https://github.com/oap-project/gluten/pull/2669
