### ISSUE TITLE
[VL] java.lang.RuntimeException: java.io.FileNotFoundException: libthrift-0.13.0.so

### ISSUE THREAD

**Issue by sandeep-biddala** [oap-project/gluten#2549]
**Describe the bug**
I get java.lang.RuntimeException: java.io.FileNotFoundException: libthrift-0.13.0.so when running Spark in standalone mode.

Spark Version: 3.2.2
Gluten Version: 1.0.0

I checked by including the thirdparty jar released for 0.5.0 but I get the same error.

**To Reproduce**
Run Spark in standalone mode.

**Expected behavior**
SparkContext should be loaded without errors.

**Comment by PHILO-HE** [comment]
Hi @sandeep-biddala, did you enable `spark.gluten.loadLibFromJar` in your test? It should not be enabled if you are using our posted 1.0.0 release jar which is generated through static build. There is a PR to clarify the usage of that config: https://github.com/oap-project/gluten/pull/2570
