### ISSUE TITLE
question: is gluten published on maven central?

### ISSUE THREAD

**Issue by MasseGuillaume** [oap-project/gluten#2568]
I would like to use substrait-spark in one of my project.

I saw you created https://issues.sonatype.org/browse/OSSRH-79538

however, I did not find any published artifact under io.glutenproject (https://search.maven.org/search?q=g:io.glutenproject)

**Comment by PHILO-HE** [comment]
Hi @weiting-chen, could you please make a clarification?

**Comment by weiting-chen** [comment]
@MasseGuillaume We are still working on this, there are some technical issue under fixing, and we will publish a jar soon.

Thanks,
Weiting.

**Comment by weiting-chen** [comment]
@MasseGuillaume 
Gluten's binary jar has been released to maven repository, please check below link
https://repo1.maven.org/maven2/io/glutenproject/gluten-package/1.0.0/
