### ISSUE TITLE
[VL] Can the community provide version 1.0.0 of the thirdparty-centos7 jar?

### ISSUE THREAD

**Issue by rhh777** [oap-project/gluten#2590]
I followed the steps in dev/package.sh to install a lot of so library in my environment and punch out the jar packages. But there are still problems at runtime.  I just saw that the centos8 package is already in the release list.

Can the community provide thirdparty-centos7 packs?

I tried to use the 1.0.0-bundle package with the 0.5.0-thirdparty package, but ran into problems.
<img width="1667" alt="image" src="https://github.com/oap-project/gluten/assets/41908930/8f9d3b86-1464-4c79-b03f-47b22f009d75">

**Comment by rhh777** [comment]
https://github.com/oap-project/gluten/pull/2570 After seeing this PR, I understand.

**Comment by PHILO-HE** [comment]
Hi @rhh777, could you please clarify a bit about this std::bad_cast issue? e.g., how this issue can happen and how to fix this issue. I note a few users encountered this issue. Thanks!

**Comment by rhh777** [comment]
> Hi @rhh777, could you please clarify a bit about this std::bad_cast issue? e.g., how this issue can happen and how to fix this issue. I note a few users encountered this issue. Thanks!

Sorry, I didn't fix this issue. Because when I saw that the document was updated, the bundle jar using 1.0.0 does not need to set spark.gluten.loadLibFromJar, so I don't need to import the thirdparty package. In this way, I bypassed this problem , not sure if my understanding is correct.

**Comment by rhh777** [comment]
By the way, what is the purpose of the third-party jar after 1.0.0?

**Comment by PHILO-HE** [comment]
> > Hi @rhh777, could you please clarify a bit about this std::bad_cast issue? e.g., how this issue can happen and how to fix this issue. I note a few users encountered this issue. Thanks!
> 
> Sorry, I didn't fix this issue. Because when I saw that the document was updated, the bundle jar using 1.0.0 does not need to set spark.gluten.loadLibFromJar, so I don't need to import the thirdparty package. In this way, I bypassed this problem , not sure if my understanding is correct.

I see. It is just a config issue.


> By the way, what is the purpose of the third-party jar after 1.0.0?

Dynamic linking is not discarded and it is used by default in building the project. So third-party jar can still be used by enabling the mentioned config, working together with the jar with dynamic linked native lib.
