### ISSUE TITLE
[CH] precision may overflow 

### ISSUE THREAD

**Issue by shuai-xu** [oap-project/gluten#2591]
**Describe the bug**
Now the result precision of divide and multiply is the sum of inputs, if there are multi divede together, the precision may overflow and throw exception like " Wrong precision: it must be between 1 and 76, got 102". 

**To Reproduce**
run sql `select
                     (p+z*z/(2.0*n))/(1.0+z*z/n) as price from (
select (0.03*clk+0.07*like+0.3*comment+0.6*share)/1.0/(exposure+preview_enter) as p,
       1.96 as z, exposure+preview_enter as n
       from xxxxx where day = '2023-07-20'
                                        ) limit 1`

**Comment by loneylee** [comment]
@shuai-xu 有执行计划可以贴一下么

**Comment by loneylee** [comment]
RC: Spark中最大精度为38，当前backend按照spark转换后未检查最大精度
