### ISSUE TITLE
[VL]The problem with running./build_velox.sh stopping

### ISSUE THREAD

**Issue by zombie0826** [oap-project/gluten#2615]
**Describe the bug**
I don't know if it's a bug, I don't know why it doesn't continue after running to this point.

![image](https://github.com/oap-project/gluten/assets/141295844/8613c631-6324-424b-a6f8-4e1c4727e44c)

Can someone guide me？

**Comment by XorSum** [comment]
This might be a slow internet problem. It took me an hour to download boost.
