### ISSUE TITLE
[CORE] JsonString is initialized during wholestage transform

### ISSUE THREAD

**Issue by loneylee** [oap-project/gluten#2626]
**Is your feature request related to a problem or challenge? Please describe what you are trying to do.**
In `WholeStageTransformer`, `planJson` is initialized during wholestage doWholeStageTransform. It's a debug message and will takes 10~100ms in driver. Should not initialized all times.

**Comment by PHILO-HE** [comment]
Suppose fixed. Closing this issue. Thanks!
