### ISSUE TITLE
Let C2R/R2C operators be parts of whole stage

### ISSUE THREAD

**Issue by Yohahaha** [oap-project/gluten#2672]
### Description

Gluten insert C2R/R2C for fallback operators as boundaries of WholeStageTransformer, it's hard to manage stateful resources across two RDDs and bring lots complexity.

If we merge C2R/R2C into WholeStageTransformer, we can gain benefits from
1) offload only one RDD as native fragment, it's help to manage resources like initialize when split start and release when split end.
2) provide a consistent row based output view from Spark's point, avoid consider both Gluten C2R and Spark C2R in the same time.

I'm curious about why we choose separate C2R/R2C from whole stage? could someone give me some inputs? CC @zhouyuan @zhztheplayer @FelixYBW

**Comment by FelixYBW** [comment]
I think it's copied from Gazelle, just no one merge it into transformer. Feel free to submit a PR to do the merge

**Comment by Yohahaha** [comment]
This idea has conflict with columnar shuffle, close it.

**Comment by FelixYBW** [comment]
Yes, we just talked it in our team. Currently C2R use the same interface as shuffle mapper and parquet writer, R2C use the same interface as reducer reader. the transformer interface is columnar batch in, columnar batch out. If we merge the two operator in operator, we need to modify many interfaces.
