### ISSUE TITLE
Spark parquet scan always return timestamp_ntz column when reading test file

### ISSUE THREAD

**Issue by marin-ma** [oap-project/gluten#2684]
### Backend

VL (Velox)

### Bug description

https://github.com/oap-project/gluten/pull/2674#issuecomment-1670870359
Temporarily disable test case "SPARK-36726: test incorrect Parquet row group file offset" in `GlutenParquetIOSuite` for Spark33

**Comment by Yohahaha** [comment]
It maybe related with local timezone? my build machine can pass it.
