### ISSUE TITLE
[VL]HdfsConfigNotFound: config key: dfs.ha.namenodes.xxxx not found

### ISSUE THREAD

**Issue by ziwuse** [oap-project/gluten#2689]
### Backend

VL (Velox)

### Bug description

spark-shell \
 --master yarn --deploy-mode client \
 --conf spark.plugins=io.glutenproject.GlutenPlugin \
 --conf spark.memory.offHeap.enabled=true \
 --conf spark.memory.offHeap.size=10g \
 --conf spark.shuffle.manager=org.apache.spark.shuffle.sort.ColumnarShuffleManager \
 --jars /xxx/xxx/gluten-velox-bundle-spark3.2_2.12-centos_7-1.0.0.jar
 启动spark-shell一切正常，读取parquet文件时报错 HdfsConfigNotFound: config key: dfs.ha.namenodes.xxxx not found，但实际上是配好了的，不使用gluten启动spark-shell的话可以正常工作

![1691578554806](https://github.com/oap-project/gluten/assets/59003075/e85033a0-a29d-4737-89ea-4613068f042d)

### Spark version

spark3.2.1-hadoop2.7

**Comment by ziwuse** [comment]
需要配置hdfs支持，不是bug

**Comment by hailiang9615** [comment]
Hello, how to configure this? Does it need to be modified in the hdfs-site .xml file, or in spark_default.conf?

**Comment by shaileneF** [comment]
> 需要配置hdfs支持，不是bug

您好，我遇到了完全一样的问题，请问是怎么配置的呀？
