### ISSUE TITLE
[fatal bug] query case when with hour result wrong

### ISSUE THREAD

**Issue by loukey-lj** [oap-project/gluten#2752]
### Backend

VL (Velox)

### Bug description

spark3.2.1 gluten 1.0

1、create table test_tm STORED AS PARQUET as select '2023-08-08 07:31:36' as t;

2、select t, case when hour(t) < 8 then 1 else 0 end from test_tm;
      wrong result: 2023-08-08 07:31:36	0   

3、select t,  hour(t),  hour(t) < 8,case when hour(t) < 8 then 1 else 0 end from test_tm;
      correct result： 2023-08-08 07:31:36	7	true	1

### Spark version

3.2.1

### System information

centos7

### Relevant logs

E20230814 09:32:51.508433 483710 Exceptions.h:68] Line: ../.././velox/type/Conversions.h:44, Function:cast, Expression:  Conversion to TIMESTAMP is not supported, Source: USER, ErrorCode: UNSUPPORTED
E20230814 09:32:51.508608 483710 Exceptions.h:68] Line: ../../velox/expression/CastExpr.cpp:301, Function:operator(), Expression:  Failed to cast from VARCHAR to TIMESTAMP: 2023-08-08 07:31:36. Conversion to TIMESTAMP is not supported, Source: USER, ErrorCode: INVALID_ARGUMENT

**Comment by zhouyuan** [comment]
@loukey-lj thanks for reporting, timestamp support is not completed and seems buggy. Gluten didn't fallback correctly "cast from VARCHAR to TIMESTAMP"

-yuan

**Comment by zhouyuan** [comment]
might be related: https://github.com/oap-project/gluten/pull/2823

**Comment by loukey-lj** [comment]
We have solved it internally
