### ISSUE TITLE
case when unix_timestamp(xx) query data result wrong

### ISSUE THREAD

**Issue by loukey-lj** [oap-project/gluten#2759]
### Backend

VL (Velox)

### Bug description

select plan_depart_tm, assigned_tm,case when (unix_timestamp(plan_depart_tm)-unix_timestamp(assigned_tm))/3600>=48  then -2 else 0 end from xx

2023-07-16 15:20:00     2023-07-07 09:24:25     0

### Spark version

3.2.1

### Relevant logs

```bash
E20230815 13:58:50.553767 325101 Exceptions.h:68] Line: ../../velox/functions/lib/DateTimeFormatter.cpp:1452, Function:buildJodaDateTimeFormatter, Expression:  Specifier A is not supported., Source: USER, ErrorCode: UNSUPPORTED
E20230815 13:58:50.553875 325101 Exceptions.h:68] Line: ../../velox/functions/lib/DateTimeFormatter.cpp:1452, Function:buildJodaDateTimeFormatter, Expression:  Specifier A is not supported., Source: USER, ErrorCode: UNSUPPORTED
```

**Comment by zhouyuan** [comment]
@loukey-lj thanks for reporting, this commit may help to fix the issue on `unix_timestamp`, but it missed 1.0 
https://github.com/oap-project/gluten/commit/6f6fd0dabb8df0bcde0c2b37a20fb9a5674093b1

Thanks, -yuan

**Comment by loukey-lj** [comment]
We have solved it internally
