### ISSUE TITLE
TPCDS q4 need more memory and run slower after memory arbitrator 

### ISSUE THREAD

**Issue by Yohahaha** [oap-project/gluten#2762]
### Backend

VL (Velox)

### Bug description

Before memory arbitrator enabled, we run sf1000 TPCDS with 4core 8g(off-heap) per executor successfully, and total time was `29.45`.

After that feature, we failed with same memory config, but success with 10g(off-heap), and total time was `37.6`.

**Comment by Yohahaha** [comment]
CC @zhouyuan @zhztheplayer

**Comment by Yohahaha** [comment]
Before: stage metrics shows peek memory was 56MB.
After: 2.4GiB.

**Comment by Yohahaha** [comment]
@zhouyuan 
"before" means commits end up to 7.25, "after" means newly commits.

"before" not trigger spill, "after" trigger spill, but default spill strategy config does not passed to native correctly by default(will submit PR to fix), so spill failed.

**Comment by Yohahaha** [comment]
https://github.com/oap-project/gluten/pull/2769

**Comment by zhztheplayer** [comment]
> Before: stage metrics shows peek memory was 56MB. After: 2.4GiB.

This is something abnormal. Can you share more details about this case?

**Comment by Yohahaha** [comment]
I probably know the root issue which cause task peek memory always increase, let me try to fix.

**Comment by zhztheplayer** [comment]
> @zhouyuan "before" means commits end up to 7.25, "after" means newly commits.
> 
> "before" not trigger spill, "after" trigger spill, but default spill strategy config does not passed to native correctly by default(will submit PR to fix), so spill failed.

Sorry, after some investigation it's probably related to a recent Velox rebase action https://github.com/oap-project/gluten/pull/2370/files#diff-013353c1aa2ebe3f4c5c014b936dd52b2f91bef0a51421c1a901a57cac361f17R83 to change default strategy by mistake.

I've applied your PR https://github.com/oap-project/gluten/pull/2769, it should be back to normal.

**Comment by Yohahaha** [comment]
I could share the memory config of TPCDS sf1000 in our benchmark, each executor has 4cores and 8G off-heap and 2G overhead and would not trigger spill.

As we talked in the meeting @weiting-chen  , your guys could find suitable memory config of your benchmark which has less memory but not trigger spill, thus we can guarantee follow changes would not cause peek memory increase.
