### ISSUE TITLE
GHA report "Error: No space left on device" for velox backend testing

### ISSUE THREAD

**Issue by weiting-chen** [oap-project/gluten#277]
**Describe the bug**
GHA report "Error: No space left on device" when running velox backend testing during PR submission.

**To Reproduce**
When submitting a PR and running velox backend, it would happen occasionally.

**Expected behavior**
Expect to run pass velox backend testing without any error message.

**Comment by jinchengchenghh** [comment]
Because temp directories /tmp/spark_columnar_plugin* not clean, use crontab to clean this dir, fixed
