### ISSUE TITLE
[VL] get_json object error

### ISSUE THREAD

**Issue by FelixYBW** [oap-project/gluten#2776]
### Backend

VL (Velox)

### Bug description

Error Code: INVALID_ARGUMENT
Context: get_json_object(itemdata, $.offers[0]['availability']:VARCHAR)
Function: JsonExtractor
File: /gluten-731/ep/build-velox/build/velox_ep/velox/functions/prestosql/json/JsonExtractor.cpp
Line: 61

### Spark version

3.2.0

**Comment by PHILO-HE** [comment]
We have a pending patch to let the execution offloaded to a simdjson-based function. Assume there would be no such issue with the new function used. I will track this issue.
