### ISSUE TITLE
[VL]Run CI with DEBUG build mode to enhance stability

### ISSUE THREAD

**Issue by Yohahaha** [oap-project/gluten#2783]
### Description

Velox CI will run with both RELEASE and DEBUG mode, so the check which only enabled in DEBUG mode will work and help avoid potential bugs. However, Gluten CI all runs in RELEASE mode, and I found some DEBUG check will fail when compile Gluten cpp with DEBUG mode.

So, the proposal is compile Gluten cpp in DEBUG mode in CI, this may need changes from both Gluten CI and oap/velox CI. cc @FelixYBW @zhouyuan

**Comment by zhouyuan** [comment]
@Yohahaha thanks for this input, we actually have some nightly Jenkins jobs running with DEBUG mode here, but didnt enable this in GHA. I think the main issue is using DEBUG mode will increase the tests time. Can you please share the failed cases in your tests, is this from Spark unit tests?  

thanks, -yuan
