### ISSUE TITLE
[VL] Separate each jni wrapper to different files

### ISSUE THREAD

**Issue by Yohahaha** [oap-project/gluten#2845]
### Description

JniWrapper.cc is too large and may be larger in the future, we could separate it into sub dirs when some stateful static variables be removed, and get benefits from readability and UT.

**Comment by zhztheplayer** [comment]
This sort of refactor is needed. 

The thing is that we should find a proper time to apply the change, since it may easily conflict with other pending PRs.

**Comment by Yohahaha** [comment]
> The thing is that we should find a proper time to apply the change, since it may easily conflict with other pending PRs.

Good point, I prefer do the refactor in weekend, before that, let's discuss the structure we expected.

**Comment by Yohahaha** [comment]
Also cc @ulysses-you @FelixYBW @zhouyuan

**Comment by ulysses-you** [comment]
I think make jni file name align with java class is good. The `VexloJniWrapper` should also be taken into account. e.g., The java class `PlanEvaluatorJniWrapper` has several jni methods that map to both `JniWrapper` and `VexloJniWrapper`. What's the really difference between `VexloJniWrapper` and `JniWrapper` ?

**Comment by zhztheplayer** [comment]
> The java class PlanEvaluatorJniWrapper has several jni methods that map to both JniWrapper and VexloJniWrapper.

PlanEvaluatorJniWrapper -> VeloxJniWrapper

Such mappings should be finally eliminated  IIUC. We already had `Backend` and `ExecutionCtx` as the APIs across backends.
