### ISSUE TITLE
[VL] OrcTest was broken and should be fixed or skip

### ISSUE THREAD

**Issue by Yohahaha** [oap-project/gluten#2862]
### Description

PR #1181 exclude OrcTest in CI with no comments, and PR #1568 add convertBatch method to force convert arrow batch to Velox batch, cause a dynamic cast failure in OrcTest.

Does OrcTest is outdated? If yes, let's remove or use GTEST_SKIP(), if no, why exclude? who is expect to fix this?
CC @jinchengchenghh @zuochunwei

**Comment by jinchengchenghh** [comment]
I remove it because it will raise exception `miss some orc files` which will generate by other program, maybe benchmark or the java unit test.

**Comment by Yohahaha** [comment]
Thanks for explanation!
