### ISSUE TITLE
build gluten with velox backend on centos7

### ISSUE THREAD

**Issue by zombie0826** [oap-project/gluten#2910]
### Problem description

Compile gluten with velox backend on centos7 . If enable_vcpkg=off, spark generates an error message. If enable_vcpkg=on,an error message is displayed.

The official image is used to compile, and the built jar package is tested on a virtual machine

What is the problem?

### System information

spark3-sql \
--master yarn  \
--deploy-mode client \
--conf spark.plugins=io.glutenproject.GlutenPlugin \
--conf spark.gluten.loadLibFromJar=false \
--conf spark.shuffle.manager=org.apache.spark.shuffle.sort.ColumnarShuffleManager \
--driver-cores 1 \
--driver-memory 5G \
--executor-cores 5 \
--executor-memory 10G \
--num-executors 10 \
--conf spark.memory.offHeap.enabled=true \
--conf spark.memory.offHeap.size=11G \
--jars /pathto/gluten-velox-bundle-spark3.3_2.12-centos_7-1.0.0.jar \

./dev/buildbundle-veloxbe.sh --enable_vcpkg=off:
![off](https://github.com/oap-project/gluten/assets/141295844/5f774d1c-c2b3-4ae7-833f-69dbfd3844be)
./dev/buildbundle-veloxbe.sh --enable_vcpkg=on:
![image](https://github.com/oap-project/gluten/assets/141295844/c032c815-49bf-47c6-9aea-b439879babe1)

**Comment by zhejiangxiaomai** [comment]
Here is CI build step gluten on centos. 
https://github.com/oap-project/gluten/blob/main/.github/workflows/velox_be.yml#L366-L413
And here is docker file https://github.com/oap-project/gluten/blob/main/tools/gluten-te/centos/dockerfile-buildenv. Maybe it can help you.
