### ISSUE TITLE
[VL]Bad memory usage with Spark speculation, possible memory leakage

### ISSUE THREAD

**Issue by jackylee-ch** [oap-project/gluten#2952]
### Backend

VL (Velox)

### Bug description

While running TPCDS with `spark.speculation=true`, we meet the `Bad memory usafe problem`. It seems that we have some memory unreleased after task is killed.
```
terminate called after throwing an instance of 'facebook::velox::VeloxRuntimeError'
  what():  Exception: VeloxRuntimeError
Error Source: RUNTIME
Error Code: INVALID_STATE
Reason: Bad memory usage track state: Memory Pool[op.0.0.0.TableScan LEAF MALLOC track-usage thread-safe]<unlimited max capacity unlimited capacity used 24.00KB available 1000.00KB reservation [used 24.00KB, reserved 1.00MB, min 0B] counters [allocs 27, frees 26, reserves 0, releases 1, collisions 0])>
Retriable: False
Expression: (usedReservationBytes_ == 0) && (reservationBytes_ == 0) && (minReservationBytes_ == 0)
Function: ~MemoryPoolImpl
File: /code/gluten/ep/build-velox/build/velox_ep/velox/common/memory/MemoryPool.cpp
Line: 393
Stack trace:
# 0  _ZN8facebook5velox7process10StackTraceC1Ei
# 1  _ZN8facebook5velox14VeloxExceptionC1EPKcmS3_St17basic_string_viewIcSt11char_traitsIcEES7_S7_S7_bNS1_4TypeES7_
# 2  _ZN8facebook5velox6detail14veloxCheckFailINS0_17VeloxRuntimeErrorERKSsEEvRKNS1_18VeloxCheckFailArgsET0_
# 3  _ZN8facebook5velox6memory14MemoryPoolImplD2Ev
# 4  _ZNSt16_Sp_counted_baseILN9__gnu_cxx12_Lock_policyE2EE24_M_release_last_use_coldEv
# 5  _ZN8facebook5velox4exec4TaskD2Ev
# 6  _ZNSt15_Sp_counted_ptrIPN8facebook5velox4exec4TaskELN9__gnu_cxx12_Lock_policyE2EE10_M_disposeEv
# 7  _ZNSt16_Sp_counted_baseILN9__gnu_cxx12_Lock_policyE2EE24_M_release_last_use_coldEv
# 8  _ZN6gluten34WholeStageResultIteratorFirstStageD0Ev
# 9  _ZNSt16_Sp_counted_baseILN9__gnu_cxx12_Lock_policyE2EE10_M_releaseEv
# 10 Java_io_glutenproject_vectorized_ColumnarBatchOutIterator_nativeClose
# 11 0x00007fc74e896768
# 12 0x00007fc74e47a37c
```

### Spark version

Spark-3.3.x

### Spark configurations

spark.speculation true

### System information

The latest commit: e6ec25135ce53673e7020791772b36c78304fa98
OS: CentOS7.6
GCC: 12.1

**Comment by zhouyuan** [comment]
@jackylee-ch thanks for reporting, could you please share more settings on speculation testing, other than `spark.speculation=true` ?

thanks, -yuan

**Comment by ulysses-you** [comment]
Is it a valid commit revision ?

```
git log e6ec25135ce53673e7020791772b36c78304fa98
fatal: bad object e6ec25135ce53673e7020791772b36c78304fa98
```

**Comment by jackylee-ch** [comment]
Oh, sorry, the commit `e6ec25135ce53673e7020791772b36c78304fa98` is from https://github.com/oap-project/gluten/pull/2888 before it is merged. The actual main commit is `a06e4f0a4662d69623c3b62cd87d013237e33b45`

**Comment by Yohahaha** [comment]
Have you try to fix that? if not, I can submit a fix.

**Comment by jackylee-ch** [comment]
> Have you try to fix that? if not, I can submit a fix.

I have not found the way to fix it. It' greate if you can fix it right now.

**Comment by Yohahaha** [comment]
https://github.com/oap-project/gluten/pull/2965 this pr should fix above error, but I'm not sure this is the root cause. 

The root cause we need to solve is release all memory when speculation task finished/killed.

**Comment by Yohahaha** [comment]
Could you share the speculation task's execution plan? which means the executed operator/RDD of speculation task.

**Comment by Yohahaha** [comment]
CC @zhztheplayer

**Comment by Yohahaha** [comment]
Thanks! you can try that patch if you would to, and hope give more feedbacks on this case.

**Comment by jackylee-ch** [comment]
@Yohahaha I have tried the https://github.com/oap-project/gluten/pull/2965, and still find this problem in q3.
The related physical plan for the failed stage in q3 is bellow.
```
<img width="819" alt="image" src="https://github.com/oap-project/gluten/assets/10897625/0e961ee6-6cab-496d-9f61-5dd7624c8c22">
```

**Comment by Yohahaha** [comment]
@jackylee-ch what about q60?

**Comment by jackylee-ch** [comment]
> @jackylee-ch what about q60?

we still have the problem, it is not fixed

**Comment by zhztheplayer** [comment]
@jackylee-ch Was there any other abnormal log above the error message you pasted?

**Comment by zhztheplayer** [comment]
@jackylee-ch Also, is `memory leak` accurate to describe this issue? Can you elaborate on the leakage part?

**Comment by jackylee-ch** [comment]
> @jackylee-ch Also, is `memory leak` accurate to describe this issue? Can you elaborate on the leakage part?

Compared with `memory leak`, I prefer that some memory is not closed normally during task killing, because each time this problem is reported, it is accompanied by `TaskKilledException `.

**Comment by zhztheplayer** [comment]
> Compared with memory leak, I prefer that some memory is not closed normally during task killing, because each time this problem is reported, it is accompanied by TaskKilledException .

Is the executor still alive after getting this error?

**Comment by jackylee-ch** [comment]
> Is the executor still alive after getting this error?

No, it is terminated because of this problem.

**Comment by jackylee-ch** [comment]
@zhztheplayer @Yohahaha  Have you tried run TPCDS with speculation? It should be easy to reproduct.

**Comment by zhztheplayer** [comment]
> @zhztheplayer @Yohahaha Have you tried run TPCDS with speculation? It should be easy to reproduct.

I'll have a try. Is `spark.speculation=true` enough for reproducing the issue?

**Comment by jackylee-ch** [comment]
Basically, `spark.speculation=true` can reproduce the problem. However if your environment is relatively good overall and rarely run speculative tasks, consider setting more aggressive configurations. Such as `spark.speculation.multiplier=1.1`, `spark.speculation.quantile=0.3`
