### ISSUE TITLE
[VL] Track all failed UT for Velox upstream

### ISSUE THREAD

**Issue by marin-ma** [oap-project/gluten#2961]
### Description

1. ORC support is still not merged to Velox Upstream. Temporarily disable ALL ORC suites. https://github.com/oap-project/gluten/pull/2944
2. Command to run Gluten Spark3.2 Unit tests 
```
mvn clean install -Pspark-3.2 -Pspark-ut -Pbackends-velox -Prss -DargLine="-Dspark.test.home=/home/sparkuser/github/apache/spark" -DtagsToExclude=io.glutenproject.tags.UDFTest,io.glutenproject.tags.SkipTestTags
```

#### Parquet write: Spark utilizes Snappy compression to write data, but currently Velox only supports uncompressed data. As a result, the following unit tests have failed. The discussion with community is [here](https://github.com/facebookincubator/velox/discussions/6193#discussioncomment-7077923).

- test write parquet with compression codec

### Gluten Spark 3.2 UT Failed list:

Ignored due to unopened Window change:
- udf/udf-window.sql - Scala UDF *** FAILED ***
- udf/udf-window.sql - Regular Python UDF *** FAILED ***
- udf/udf-window.sql - Scalar Pandas UDF *** FAILED ***
- range between should accept int/long values as boundary *** FAILED ***
- unbounded preceding/following range between with aggregation *** FAILED ***
- sliding range between with aggregation *** FAILED ***
- rows between should accept int/long values as boundary

Ignored due to [double precision loss](https://github.com/facebookincubator/velox/pull/6051#issuecomment-1731028215).
- SPARK-22271: mean overflows and returns null for some decimal variables

**Comment by FelixYBW** [comment]
All Spark3.2 UT passed
