### ISSUE TITLE
Linking velox_plan_conversion_test fail due to gtest upgrade

### ISSUE THREAD

**Issue by surnaik** [oap-project/gluten#3001]
### Problem description

I think we're hitting the issue related to gtest upgrade. This problem is fixed for exec_backend_test. 

### System information

Velox System Info v0.0.2
Commit: bfa0d89f25ce41526b60a6757ecf4cd27a4cf9a6
CMake Version: 3.16.3
System: Linux-6.3.11-1rodete1-amd64
Arch: x86_64
C++ Compiler: /usr/bin/c++
C++ Compiler Version: 9.4.0
C Compiler: /usr/bin/cc
C Compiler Version: 9.4.0
CMake Prefix Path: /usr/local;/usr;/;/usr;/usr/local;/usr/X11R6;/usr/pkg;/opt

### CMake log

```bash
[ 83%] Linking CXX executable velox_plan_conversion_test
/usr/bin/ld: /root/docker-repos/gluten/ep/build-velox/build/velox_ep/_build/release/velox/exec/tests/utils/libvelox_exec_test_lib.a(QueryAssertions.cpp.o): in function `void testing::internal::DefaultPrintTo<facebook::velox::Type>(testing::internal::WrapPrinterType<(testing::internal::DefaultPrinterType)0>, facebook::velox::Type const&, std::ostream*)':
QueryAssertions.cpp:(.text._ZN7testing8internal14DefaultPrintToIN8facebook5velox4TypeEEEvNS0_15WrapPrinterTypeILNS0_18DefaultPrinterTypeE0EEERKT_PSo[_ZN7testing8internal14DefaultPrintToIN8facebook5velox4TypeEEEvNS0_15WrapPrinterTypeILNS0_18DefaultPrinterTypeE0EEERKT_PSo]+0x9e): undefined reference to `testing::internal2::PrintBytesInObjectTo(unsigned char const*, unsigned long, std::ostream*)'
collect2: error: ld returned 1 exit status
make[2]: *** [velox/tests/CMakeFiles/velox_plan_conversion_test.dir/build.make:357: velox/tests/velox_plan_conversion_test] Error 1
make[1]: *** [CMakeFiles/Makefile2:655: velox/tests/CMakeFiles/velox_plan_conversion_test.dir/all] Error 2
make: *** [Makefile:141: all] Error 2
```

**Comment by surnaik** [comment]
@zhejiangxiaomai Could you please take a look at this once?

**Comment by surnaik** [comment]
Thanks @zhejiangxiaomai for taking a look.
You had earlier fixed a similar issue #1289 . This issue seems similar to that. There is a bug in gtest 1.13 and one of the accepted solutions is to override the << operator. This is the bug - https://github.com/google/googletest/issues/3816

While building gluten with tests enabled, I'm hitting this issue, this didn't occur to me before, but has now started happening. Since you had fixed this earlier for exec_backend_test, I think you might have some more information.

My build steps are very simple, I just run ./dev/package.sh

**Comment by zhejiangxiaomai** [comment]
Ok, I know. I remember this issue. The solution is override the << operator. I think may be you need check your environment. Because gtest version is not changed.  And our CI workflow is work well now.  May be you can follow this 
 step by step. https://github.com/oap-project/gluten/blob/main/.github/workflows/velox_be.yml#L46-L98

**Comment by surnaik** [comment]
Let me try it out. Thanks!
