### ISSUE TITLE
[CH/VL] Memory management should only care about physical memory

### ISSUE THREAD

**Issue by zhanglistar** [oap-project/gluten#3019]
### Description

Now, the `CHManagedCHReservationListener` class is a memory accounting to track memory allocation and free. This is a total memory accounting including physical memory and virtual memory.
But in vanilla spark, the memory is the physical memory, because that's the limited resources.
So, gluten, we should also care about physical memory, that's fair. Or else, gluten can be early stoped by OOM like what this issue describes https://github.com/oap-project/gluten/issues/2964.
As far I know, velox backend also have the same issue.

**Comment by taiyang-li** [comment]
I'll add a spark config to control whether to throw exception when total memory(including physical memory and virtual memory) exceeds threshold.
