### ISSUE TITLE
[CH] MapFromArrays throws exception

### ISSUE THREAD

**Issue by shuai-xu** [oap-project/gluten#3071]
### Backend

CH (ClickHouse)

### Bug description

When run sql, it throw exception as bellow:
<img width="1439" alt="image" src="https://github.com/oap-project/gluten/assets/20960838/757ca7cb-7a42-43db-b745-c606526b682c">
It shows the offsets differ from 5078:
<img width="525" alt="image" src="https://github.com/oap-project/gluten/assets/20960838/b334afb0-de1f-4796-b211-800a447b03d7">

### Spark version

Spark-3.3.x

**Comment by shuai-xu** [comment]
@taiyang-li d_1216_0

**Comment by taiyang-li** [comment]
fixed by https://github.com/oap-project/gluten/pull/3106/files
