### ISSUE TITLE
[VL] EP: Centralized lifecycle management for C++ / JNI contextual objects

### ISSUE THREAD

**Issue by zhztheplayer** [oap-project/gluten#3077]
## Description

(EP in title stands for enhancement proposal. Let's have a standardized way to organize all the EPs in future.)

Derived from https://github.com/oap-project/gluten/issues/3040, thanks @Yohahaha for putting this to table.

This is to propose some basic designs about a new API to manage C++ / JNI contextual objects whose lifecycles were bound to Spark's task context. Doing this can help reducing the code complexity of JNI code (including removing the global concurrent maps in JniWrapper.cc) to ensure the maintainability of the part of code.

## Solution

The "Phase *" is a rough estimation of work breaking down. We'd create PRs on demand.

### Phase 1

* In C++, rename VeloxInitializer to VeloxBackend, this could make the code align with Java side "backend" definition that indicates a global factory or global metadata storage at process wise.
* In C++, introduce a new context API whose lifecycle aligns with Spark TaskContext. I would suggest using name ExecutionContext (and VeloxExecutionContext as derived name). TaskContext would also be a choice but it collides with Spark's TaskContext so that we may have to use NativeTaskContext in Java which looks a little bit tedios.
(Besides, Velox has ExecCtx. We use longer name that it to distinguish with it)
* In Java, introduce a mirrored structure ExecutionContext to which the C++ side ExecutionContext can bind. The objects should be managed by TaskResouceRegistry.
* In C++, move the APIs in old VeloxBackend class to ExecutionContext. There were two stateful members inputIters_ and veloxPlan_, we may manage to eliminate them in the new class.
* Change C++ and Java code, to pass ExecutionContext through the JNI APIs that requires for it.

### Phase 2
In C++, move the concurrent maps (except for memory manager), from JniWrapper to ExecBackend. The concurrency doesn't apply to ExecutionContext so unordered_map may be enough.

### Phase 3, and more
Develop a way to initialize MemoryManager in ExecutionContext's initialization. Spiller part will be tricky so we put this into TODOs.

## Notes

After this refactor, we expect JniWrapper would be less coupled with the actual query execution procedure. We may get some bonuses in C++ unit testing from this kind of decoupling, I am not sure, but it should be expected.

Another note, during development, we should keep in mind that ExecutionContext is just bound to SparkContext through TaskResourceRegistry in practice. Its design should be more scalable as long as it's to be used in a single thread (which means, we don't have to grantee thread-safety). One could create more instances in a Spark task context if wanted.

**Comment by zhztheplayer** [comment]
cc @Yohahaha Thanks for your willing to help in advance!

Probably I can too take some work later on, after finishing some current works.

And please feel free to submit sub-issues or draft PRs as soon as you get started. Thanks!

**Comment by Yohahaha** [comment]
Thanks for the detailed design! @zhztheplayer 

I have implemented a draft contains patch 1 and patch 2, and I agree with the design of separate these work, will separate and submit patch 1 later.

The most confused work for me is patch 3, it would be great if you could merge memory managers into one in current lifecycle management.

**Comment by Yohahaha** [comment]
Tracking releated issues
https://github.com/oap-project/gluten/issues/2845

**Comment by zhztheplayer** [comment]
Closing as resolved. Feel free to reopen if any remaining issues.
