### ISSUE TITLE
[CH] CAST float-type string to int is null 

### ISSUE THREAD

**Issue by KevinyhZou** [oap-project/gluten#3094]
### Backend

CH (ClickHouse)

### Bug description

Insert a float-type string into a table , like
```
insert into test_tbl3 values(21, '1.8', 'n');
```

and then do query `select cast(name as int) from test_tbl3 where id = 21`,  and we get the result is null  as below
0: jdbc:hive2://localhost:10010> select cast(name as int) from test_tbl3 where id = 21;
+-------+
| name  |
+-------+
| NULL  |
+-------+

as spark do the query the result is 1;

### Spark version

Spark-3.3.x

**Comment by taiyang-li** [comment]
I'll fix it.

**Comment by taiyang-li** [comment]
```
 :) select toInt32OrNull('1.8')

SELECT toInt32OrNull('1.8')

Query id: 55745f90-d065-4122-9b5b-c6596104089a

┌─toInt32OrNull('1.8')─┐
│                 ᴺᵁᴸᴸ │
└──────────────────────┘

1 row in set. Elapsed: 0.002 sec. 
```

**Comment by taiyang-li** [comment]
maybe fixed by https://github.com/ClickHouse/ClickHouse/pull/54530
