### ISSUE TITLE
[CH] Function Row_Number result is not same compare to spark

### ISSUE THREAD

**Issue by KevinyhZou** [oap-project/gluten#3118]
### Backend

CH (ClickHouse)

### Bug description

we have a table, and the data of it as below
+-------+---------------------------------+--------+
|  id   |              name               |  sex   |
+-------+---------------------------------+--------+
| 0     | {"extra_info": "{\"c\": [2]}"}  | n      |
| 29    | {"extra_info": "{\"c\": [2]}"}  | n      |
| 15    | {"123":{"a":"b"}, "a":[5,4]}    | x      |
| 14    | {"123":[3,4,5], "a":[5,4]}      | x      |
| 6     | {"a":[1,2],"b":{"a":"c"}}       | n      |
| 13    | {"123":"abde", "a":[3,4]}       | x      |
| 21    | 0.00002846384813892655          | n      |
| 5     | {"a":"ab1", "b":"bc1"}          | n      |
| 28    | {\"a\":{\"b\":\"c\"}}           | n      |
| 7     | {"b":{"a":{"c":"d"}}}           | n      |
| 3     | {"a":"ab", "b":"bc"}            | n      |
| 28    | {"a":{\"b\":\"c\"}}             | n      |
| 28    | {"a":{\"b\":\"c\"}}             | n      |
| 12    | 2023-01-02 11:22                | UTC    |
| 21    | {"a":{"b":"c"}}                 | n      |
| 11    | 2023-01-02 11                   | UTC    |
| 25    | {"a":{"b":"c"}}                 | n      |
| 28    | {"a":{"b":"c"}}                 | n      |
| 9     | 2023-01-12                      | GMT+1  |
| 8     | 2023-01-12                      | UTC    |
| 10    | 2023-01                         | UTC    |
| 10    | 2023                            | UTC    |
| 21    | 1.8                             | n      |
| 1     | ab                              | m      |
| 2     | bc                              | m      |
| NULL  | bc                              | m      |
+-------+---------------------------------+--------+

while do the query `select id, row_number() OVER(ORDER BY sex DESC ) AS rn from test_tbl3`, the result of gluten is 
![image](https://github.com/oap-project/gluten/assets/37431499/9f8487fd-d3a4-4812-9d1f-23181daff950)

and the result of spark is 
![image](https://github.com/oap-project/gluten/assets/37431499/c9ab6ad4-95b9-41e3-a85c-00648ff3d03c)

the result is not same, such as the id 12's row number is 25, bu in spark is 21

### Spark version

Spark-3.3.x

**Comment by taiyang-li** [comment]
spark涉及到多个节点的排序和ch一样，也是不稳定的。可以暂时忽略
