### ISSUE TITLE
[CH]  lateral view result is different from spark while the array is null

### ISSUE THREAD

**Issue by KevinyhZou** [oap-project/gluten#3124]
### Backend

CH (ClickHouse)

### Bug description

We have a table,  and the schema is `id bigint, name string, sex string` with some element is null, as below
![image](https://github.com/oap-project/gluten/assets/37431499/5b3db486-b448-4b8e-9fd8-9a9ebb51b944)

and we do the query base on the null element with id = 31, the sql is `select id,name_flag from test_tbl3 lateral view explode(split(name, ',')) as name_flag where id = 31;`

and we get different result of gluten compare to spark, use gluten, the result is
![image](https://github.com/oap-project/gluten/assets/37431499/ce7d52c6-c71b-42e0-9205-4b3b0e80cd5e)

use spark the result is  empty
![image](https://github.com/oap-project/gluten/assets/37431499/1034d7dc-1704-4054-844a-874b513c6a8d)

### Spark version

Spark-3.3.x

**Comment by taiyang-li** [comment]
I'll fix it.
