### ISSUE TITLE
[CH] posexplode index start from 1

### ISSUE THREAD

**Issue by shuai-xu** [oap-project/gluten#3127]
### Backend

CH (ClickHouse)

### Bug description

When run sql `select uid, n from xxxx
       lateral view posexplode(split(substr(event.event_info['tags'], 3, length(event.event_info['tags'])-4), '\\},\\{')) tags as n, tag`, the n return 1 and 12, but vanila spark return 0 and 11.

### Spark version

Spark-3.3.x

**Comment by taiyang-li** [comment]
it is fixed https://github.com/oap-project/gluten/pull/3106

**Comment by baibaichen** [comment]
duplicated with https://github.com/oap-project/gluten/issues/2492
