### ISSUE TITLE
[backend-Velox] Use tpch_datagen_parquet.sh to generate parquet data for tpch failed. 

### ISSUE THREAD

**Issue by zengruios** [oap-project/gluten#315]
**Describe the bug**
use tpch_datagen_parquet.sh to generate parquet data for tpch failed. 
tpch_datagen_parquet.scala code:
![image](https://user-images.githubusercontent.com/26316365/184611517-df788580-126d-43c9-994a-b95e64ecb5cc.png)
tpch_datagen_parquet.sh code:
![image](https://user-images.githubusercontent.com/26316365/184611150-80ade835-1d91-428f-9556-9fe7ee7db15e.png)
The parquet files generated in the directory `/mnt/disk2/tpc-h/datagen/parquet`:
![image](https://user-images.githubusercontent.com/26316365/184611867-9585d222-63bd-4a75-93a8-5b2c588dfa04.png)
Parquet files do not contain tpch data. Data in the parquet file like below:
![image](https://user-images.githubusercontent.com/26316365/184612139-2eedaa06-7454-4d2b-8274-bb6efbbcb5e4.png)

**To Reproduce**

**Expected behavior**

**Additional context**

**Comment by zengruios** [comment]
Tpch dbgen generate tbl files under `/mnt/disk2/TPC_H_Tools_v3.0.0/dbgen` successfully.
![image](https://user-images.githubusercontent.com/26316365/184612807-ac5cb7e1-94ea-4a85-8c30-6abe37635e1b.png)

**Comment by zengruios** [comment]
Maybe I use a wrong tpch tool. Which tpch tool gluten use?

**Comment by FelixYBW** [comment]
we use this one: https://github.com/databricks/tpch-dbgen/commits/master
