### ISSUE TITLE
[CH] Support decode function

### ISSUE THREAD

**Issue by zhanglistar** [oap-project/gluten#3190]
### Description

d_9798_0.sql

(7) Project: Not supported: stringdecode(unhex(hex(cast((cast((cast((cast(other_unfixed_para#445[401] as bigint) & 992) as double) / 32.0) as int) + 65) as bigint))), US-ASCII). class org.apache.spark.sql.catalyst.expressions.StringDecode
(13) Project: Not supported: stringdecode(unhex(hex(cast((cast((cast((cast(other_unfixed_para#458[401] as bigint) & 992) as double) / 32.0) as int) + 65) as bigint))), US-ASCII). class org.apache.spark.sql.catalyst.expressions.StringDecode

**Comment by taiyang-li** [comment]
let's do it!
