### ISSUE TITLE
[VL] Too many logs print to stdout

### ISSUE THREAD

**Issue by Yohahaha** [oap-project/gluten#3208]
### Backend

VL (Velox)

### Bug description

After PR #2982 , this line will print TOO MANY logs to stdout https://github.com/oap-project/gluten/blob/7d9763c31d1eeca5bc03e579a7824de41dee2d93/cpp/velox/shuffle/VeloxShuffleWriter.cc#L1100C13-L1100C13

If revert #2982  whole output clear, is any logic be triggered in this branch?

![image](https://github.com/oap-project/gluten/assets/34979747/6f53a12b-a6be-447a-860f-8969498705bb)

### Spark version

Spark-3.3.x

**Comment by Yohahaha** [comment]
@marin-ma

**Comment by marin-ma** [comment]
Changed to debug log here https://github.com/oap-project/gluten/pull/3199/files#diff-55954c774f5d66d0d359c3c7baa29be65f75198b30fd27603b0456ccd11b6a79R1104

**Comment by Yohahaha** [comment]
> Changed to debug log here https://github.com/oap-project/gluten/pull/3199/files#diff-55954c774f5d66d0d359c3c7baa29be65f75198b30fd27603b0456ccd11b6a79R1104

Thanks, could we apply a hotfix? Does #3199 will fix the number of this log? or just replace with DLOG?
