### ISSUE TITLE
build clickhouse报错

### ISSUE THREAD

**Issue by le229** [oap-project/gluten#3242]
### Problem description

[Directly Compile ClickHouse backend](https://github.com/oap-project/gluten/blob/main/docs/get-started/ClickHouse.md#directly-compile-clickhouse-backend)按照这个步骤编译clickhouse
![image](https://github.com/oap-project/gluten/assets/38638397/e9617916-75bf-49b6-b625-f53d733fa6f2)

### System information

CentOS Linux release 7.8.2003

**Comment by zhanglistar** [comment]
What's the result of under directory cpp-ch and execute command `bash -x ../ep/build-clickhouse/src/build_clickhouse.sh`?
