### ISSUE TITLE
[VL] batch holder in executorCtx is not thread safe but batch access from two threads

### ISSUE THREAD

**Issue by FelixYBW** [oap-project/gluten#3328]
### Backend

VL (Velox)

### Bug description

two issues:

- Batch add and batch clear are from different threads which cause segfault
- batch is closed twice from write and close. It doesn't lead to any bug, but an inefficient way

### Spark version

Spark-3.2.x

**Comment by FelixYBW** [comment]
Currently I use a mutex to  guard the map insert/lookup/erase. Needs to see if we can remove the mutex.

**Comment by Yohahaha** [comment]
Curious which case trigger this issue? seems ExecutionCtx be used in multi Spark Task?

**Comment by zhztheplayer** [comment]
I assume the new thread was started in VeloxWriteQueue when it's instantiated, then the thread could close input batches when they were no longer used? @JkSelf please confirm, thanks

**Comment by FelixYBW** [comment]
Yes. I think we should have some UT to make sure the add and erase to be called in the same task thread always

**Comment by JkSelf** [comment]
Filed https://github.com/oap-project/gluten/pull/3332 to fix this issue.
