### ISSUE TITLE
Support Spark 3.4 in Gluten.

### ISSUE THREAD

**Issue by JkSelf** [oap-project/gluten#3361]
### Description

Spark 3.4 has been [released](https://spark.apache.org/releases/spark-release-3-4-0.html). We plan to upgrade the spark version to 3.4 in Gluten.

**Comment by kelvin-qin** [comment]
Spark 3.5.0 released, Sep 13, 2023

**Comment by zhouyuan** [comment]
> Spark 3.5.0 released, Sep 13, 2023

@kelvin-qin Yes, noted the new 3.5 release and Gluten will support this as next. Per my understanding, customers usually will wait for 1-2 minor releases, e.g, using Spark 3.5.1/3.5.2, so it may makes more sense to support newer one in 3.5.x. 

thanks, -yuan

**Comment by kelvin-qin** [comment]
Yes. We use 3.3.2.

**Comment by zhouyuan** [comment]
close by https://github.com/oap-project/gluten/pull/3360
