### ISSUE TITLE
build project success but not found libprotobuf

### ISSUE THREAD

**Issue by LoseYSelf** [oap-project/gluten#3389]
### Problem description

In Ubuntu20 system version,run ./dev/buildbundle-veloxbe.sh and build success.
spark-sql command is:
bin/spark-sql --master local[8] --conf spark.driver.extraClassPath=/data/apps/spark-3.3.2-bin-hadoop2/gluten-velox-bundle-spark3.3_2.12-ubuntu_20.04-1.0.0.jar --conf spark.plugins=io.glutenproject.GlutenPlugin --conf spark.memory.offHeap.enabled=true --conf spark.gluten.sql.columnar.filescan=false  --conf spark.memory.offHeap.size=20g --conf spark.shuffle.manager=org.apache.spark.shuffle.sort.ColumnarShuffleManager -f xx.sql
and error is :
Exception in thread "main" java.lang.UnsatisfiedLinkError: /data/spark_tmp/gluten-8ff5488b-6346-4d8b-a5c1-217e0903d9f2/jni/bf82b94b-ed52-4890-9254-a4c85dabac4d/gluten-2230286230297993280/libarrow.so.1200.0.0: libprotobuf.so.32: cannot open shared object file: No such file or directory

Note: gluten branch is 1.0.0.
May be the build script is not complete?

### System information

1

### CMake log

```bash
1
```

**Comment by LoseYSelf** [comment]
fix: it must use --enable_vcpkg=ON

**Comment by hailiang9615** [comment]
Where does this need to be added? Is this './dev/buildbundle-veloxbe.sh' behind?

**Comment by hailiang9615** [comment]
> fix: it must use --enable_vcpkg=ON

Where does this need to be added? Is this './dev/buildbundle-veloxbe.sh' behind?

**Comment by LoseYSelf** [comment]
> > fix: it must use --enable_vcpkg=ON
> 
> Where does this need to be added? Is this './dev/buildbundle-veloxbe.sh' behind?

./dev/buildbundle-veloxbe.sh --enable_vcpkg=ON

**Comment by wanweiqiangintel** [comment]
when I enable vcpkg, i got this error:
-- Building x64-linux-avx-dbg
CMake Error at scripts/cmake/vcpkg_execute_build_process.cmake:134 (message):
    Command failed: /home/ww/gluten/dev/vcpkg/.vcpkg/downloads/tools/cmake-3.25.1-linux/cmake-3.25.1-linux-x86_64/bin/cmake --build . --config Debug --target install -- -v -j225
    Working Directory: /home/ww/gluten/dev/vcpkg/.vcpkg/buildtrees/folly/x64-linux-avx-dbg
    See logs for more information:
      /home/ww/gluten/dev/vcpkg/.vcpkg/buildtrees/folly/install-x64-linux-avx-dbg-out.log

Call Stack (most recent call first):
  /home/ww/gluten/dev/vcpkg/vcpkg_installed/x64-linux-avx/share/vcpkg-cmake/vcpkg_cmake_build.cmake:74 (vcpkg_execute_build_process)
  /home/ww/gluten/dev/vcpkg/vcpkg_installed/x64-linux-avx/share/vcpkg-cmake/vcpkg_cmake_install.cmake:16 (vcpkg_cmake_build)
  /home/ww/gluten/dev/vcpkg/ports/folly/portfile.cmake:73 (vcpkg_cmake_install)
  scripts/ports.cmake:147 (include)


error: building folly:x64-linux-avx failed with: BUILD_FAILED
Please ensure you're using the latest port files with `git pull` and `vcpkg update`.
Then check for known issues at:
    https://github.com/microsoft/vcpkg/issues?q=is%3Aissue+is%3Aopen+in%3Atitle+folly
You can submit a new issue at:
    https://github.com/microsoft/vcpkg/issues/new?title=[folly]+Build+error&body=Copy+issue+body+from+%2Fhome%2Fww%2Fgluten%2Fdev%2Fvcpkg%2Fvcpkg_installed%2Fvcpkg%2Fissue_body.md
<img width="706" alt="image" src="https://github.com/oap-project/gluten/assets/89506884/672ddda2-8a84-4c14-b52e-7a253a2875a9">
