### ISSUE TITLE
Spark Plan error when running TPC-DS Q75

### ISSUE THREAD

**Issue by kelvin-qin** [oap-project/gluten#3390]
### Backend

VL (Velox)

### Bug description

When running TPC-DS, q75 fails with an error report.

### Spark version

Spark-3.3.x

### Spark configurations

./bin/spark-sql  --master yarn --deploy-mode client  --conf spark.sql.shuffle.partitions=270  --conf spark.plugins=io.glutenproject.GlutenPlugin --conf spark.gluten.sql.columnar.backend.lib=velox  --conf spark.gluten.loadLibFromJar=true  --conf spark.shuffle.manager=org.apache.spark.shuffle.sort.ColumnarShuffleManager  --conf spark.driver.extraClassPath=/opt/pathto/gluten-velox-bundle-spark3.3_2.12-centos_8.jar  --conf spark.executor.extraClassPath=./gluten-velox-bundle-spark3.3_2.12-centos_8.jar   --conf spark.memory.offHeap.enabled=true  --conf spark.scheduler.mode=FIFO   --conf spark.sql.adaptive.enabled=true  --conf spark.memory.offHeap.size=40g --num-executors 15 --executor-memory 8g  --executor-cores 6 --jars /opt/pathto/gluten-velox-bundle-spark3.3_2.12-centos_8.jar  --driver-memory 20g --conf spark.gluten.sql.columnar.coreRange="0-27,56-83|28-55,84-111" --conf spark.gluten.sql.columnar.numaBinding=true --conf spark.sql.optimizer.dynamicPartitionPruning.enabled=true

### System information

CentOS 8
Gluten1.0
JDK 1.8.0_345

### Relevant logs

```bash
Error AdaptiveSparkPlanExec ……

Caused by: java.lang.IllegalStateException: Key d_date_sk#28632 not found from build side relation output: List(d_date_sk#28532,d_year#28538)
```

**Comment by kelvin-qin** [comment]
Vanilla Spark is ok.

**Comment by Yohahaha** [comment]
cc @liujiayi771 @zhouyuan

**Comment by liujiayi771** [comment]
@kelvin-qin Can you try the latest code? This problem was fixed in the https://github.com/oap-project/gluten/pull/2337 on July 17. Gluten 1.0 was released on July 14 and did not introduce this modification.

**Comment by zhouyuan** [comment]
close this as it's fixed in new code. feel free to reopen if the issue still exists.

-yuan
