### ISSUE TITLE
[VL] Support `BroadcastNestedLoopJoinExec` and `CartesianProductExec`

### ISSUE THREAD

**Issue by zhouyuan** [oap-project/gluten#3432]
### Description

These two join operators can be mapped to [NestedLoopJoin](https://github.com/facebookincubator/velox/blob/6742acdd90bfb5e2efcbe3554a0c67e3b6cd137e/velox/core/PlanNode.cpp#L978)  in Velox

**Comment by SurbhiVijayvargeeya** [comment]
I would like to work on it. Please let me know if I can go ahead since I was already looking into it before the issue was created.

**Comment by zhouyuan** [comment]
@SurbhiVijayvargeeya cool! I just started working with some basic C++ code with the NestedLoopJoin in Velox and as far as I know there's no other people working on this. Could you please send a draft design/doc on this first, if it's convenient for you? 

thanks, -yuan

**Comment by SurbhiVijayvargeeya** [comment]
Please allow me sometime. I will try to share a draft in this week.

**Comment by SurbhiVijayvargeeya** [comment]
This the initial [draft doc](https://1drv.ms/w/s!Ajw-L7_tFgRyjW-CBZ0gWLjq3hzF) based on my current understanding. I have started working on code changes and will add more details into it as I get more clarity.

**Comment by zhouyuan** [comment]
> This the initial [draft doc](https://1drv.ms/w/s!Ajw-L7_tFgRyjW-CBZ0gWLjq3hzF) based on my current understanding. I have started working on code changes and will add more details into it as I get more clarity.

@SurbhiVijayvargeeya thanks for this write up. Overall it looks good. One possible missing piece is on how to handle `IdentityBroadcastMode` broadcast xchg for BNLJ, as the current impl doesnt support this
https://github.com/oap-project/gluten/blob/a7b68c3dc0c88d117e2b6c1fdaaf8f5dd011da8c/gluten-core/src/main/scala/org/apache/spark/sql/execution/ColumnarBroadcastExchangeExec.scala#L138

The related code on broadcast small table is here:
https://github.com/oap-project/gluten/blob/main/backends-velox/src/main/scala/io/glutenproject/backendsapi/velox/SparkPlanExecApiImpl.scala#L274C40-L274C40

thanks, -yuan

**Comment by Surbhi-Vijay** [comment]
Thanks @zhouyuan for pointing out. Yes, I also had a look at it. I am planning to first work on supporting BroadcastNestedLoopJoinExec to cover all these cases and then CartesianProductExec.
