### ISSUE TITLE
[CH] Cast float-type string to float lost precision

### ISSUE THREAD

**Issue by KevinyhZou** [oap-project/gluten#3446]
### Backend

CH (ClickHouse)

### Bug description

we have a float-type string value, and cast it to float, which lost precision
![image](https://github.com/oap-project/gluten/assets/37431499/e3a875b7-34fd-4890-ac99-66c7a3f00a20)

the result should be `7.921901` not `7.92190007`

### Spark version

Spark-3.3.x

**Comment by taiyang-li** [comment]
I'll fix it.
