### ISSUE TITLE
[CH] AQE cannot coalesce partitions when Exchange hash partitioning exists non-attribute expressions

### ISSUE THREAD

**Issue by exmy** [oap-project/gluten#3486]
### Backend

CH (ClickHouse)

### Bug description

![image](https://github.com/oap-project/gluten/assets/18643308/bec62ce1-91db-42fa-bcec-b1c65be412f7)

A pre-project operator is added before the exchange operator when hash partitioning involves non-attribute expressions, which results in that AQE cannot coalesce shuffle partitions.

### Spark version

None

**Comment by lgbo-ustc** [comment]
@rui-mo mo @zzcclp Should we extend the substait pb to support expression in exchange operator?

**Comment by rui-mo** [comment]
@exmy Thanks for noticing this issue. Could you explain a bit how large this issue will affect the performance?

**Comment by rui-mo** [comment]
cc @PHILO-HE

**Comment by exmy** [comment]
> @exmy Thanks for noticing this issue. Could you explain a bit how large this issue will affect the performance?

We've recently noticed that this issue will also prevent AQE's OptimizeSkewedJoin rule from being effective, and it has a significant impact on performance.

If OptimizeSkewedJoin disabled due to this issue:
![image](https://github.com/oap-project/gluten/assets/18643308/7af89721-2be2-4013-82b8-7ef14008a6e7)
![image](https://github.com/oap-project/gluten/assets/18643308/b6dc4796-740f-4010-9fb1-58974f1a04b5)


If OptimizeSkewedJoin enabled:
![image](https://github.com/oap-project/gluten/assets/18643308/0b75a8ce-efec-4400-adfe-b0fad4b677e2)
![image](https://github.com/oap-project/gluten/assets/18643308/43f92bee-27b4-4de1-afc5-47f2d6b69c5b)


@rui-mo

**Comment by rui-mo** [comment]
@exmy Thanks for the profiling. On which query can we reproduce the performance result? Does that mean we shouldn't add extra project before exchange?

**Comment by exmy** [comment]
> @exmy Thanks for the profiling. On which query can we reproduce the performance result? Does that mean we shouldn't add extra project before exchange?

Sorry, this issue is specific to the CH backend. It's not present in the Velox backend.

**Comment by rui-mo** [comment]
> Sorry, this issue is specific to the CH backend. It's not present in the Velox backend.

@exmy Thanks for your work. Velox backend also inserts a Project transformer before exchange if the hash keys are expressions. I assume similar issue also occurs for Velox backend, right?

**Comment by exmy** [comment]
> @exmy Thanks for your work. Velox backend also inserts a Project transformer before exchange if the hash keys are expressions. I assume similar issue also occurs for Velox backend, right? cc @PHILO-HE

Velox backend doesn't has this issue. Because it adds pre-project to calculate hash value but doesn't change shuffle hash expressions in ShuffleExchange operator. I have tested it. @rui-mo

**Comment by rui-mo** [comment]
@exmy Thanks for checking!
