### ISSUE TITLE
[backend-Velox] Use tpch_convert_parquet_dwrf.sh to convert parquet but cause exception 'double free or corruption (!prev)'

### ISSUE THREAD

**Issue by KevinyhZou** [oap-project/gluten#349]
**Describe the bug**
generate the parquet table file by use tpch-dbgen: https://github.com/databricks/tpch-dbgen

then convert the parquet file to dwrf format by use the tpch_convert_parquet_dwrf.sh script, and submit the spark job to yarn, the job fail and the error log as below
![gluten_bug_1](https://user-images.githubusercontent.com/37431499/187916591-423f3a4d-a20c-498a-9415-c5089d085c1d.png)

it seems the jni call make the exception

**To Reproduce**
re-run  tpch_convert_parquet_dwrf.sh script

**Expected behavior**
convert parquet to dwrf without error

**Additional context**

**Comment by FelixYBW** [comment]
parquet is supported now. You may try parquet file directly.

**Comment by KevinyhZou** [comment]
> parquet is supported now. You may try parquet file directly.

OK
