### ISSUE TITLE
[CH] to_json function result is diffrent from spark when the input is `struct` type

### ISSUE THREAD

**Issue by KevinyhZou** [oap-project/gluten#3501]
### Backend

CH (ClickHouse)

### Bug description

to_json function result is different from spark when the input is struct type, when query such by gluten `select to_json(struct(name)) from test_tbl1`, the result is 
![image](https://github.com/oap-project/gluten/assets/37431499/a9bd5f05-c054-4ed3-8f29-15d16b782638)

when query by spark, the result is
![image](https://github.com/oap-project/gluten/assets/37431499/90f53d28-5c7f-4a5c-ac6f-e702e0c29e13)

### Spark version

Spark-3.3.x

**Comment by taiyang-li** [comment]
Maybe fixed by https://github.com/ClickHouse/ClickHouse/pull/55956
