### ISSUE TITLE
[VL] Add native read support from ABFS storage

### ISSUE THREAD

**Issue by gaoyangxiaozhu** [oap-project/gluten#3580]
### Description

the abfs read support change has been ready in meta velox and also been synced by OAP/velox update branch, we can do chagne now in gluten to make the abfs read end to end work in OSS gluten repository.

I will take the job.

**Comment by gaoyangxiaozhu** [comment]
@zhli1142015 and @zhouyuan

**Comment by zhouyuan** [comment]
@gaoyangxiaozhu @zhli1142015 thanks for the help, do you happen to have some ideas on how to validate this via tests? We currently have some S3(minio) related jobs running locally to verify the S3 adaptor. 

-yuan

**Comment by gaoyangxiaozhu** [comment]
> @gaoyangxiaozhu @zhli1142015 thanks for the help, do you happen to have some ideas on how to validate this via tests? We currently have some S3(minio) related jobs running locally to verify the S3 adaptor.
> 
> -yuan

for read part we can leverage azurite simulator https://learn.microsoft.com/en-us/azure/storage/common/storage-use-azurite?tabs=visual-studio

**Comment by gaoyangxiaozhu** [comment]
@zhouyuan how about make sperate PR for adding test with azurite, or you want me cover ut in this PR also ?

**Comment by zhouyuan** [comment]
> @zhouyuan how about make sperate PR for adding test with azurite, or you want me cover ut in this PR also ?

@gaoyangxiaozhu Hi, make senesce to me. 

thanks, -yuan
