### ISSUE TITLE
[VL] Allow users to set bloom filter configurations

### ISSUE THREAD

**Issue by zhouyuan** [oap-project/gluten#3594]
### Description

Gluten should allow users to config these bloom filter params, as it may impact the performance.

https://github.com/facebookincubator/velox/blob/73d4279a14744cf4d038d3a967a49dcddbad9d39/velox/core/QueryConfig.h#L629

**Comment by zhli1142015** [comment]
If no one would like to pick up this, I would like to work on this, as now the default value of MaxNumBits is too small comparing to spark default value, we saw about 20s difference in our TPCDS run.
