### ISSUE TITLE
Build Gluten velox thrid party failed with S3 on Centos8

### ISSUE THREAD

**Issue by dcoliversun** [oap-project/gluten#3602]
### Problem description

When exec `./get_velox.sh --enable_s3=on & ./build_velox.sh`,  we have a error with command not found
```plain
-- Installing: /usr/local/lib64/pkgconfig/fmt.pc
+ install_awssdk
scripts/setup-centos8.sh: line 118: install_awssdk: command not found
Error: Process completed with exit code 127.
```

### System information

```plain
Velox System Info v0.0.2
Commit: 30663fb45a74fd35e1190b439a0d31865374ddd9
CMake Version: 3.20.2
System: Linux-3.10.0-693.2.2.el7.x86_64
Arch: x86_64
C++ Compiler: /opt/rh/gcc-toolset-9/root/usr/bin/c++
C++ Compiler Version: 9.2.1
C Compiler: /opt/rh/gcc-toolset-9/root/usr/bin/cc
C Compiler Version: 9.2.1
CMake Prefix Path: /usr/local;/usr;/;/usr;/usr/local;/usr/X11R6;/usr/pkg;/opt
```

**Comment by dcoliversun** [comment]
more info: https://github.com/oap-project/gluten/actions/runs/6731284448/job/18296787976

**Comment by zhouyuan** [comment]
@dcoliversun yes, this is missed after Velox rebase. In previous velox branch, we did installed aws sdk. we need to align below script 

old: https://github.com/oap-project/velox/blob/main/scripts/setup-centos8.sh
new: https://github.com/oap-project/velox/blob/update/scripts/setup-centos8.sh 

can you please help to make a patch to fix this issue?

-yuan

**Comment by dcoliversun** [comment]
@zhouyuan Sure, I will patch to oap-project/velox
