### ISSUE TITLE
[VL] Clean up arrow related doc

### ISSUE THREAD

**Issue by zhouyuan** [oap-project/gluten#3635]
### Description

gluten currently relies on the arrow in velox. the scripts related with arrow are not available 
https://github.com/oap-project/gluten/blob/main/docs/get-started/Velox.md#build-gluten-with-velox-backend

**Comment by PHILO-HE** [comment]
It may be covered by https://github.com/oap-project/gluten/pull/3573.

**Comment by ted-jenks** [comment]
This issue should be reopened to address the last couple places arrow stuff is mentioned in the docs: https://github.com/oap-project/gluten/pull/3709
