### ISSUE TITLE
[VL] Error building Gluten with QAT with in-tree kernel QAT driver

### ISSUE THREAD

**Issue by hanblee** [oap-project/gluten#3643]
### Problem description

I am running custom kernel 6.4.0 with in-tree kernel QAT driver, and I am trying to build Gluten with QAT enabled using the following command:
`dev/buildbundle-veloxbe.sh --enable_hdfs=ON --enable_qat=ON`

but I get the following error:
`CMake Error at CMake/BuildQATzip.cmake:85 (find_library):
  Could not find USDM_DRV_LIBRARY using the following names: usdm_drv_s`

What steps should I be taking to make in-tree kernel QAT driver to work with Gluten? It looks like [Build Gluten with QAT](https://github.com/oap-project/gluten/blob/main/docs/get-started/Velox.md#build-gluten-with-qat) instructions are tailored for out-of-tree QAT driver usage.

### System information

Velox System Info v0.0.2
Commit: e3eff1d8f5e8230c3872ce5f7d1b31c02eb0dcbe
CMake Version: 3.20.2
System: Linux-6.4.0-2023-07-06-intel-nextqat-gbbd5a7d96ead
Arch: x86_64
C++ Compiler: /opt/rh/gcc-toolset-9/root/usr/bin/c++
C++ Compiler Version: 9.2.1
C Compiler: /opt/rh/gcc-toolset-9/root/usr/bin/cc
C Compiler Version: 9.2.1
CMake Prefix Path: /usr/local;/usr;/;/usr;/usr/local;/usr/X11R6;/usr/pkg;/opt

**Comment by marin-ma** [comment]
@hanblee Can we close this one?

**Comment by marin-ma** [comment]
By checking this thread https://community.intel.com/t5/Intel-QuickAssist-Technology/RHEL-8-8-KVM-guest-hangs-when-running-QAT-qzip/m-p/1538277/highlight/true#M166 , looks like the in-tree kernel driver doesn't use the usdm_drv module.
> For (2), make sure the in-tree driver is uninstall first, and then install the out-of-tree driver which is available here: https://www.intel.com/content/www/us/en/download/765501/intel-quickassist-technology-driver-for-linux-hw-version-2-0.html

And the suggestion is to uninstall the in-tree driver then install the out-of-tree driver.
