### ISSUE TITLE
[VL] Integrate upstream DirectBufferedInput with executor

### ISSUE THREAD

**Issue by Yohahaha** [oap-project/gluten#3666]
### Description

Upstream velox add DirectBufferedInput to replace BufferedInput, and use a optional executor do async load or prefetch, but its executor was passed from HiveConnector which means this executor is global instance, I'm not sure Gluten's thread mode or memory mode could fit it, will keep tracking.

**Comment by Yohahaha** [comment]
DirectBufferedInput has less performance boost, my benchmark result in TPCH sf30 cloud storage is 160s(without executor) vs 152s(with executor).

**Comment by FelixYBW** [comment]
@zhli1142015 Did you noted the perf regression?

**Comment by zhli1142015** [comment]
yes, we noticed the regression also 10% totally for our TPCDS runs.

**Comment by FelixYBW** [comment]
should we fallback to bufferInput?

directBufferedInput reads page by page, BufferInput reads row group by row group. 
rowgroup read ahead looks not work with direct buffer input.

**Comment by zhli1142015** [comment]
I thought @Yohahaha opened an issue for this: https://github.com/facebookincubator/velox/issues/7535.

**Comment by Yohahaha** [comment]
@FelixYBW have you try compare the perf between DBI and BI?

**Comment by FelixYBW** [comment]
Yes, The issue I faced now is row group read ahead doesn't work with DBI. without the read ahead perf is worse

**Comment by Yohahaha** [comment]
> Yes, The issue I faced now is row group read ahead doesn't work with DBI. without the read ahead perf is worse

thanks, I will reopen above issue to solve it.

we could use BI default in oap-velox for now. @zhouyuan

**Comment by FelixYBW** [comment]
Just tested a IO bound query, DBI 4.6 min, BI 1.6 min
