### ISSUE TITLE
[VL] Cannot turn off the shuffle compression with --conf spark.shuffle.compress=false

### ISSUE THREAD

**Issue by weiting-chen** [oap-project/gluten#3684]
### Backend

VL (Velox)

### Bug description

[Expect Behavior]
With --conf spark.shuffle.compress=false setting, Gluten's shuffle manager should turn off the compression support, but we have monitor the lz4 library still be called out in the background.
![shuffle compress issue](https://github.com/oap-project/gluten/assets/9245981/8c39fe97-6dd9-4841-a243-693289681388)

### Spark version

None

**Comment by zhouyuan** [comment]
fixed by https://github.com/oap-project/gluten/pull/3672
