### ISSUE TITLE
[VL] libre2.so.5: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by guyuqi** [oap-project/gluten#3695]
### Backend
VL (Velox)

### Bug description

When I run TPC-DS with the Velox backend on **Arm64 Ubuntu-22.04**, Spark submit error occurs.
```
To adjust logging level use sc.setLogLevel(newLevel). For SparkR, use setLogLevel(newLevel).
java.lang.UnsatisfiedLinkError: /opt/spark-3.3.3-bin-3.3.6/spark-tmp/gluten-ed15a8a5-6c40-4416-aad9-4a6d9b2602de/jni/37c97939-9090-4bb2-a8d9-68166279cdcd/gluten-6880146105144534931/libarrow.so.1200.0.0: libre2.so.5: cannot open shared object file: No such file or directory
  at java.lang.ClassLoader$NativeLibrary.load(Native Method)
  at java.lang.ClassLoader.loadLibrary0(ClassLoader.java:1934)
  at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1817)
```

I found the solution in: [here](https://github.com/oap-project/gluten/issues/2094#issuecomment-1609060353)
`--conf spark.gluten.loadLibFromJar=true`

`gluten-thirdparty-lib-ubuntu-22.04.jar` was pre-built on x86_64:
```
gluten-9036994617175429867/libboost_context.so.1.74.0: cannot open shared object file: No such file or directory (Possible cause: can't load AMD 64-bit .so on a AARCH64-bit platform)
  at java.lang.ClassLoader$NativeLibrary.load(Native Method)
```

**May I ask how to build** `gluten-thirdparty-lib-ubuntu-22.04.jar` **from source on my own**?

### Spark version

Spark-3.3.x

### Spark configurations

spark.driver.extraClassPath        /home/hadoop/spark-gluten-velox/gluten-jar/*
spark.executor.extraClassPath      /home/hadoop/spark-gluten-velox/gluten-jar/*

### System information

OS: Ubuntu-22.04
ARCH: Arm64

**Comment by PHILO-HE** [comment]
The below link may be helpful to you:
https://github.com/oap-project/gluten/blob/main/shims/common/src/main/scala/io/glutenproject/GlutenConfig.scala#L377-L380

**Comment by guyuqi** [comment]
@PHILO-HE , @zhouyuan 

Thanks for your help. That's informative. I could sccessfully build `gluten-thirdparty-lib-ubuntu-22.04.jar`by myself. 

TPC-DS Table of parquet files also have been generated in HDFS by [tpcds_datagen_parquet.sh](https://github.com/oap-project/gluten/blob/main/backends-velox/workload/tpcds/gen_data/parquet_dataset/tpcds_datagen_parquet.sh) .

But, when I re-run the tpcds :
```
cat tpcds_parquet.scala | ${SPARK_HOME}/bin/spark-shell \
  --master yarn --deploy-mode client \
  --conf spark.plugins=io.glutenproject.GlutenPlugin \
  --conf spark.memory.offHeap.enabled=true \
  --conf spark.memory.offHeap.size=2g \
  --conf spark.gluten.sql.columnar.forceShuffledHashJoin=true \
  --conf spark.shuffle.manager=org.apache.spark.shuffle.sort.ColumnarShuffleManager \
  --num-executors 3 \
  --executor-cores 3 \
  --driver-memory 2g \
  --executor-memory 2g \
  --conf spark.executor.memoryOverhead=2g \
  --conf spark.driver.maxResultSize=2g \
  --conf spark.gluten.loadLibFromJar=true \
  --jars /home/hadoop/spark-gluten-velox/gluten-jar/gluten-velox-bundle-spark3.3_2.12-ubuntu_22.04-1.1.0-SNAPSHOT.jar,/home/hadoop/spark-gluten-velox/gluten-jar/gluten-thirdparty-lib-ubuntu-22.04.jar

```


Some issues occurred when reading TPC-DS Table from parquet file from HDFS ([tpcds_parquet.scala](https://github.com/oap-project/gluten/blob/main/backends-velox/workload/tpcds/run_tpcds/tpcds_parquet.scala)):
```
scala> val call_center = spark.read.format("parquet").load("hdfs://" + parquet_file_path + "/call_center")
...
java.lang.NoSuchMethodError: org.apache.spark.sql.execution.datasources.parquet.ParquetToSparkSchemaConverter.<init>(ZZZ)V
...

```
**java.lang.NoSuchMethodError: ParquetToSparkSchemaConverter**

Spark version: 3.3.3

I'm new to Project Gluten.
May I ask if Spark-3.3.3 supports gluten in tpc-ds or not? 

Thanks.

**Comment by zhouyuan** [comment]
Hi @guyuqi Spark3.3.3 is not tested AFAIK - it may require some small patches as there are some internal API changes. Currents all the codes/tests are based on Spark 3.3.1. We are aware of the issue but didn't have resource to fix it.
https://archive.apache.org/dist/spark/spark-3.3.1/
Would you please start with Spark 3.3.1 first? 

thanks, -yuan

**Comment by zhouyuan** [comment]
@guyuqi I'll close this issue as it's already fixed with your new package. Feel free to reopen if there are further issues. 

thanks, -yuan
