### ISSUE TITLE
[VL] Add config to disable velox file handle cache

### ISSUE THREAD

**Issue by zhli1142015** [oap-project/gluten#3739]
### Description

For details, please see https://github.com/facebookincubator/velox/issues/7512

**Comment by Yohahaha** [comment]
Seems we want do same thing https://github.com/oap-project/gluten/issues/3718

disable it also make sense, @zhouyuan any thoughts?

**Comment by zhli1142015** [comment]
There are two configs, `num_cached_file_handles` and `file_handle_cache_enabled`. We need the second one by now. If you need the first one also, we can add it together.

**Comment by zhli1142015** [comment]
Get it, thanks.

**Comment by zhouyuan** [comment]
@Yohahaha Velox does provide very features but not all of them are really useful. I think disabling the cache is a good solution for now. +1 on this. 

-yuan
