### ISSUE TITLE
[VL] Support rand function

### ISSUE THREAD

**Issue by Yohahaha** [oap-project/gluten#3744]
### Description

select rand();

**Comment by PHILO-HE** [comment]
It's already supported on velox side. I will enable it in gluten soon. Thanks!

**Comment by Yohahaha** [comment]
thank you!

**Comment by PHILO-HE** [comment]
Hi @Yohahaha, `rand()` should offload to native engine now as https://github.com/oap-project/gluten/pull/2749 is merged.

**Comment by Yohahaha** [comment]
> Hi @Yohahaha, `rand()` should offload to native engine now as https://github.com/oap-project/gluten/pull/2749 is merged.

thank you. i will try later.

**Comment by Yohahaha** [comment]
verified, thank you!

**Comment by ayushi-agarwal** [comment]
@PHILO-HE I was running this query spark.sql("select rand(0)") and I see results with vanilla spark are different from velox - is it expected? Is it because the difference in algorithm at both places?

**Comment by PHILO-HE** [comment]
> [@PHILO-HE](https://github.com/PHILO-HE) I was running this query spark.sql("select rand(0)") and I see results with vanilla spark are different from velox - is it expected? Is it because the difference in algorithm at both places?

@ayushi-agarwal, yes, it's expected. The result depends on the algorithm used.

**Comment by ayushi-agarwal** [comment]
> > [@PHILO-HE](https://github.com/PHILO-HE) I was running this query spark.sql("select rand(0)") and I see results with vanilla spark are different from velox - is it expected? Is it because the difference in algorithm at both places?
> 
> [@ayushi-agarwal](https://github.com/ayushi-agarwal), yes, it's expected. The result depends on the algorithm used.

Thanks, do we plan to make it compatible with spark by using same algorithm in velox?

**Comment by PHILO-HE** [comment]
> do we plan to make it compatible with spark by using same algorithm in velox?

@ayushi-agarwal, no. I think using which algorithm can be arbitrary to some extent. It seems meaningless for making this function fully consistent. Do you have any use case that requires the consistency?
