### ISSUE TITLE
Velox is built twice by build_velox.sh

### ISSUE THREAD

**Issue by zhli1142015** [oap-project/gluten#3749]
### Problem description

Looks we build velox 2 times, is this expected behavior?
Thanks.
![image](https://github.com/oap-project/gluten/assets/10524738/ecb89b1f-0fd3-4243-a0cf-aed746888d74)

### System information

Velox System Info v0.0.2

CMake Version: 3.16.3
System: Linux-5.10.102.1-microsoft-standard-WSL2
Arch: x86_64
C++ Compiler: /usr/bin/c++
C++ Compiler Version: 9.4.0
C Compiler: /usr/bin/cc
C Compiler Version: 9.4.0
CMake Prefix Path: /usr/local;/usr;/;/usr;/usr/local;/usr/X11R6;/usr/pkg;/opt

**Comment by zhli1142015** [comment]
cc @zhouyuan , @rui-mo

**Comment by zhouyuan** [comment]
@zhli1142015 looks like a bug when enabling new Velox, will do a fix, thanks!
