### ISSUE TITLE
[VL] shuffle metrics are not correct

### ISSUE THREAD

**Issue by PengleiShi** [oap-project/gluten#3799]
### Backend

VL (Velox)

### Bug description

Just a simple sql which table a join table b. In web ui, shuffle write metric is correct
![image](https://github.com/oap-project/gluten/assets/23723660/79655444-bc73-43e2-a2d7-4147cf5ebba8)
but shuffle read records seems not correct
![image](https://github.com/oap-project/gluten/assets/23723660/e91c1c1d-8670-419f-b3e8-c5565d20c90f)
I tested using spark3.4

### Spark version

None

**Comment by zhouyuan** [comment]
CC: @marin-ma

**Comment by marin-ma** [comment]
Shuffle write records is the total output rows, which is calculated and reported by Gluten. Shuffle read records is the total input batches, which is calculated by Spark `BlockStoreShuffleReader`.

In the elder version, we also collect total output batches for shuffle write records to make the two values aligned, but then we found AQE treat `shuffle write records` as the actual number of rows to compute `EliminateLimit`, therefore we had to change it to collect total output rows.

**Comment by PengleiShi** [comment]
> Shuffle write records is the total output rows, which is calculated and reported by Gluten. Shuffle read records is the total input batches, which is calculated by Spark `BlockStoreShuffleReader`.
> 
> In the older version, we also collected total output batches for shuffle write records to align the two values. However, we found that AQE treats shuffle write records as the actual number of rows for computing `EliminateLimit`. Therefore, we had to change it to collect total output rows to ensure normal behavior of AQE.

Got it, thx
