### ISSUE TITLE
generate TPCH data, but only the schema info in parquet file, no data

### ISSUE THREAD

**Issue by ruclz** [oap-project/gluten#380]
When I called the genData to generate TPCH, the program no errors, but the data isn`t converted to parquet file. just TPCH tbl data in dbgen directory. There is only 4k parquet file in the location i set.  What should i do, thank you. 
![image](https://user-images.githubusercontent.com/46258124/190587109-0c89af2b-8bf0-4889-9869-cee8b37117bd.png)

**Comment by glipner** [comment]
Relevant PR https://github.com/oap-project/gluten/pull/390

**Comment by glipner** [comment]
The cause lies not with Gluten but with `spark-perf-sql`, I created a PR pointing to a working version

**Comment by jinchengchenghh** [comment]
Maybe after `spark-perf-sql` accept your PR, we can still use databricks repo, it is not a good practice to use personal repo. What do you think?
