### ISSUE TITLE
[CH] Partition::empty() not thread safe

### ISSUE THREAD

**Issue by zhanglistar** [oap-project/gluten#3821]
<img width="540" alt="image" src="https://github.com/oap-project/gluten/assets/985418/b2eaecbf-49c0-49db-8d58-5859f2d37e8f">

**Comment by taiyang-li** [comment]
fixed by https://github.com/oap-project/gluten/pull/3728

**Comment by zzcclp** [comment]
duplicated with https://github.com/oap-project/gluten/issues/3722
