### ISSUE TITLE
Support to read dwrf format file from hdfs while use velox backend

### ISSUE THREAD

**Issue by KevinyhZou** [oap-project/gluten#388]
**Is your feature request related to a problem or challenge? Please describe what you are trying to do.**
support to read dwrf fromat file from hdfs while use velox backends

now the dwrf seems can only be read from local like  file:///a/b/c,  when the file path like hdfs://a/b/c  the exception throws from the C++ code, as '"No registered file system matched with filename hdfs:. ... '

**Describe the solution you'd like**
1.  use hdfs storage apapter provided by velox connect to hdfs and to read the file

**Describe alternatives you've considered**

**Additional context**

**Comment by FelixYBW** [comment]
HDFS support is added. But the dependency libraries has to be manually installed now.
