### ISSUE TITLE
Build failed , can't find the latest arrow jars dependency in public maven repo.

### ISSUE THREAD

**Issue by LaiZhou** [oap-project/gluten#392]
```
mvn  package -Pbackends-velox -Pfull-scala-compiler  -DskipTests -Dcheckstyle.skip -Dbuild_cpp=ON -Dbuild_velox=ON -Dbuild_arrow=ON -Dbuild_velox_from_source=ON -Dbuild_protobuf=OFF

```
Error:

```
Failed to execute goal on project backends-velox: Could not resolve dependencies for project io.glutenproject:backends-velox:jar:1.0.0-snapshot: The following artifacts could not be resolved: org.apache.arrow:arrow-memory-unsafe:jar:10.0.0-SNAPSHOT, org.apache.arrow:arrow-memory-core:jar:10.0.0-SNAPSHOT, org.apache.arrow:arrow-vector:jar:10.0.0-SNAPSHOT, org.apache.arrow.gandiva:arrow-gandiva:jar:10.0.0-SNAPSHOT, org.apache.arrow:arrow-c-data:jar:10.0.0-SNAPSHOT: Could not find artifact org.apache.arrow:arrow-memory-unsafe:jar:10.0.0-SNAPSHOT -> [Help 1]
```
I can't  find  above  arrow jars dependency in public maven repo (10.0.0-SNAPSHOT, the latest is 9.0.0).
[https://mvnrepository.com/artifact/org.apache.arrow/arrow-memory-unsafe
](https://mvnrepository.com/artifact/org.apache.arrow/arrow-memory-unsafe)

**Comment by zhztheplayer** [comment]
This should be fixed now.

**Comment by zhztheplayer** [comment]
The branch Velox backend is using is https://github.com/oap-project/arrow/tree/backend_velox_main

**Comment by zhztheplayer** [comment]
@jinchengchenghh

**Comment by jinchengchenghh** [comment]
I find your parameter -Dbuild_arrow=ON, it will revoke build_arrow.sh to build our arrow branch backends_velox_main, you can check if 10.0.0-SNAPSHOT in your local maven repository ~/.m2/repository/org/apache/arrow

**Comment by LaiZhou** [comment]
```
    mvn clean install -Dhttps.proxyHost=child-prc.intel.com -Dhttps.proxyPort=913 -P arrow-jni -pl dataset,gandiva,c -am -Darrow.cpp.build.dir=$ARROW_INSTALL_DIR/lib -DskipTests -Dcheckstyle.skip -Dmaven.gitcommitid.skip=true

```
[ERROR] Plugin org.apache.maven.plugins:maven-compiler-plugin:3.10.1 or one of its dependencies could not be resolved: Failed to read artifact descriptor for org.apache.maven.plugins:maven-compiler-plugin:jar:3.10.1: Could not transfer artifact org.apache.maven.plugins:maven-compiler-plugin:pom:3.10.1 from/to aliyunmaven (https://maven.aliyun.com/repository/central): Transfer failed for https://maven.aliyun.com/repository/central/org/apache/maven/plugins/maven-compiler-plugin/3.10.1/maven-compiler-plugin-3.10.1.pom: Unknown host child-prc.intel.com: Name or service not known -> [Help 1]

The private proxy host is not available , it should be ignored.

**Comment by LaiZhou** [comment]
https://github.com/oap-project/gluten/pull/395
