### ISSUE TITLE
Build uses "apt" while instructions use "yum"

### ISSUE THREAD

**Issue by theosib-amazon** [oap-project/gluten#396]
It seems like Gluten can't decide if it wants to be on a redhat distro or a debian distro. When I look at pages like https://github.com/oap-project/gluten/blob/main/docs/GlutenInstallation.md, the instructions use yum. But when I go to build Gluten, it wants to use apt to install things:

+ sudo --preserve-env apt install -y g++ cmake ccache ninja-build checkinstall git libssl-dev libboost-all-dev libdouble-conversion-dev libg
oogle-glog-dev libbz2-dev libgflags-dev libgtest-dev libgmock-dev libevent-dev liblz4-dev libzstd-dev libre2-dev bison flex tzdata libsnappy
-dev liblzo2-dev
sudo: apt: command not found

This seems inconsistent.

I notice in tools/build/velox_ep/scripts, there are setup scripts for setup on ubuntu and macos, but not rhel/centos/fedora, etc. How do we build gluten on one of the latter kinds of systems?

**Comment by jinchengchenghh** [comment]
Now we only support ubuntu, we will support centos on the command

**Comment by FelixYBW** [comment]
As you noted, It's velox's limitation, it only support Ubuntu20.04 now.
