### ISSUE TITLE
Build failed: Failed to find name hashes for io.substrait.proto.ReadRel

### ISSUE THREAD

**Issue by glipner** [oap-project/gluten#399]
Compiled Gluten several times today, all of a sudden keep hitting this error:
```[ERROR] ## Exception when compiling 237 sources to /home/ubuntu/gluten/jvm/target/scala-2.12/classes```
```Execution scala-compile-first of goal net.alchim31.maven:scala-maven-plugin:4.3.0:compile failed: Failed to find name hashes for io.substrait.proto.ReadRel```

**Comment by jinchengchenghh** [comment]
You should add -Pfull-scala-compiler when you build at twice time
