### ISSUE TITLE
Would not build gluten cpp in Mac OS

### ISSUE THREAD

**Issue by leesf** [oap-project/gluten#4046]
### Problem description

./get_velox.sh
./build_velox.sh
cd ./cpp && rm -rf build && mkdir build && cd build && cmake -DBUILD_VELOX_BACKEND=ON .. && make -j

then report the following error.

```
Undefined symbols for architecture x86_64:
  "fLI::FLAGS_split_preload_per_driver", referenced from:
      gluten::VeloxBackend::initConnector(facebook::velox::Config const*) in VeloxBackend.cc.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[2]: *** [releases/libvelox.dylib] Error 1
make[1]: *** [velox/CMakeFiles/velox.dir/all] Error 2
make: *** [all] Error 2

```

### System information

Mac OS

### CMake log

```bash
Undefined symbols for architecture x86_64:
  "fLI::FLAGS_split_preload_per_driver", referenced from:
      gluten::VeloxBackend::initConnector(facebook::velox::Config const*) in VeloxBackend.cc.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[2]: *** [releases/libvelox.dylib] Error 1
make[1]: *** [velox/CMakeFiles/velox.dir/all] Error 2
make: *** [all] Error 2
```

**Comment by wForget** [comment]
It may be related to #3419. You can try rebase to the latest commit of main branch.

**Comment by leesf** [comment]
> It may be related to #3419. You can try rebase to the latest commit of main branch.

I built from the commit fb3bc843b0fc9 which include the PR #3419 , so i think it is not related to the PR.

**Comment by zhli1142015** [comment]
Looks your velox code is updated but not gluten. I think you may need to pull the latest code for gluten.

**Comment by zhztheplayer** [comment]
@leesf Yes it seems like your Velox source is out-of-date. Rerunning `get_velox.sh` may help.

**Comment by leesf** [comment]
thank you guys for your help. updated code (gluten & velox) and re-compile success.
