### ISSUE TITLE
./dev/builddeps-veloxbe.sh failed installing xsimd

### ISSUE THREAD

**Issue by xumingming** [oap-project/gluten#4071]
### Problem description

I am trying to building gluten with Velox backend following the guide: https://github.com/oap-project/gluten/blob/main/docs/get-started/Velox.md

It fails with:

```
[613/613] Linking CXX static library velox/dwio/parquet/libvelox_dwio_parquet_writer.a
+ '[' -d _build/release/_deps ']'
+ cd _build/release/_deps
+ '[' -d xsimd-build ']'
+ echo 'INSTALL xsimd.'
INSTALL xsimd.
+ echo '===> CMAKE_INSTALL_PREFIX: /Users/abei/Code/velox_workspace/installed'
===> CMAKE_INSTALL_PREFIX: /Users/abei/Code/velox_workspace/installed
+ '[' Darwin == Linux ']'
+ '[' Darwin == Darwin ']'
+ cmake --install xsimd-build/
-- Install configuration: "Release"
-- Installing: /usr/local/include/xsimd
CMake Error at xsimd-build/cmake_install.cmake:41 (file):
  file INSTALL cannot make directory "/usr/local/include/xsimd": No such file
  or directory.
```

The following line is added by me in `build_velox.sh`:

```
 echo '===> CMAKE_INSTALL_PREFIX: /Users/abei/Code/velox_workspace/installed'
```

I have set CMAKE_INSTALL_PREFIX, but the script is still trying to install to the default directory, and failed.

### System information

Velox System Info v0.0.2
Commit: 23172458a26fd9bb80773be2fe056103bbb45404
CMake Version: 3.28.0
System: Darwin-23.1.0
Arch: arm64
C++ Compiler: /Library/Developer/CommandLineTools/usr/bin/c++
C++ Compiler Version: 15.0.0.15000040
C Compiler: /Library/Developer/CommandLineTools/usr/bin/cc
C Compiler Version: 15.0.0.15000040
CMake Prefix Path: /Library/Developer/CommandLineTools/SDKs/MacOSX14.0.sdk/usr;/opt/homebrew;/usr/local;/usr;/;/opt/homebrew/Cellar/cmake/3.28.0;/usr/local;/usr/X11R6;/usr/pkg;/opt;/sw;/opt/local

Result copied to cl

**Comment by huangzhir** [comment]
Last time, I also encountered the same issue. I resolved it by adding 'sudo' to 'cmake --install xsimd-build/' inside build_velox.sh, and changed it to 'cmake --install xsimd-build/'.

**Comment by xumingming** [comment]
Um, I think the thing here is, I have set CMAKE_INSTALL_PREFIX, and other velox deps are installed to the location I specified, while xsimd is installed to system default location, a better fix seems to at least install all the deps to the same location.

**Comment by xumingming** [comment]
Hmm.. Since there is not much response, closing it.
