### ISSUE TITLE
Memory Leak in long running jobs

### ISSUE THREAD

**Issue by srinivasst** [oap-project/gluten#4144]
### Backend

VL (Velox)

### Bug description

While performing a pressure test by running TPCDS (SF 3000) over and over again, after around 150 min mark the executors started failing with OOM.
```
java.lang.OutOfMemoryError: Java heap space
	at java.util.Arrays.copyOf(Arrays.java:3745) ~[?:?]
	at java.io.ByteArrayOutputStream.grow(ByteArrayOutputStream.java:120) ~[?:?]
	at java.io.ByteArrayOutputStream.ensureCapacity(ByteArrayOutputStream.java:95) ~[?:?]
	at java.io.ByteArrayOutputStream.write(ByteArrayOutputStream.java:156) ~[?:?]
	at org.apache.spark.util.ByteBufferOutputStream.write(ByteBufferOutputStream.scala:41) ~[spark-core_2.12-3.3.2.jar:3.3.2]
	at java.io.ObjectOutputStream$BlockDataOutputStream.drain(ObjectOutputStream.java:1873) ~[?:?]
	at java.io.ObjectOutputStream$BlockDataOutputStream.setBlockDataMode(ObjectOutputStream.java:1782) ~[?:?]
	at java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1180) ~[?:?]
	at java.io.ObjectOutputStream.writeObject(ObjectOutputStream.java:345) ~[?:?]
	at org.apache.spark.serializer.JavaSerializationStream.writeObject(JavaSerializer.scala:46) ~[spark-core_2.12-3.3.2.jar:3.3.2]
	at org.apache.spark.serializer.JavaSerializerInstance.serialize(JavaSerializer.scala:115) ~[spark-core_2.12-3.3.2.jar:3.3.2]
	at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:593) ~[spark-core_2.12-3.3.2.jar:3.3.2]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) ~[?:?]
	at java.lang.Thread.run(Thread.java:829) ~[?:?]
```
Here are the configs 
- spark.memory.offHeap.enabled=true
- spark.executor.memory=4g
- spark.memory.offHeap.size=24096m
- spark.plugins=io.glutenproject.GlutenPlugin
- spark.gluten.sql.columnar.backend.lib=velox
- spark.shuffle.manager=org.apache.spark.shuffle.sort.ColumnarShuffleManager
- spark.sql.autoBroadcastJoinThreshold=10485760
- spark.shuffle.service.enabled=false
- spark.gluten.sql.columnar.backend.velox.maxPartialAggregationMemoryRatio=0.75 
- spark.gluten.sql.columnar.backend.velox.maxExtendedPartialAggregationMemoryRatio=0.9

![image](https://github.com/oap-project/gluten/assets/40173930/51100763-19b5-4862-9a85-03660ae0be3e)

Both on-heap and off-heap memory is leaking. Taking a heap dump with -XX:+HeapDumpOnOutOfMemoryError I identified the cause for the leak on the Java side.
https://github.com/oap-project/gluten/blob/a24ddedc4703df742eed945d2f9909b10e3f9aec/gluten-core/src/main/java/io/glutenproject/memory/memtarget/spark/TreeMemoryConsumers.java#L77C15-L77C64

```java
MAP.computeIfAbsent(
            tmm,
            m -> {
              TreeMemoryTarget tmc = new TreeMemoryConsumer(m);
              return tmc.newChild(
                  "root", perTaskCapacity, Collections.emptyList(), Collections.emptyMap());
            });
```
tmm: TaskMemoryManager will never be garbage collected as WeakHashMap holds a hard reference over TreeMemoryTarget which holds a reference of TaskMemoryManager. The map entries are hence never removed.
<br>
I have uploaded a potential fix in the comments for on-heap memory leak.
<br>
However off-heap memory leak still persists.
![image](https://github.com/oap-project/gluten/assets/40173930/37a7ce3e-e6b1-483d-8e9c-a6f6f77c61f3)

Here the executor exited with exit code 137 after it reached its 24 GB off-heap memory limit after 400 min.

### Spark version

Spark-3.3.x

### Spark configurations

- spark.memory.offHeap.enabled=true
- spark.executor.memory=4g
- spark.memory.offHeap.size=24096m
- spark.plugins=io.glutenproject.GlutenPlugin
- spark.gluten.sql.columnar.backend.lib=velox
- spark.shuffle.manager=org.apache.spark.shuffle.sort.ColumnarShuffleManager
- spark.sql.autoBroadcastJoinThreshold=10485760
- spark.shuffle.service.enabled=false
- spark.gluten.sql.columnar.backend.velox.maxPartialAggregationMemoryRatio=0.75 
- spark.gluten.sql.columnar.backend.velox.maxExtendedPartialAggregationMemoryRatio=0.9

18 executors
9 nodes - 64 GB each

**Comment by srinivasst** [comment]
PR #4145 Proposed fix for on heap memory leak

**Comment by srinivasst** [comment]
@zhztheplayer please take a look at this issue

**Comment by surnaik** [comment]
Thanks @srinivasst for the analysis and fix! As @srinivasst mentioned above, off heap is still concerning for us, we'll investigate and address that separately. 

cc: @zhouyuan @zhztheplayer

**Comment by zhztheplayer** [comment]
Thanks. I'll setup a job on SF3000 to see if I could reproduce the off-heap memory leak. Let's proceed with https://github.com/oap-project/gluten/pull/4145 also.

**Comment by aqluheng** [comment]
> However off-heap memory leak still persists.

May I ask if the community is aware of off-heap memory leaks? I tested the version up to 2024_01_24, and the off-heap memory leak still persists. When I run TPC-DS by concating q1 to q99, the following error occurs in running of q95 and the entire system's memory is exhausted.


24/02/04 12:35:08 ERROR TaskResources: Task 656928 failed by error: 
io.glutenproject.exception.GlutenException: java.lang.RuntimeException: Exception: VeloxRuntimeError
Error Source: RUNTIME
Error Code: INVALID_STATE
Reason: Operator::getOutput failed for [operator: ValueStream, plan node ID: 1]: Error during calling Java code from native code: org.apache.spark.TaskKilledException
	at org.apache.spark.TaskContextImpl.killTaskIfInterrupted(TaskContextImpl.scala:217)
	at org.apache.spark.InterruptibleIterator.hasNext(InterruptibleIterator.scala:36)
	at scala.collection.Iterator$$anon$10.hasNext(Iterator.scala:460)
	at scala.collection.convert.Wrappers$IteratorWrapper.hasNext(Wrappers.scala:32)
	at io.glutenproject.vectorized.GeneralInIterator.hasNext(GeneralInIterator.java:31)
	at io.glutenproject.vectorized.ColumnarBatchOutIterator.nativeHasNext(Native Method)
	at io.glutenproject.vectorized.ColumnarBatchOutIterator.hasNextInternal(ColumnarBatchOutIterator.java:65)
	at io.glutenproject.vectorized.GeneralOutIterator.hasNext(GeneralOutIterator.java:37)
	at scala.collection.convert.Wrappers$JIteratorWrapper.hasNext(Wrappers.scala:45)
	at io.glutenproject.utils.IteratorCompleter.hasNext(Iterators.scala:69)
	at io.glutenproject.utils.PayloadCloser.hasNext(Iterators.scala:35)
	at io.glutenproject.utils.PipelineTimeAccumulator.hasNext(Iterators.scala:98)
	at scala.collection.Iterator$$anon$10.hasNext(Iterator.scala:460)
	at org.apache.spark.shuffle.ColumnarShuffleWriter.internalWrite(ColumnarShuffleWriter.scala:116)
	at org.apache.spark.shuffle.ColumnarShuffleWriter.write(ColumnarShuffleWriter.scala:236)
	at org.apache.spark.shuffle.ShuffleWriteProcessor.write(ShuffleWriteProcessor.scala:59)
	at org.apache.spark.scheduler.ShuffleMapTask.runTask(ShuffleMapTask.scala:99)
	at org.apache.spark.scheduler.ShuffleMapTask.runTask(ShuffleMapTask.scala:52)
	at org.apache.spark.scheduler.Task.run(Task.scala:136)
	at org.apache.spark.executor.Executor$TaskRunner.$anonfun$run$3(Executor.scala:548)
	at org.apache.spark.util.Utils$.tryWithSafeFinally(Utils.scala:1504)
	at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:551)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:750)

Retriable: False
Function: runInternal
File: ../../velox/exec/Driver.cpp
Line: 582
Stack trace:
# 0  _ZN8facebook5velox7process10StackTraceC1Ei
# 1  _ZN8facebook5velox14VeloxExceptionC1EPKcmS3_St17basic_string_viewIcSt11char_traitsIcEES7_S7_S7_bNS1_4TypeES7_
# 2  _ZN8facebook5velox6detail14veloxCheckFailINS0_17VeloxRuntimeErrorERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEEEvRKNS1_18VeloxCheckFailArgsET0_
# 3  _ZN8facebook5velox4exec6Driver11runInternalERSt10shared_ptrIS2_ERS3_INS1_13BlockingStateEERS3_INS0_9RowVectorEE
# 4  _ZN8facebook5velox4exec6Driver4nextERSt10shared_ptrINS1_13BlockingStateEE
# 5  _ZN8facebook5velox4exec4Task4nextEPN5folly10SemiFutureINS3_4UnitEEE
# 6  _ZN6gluten24WholeStageResultIterator4nextEv
# 7  Java_io_glutenproject_vectorized_ColumnarBatchOutIterator_nativeHasNext
# 8  0x0000ffff8b042678

	at io.glutenproject.vectorized.GeneralOutIterator.hasNext(GeneralOutIterator.java:39)
	at scala.collection.convert.Wrappers$JIteratorWrapper.hasNext(Wrappers.scala:45)
	at io.glutenproject.utils.IteratorCompleter.hasNext(Iterators.scala:69)
	at io.glutenproject.utils.PayloadCloser.hasNext(Iterators.scala:35)
	at io.glutenproject.utils.PipelineTimeAccumulator.hasNext(Iterators.scala:98)
	at scala.collection.Iterator$$anon$10.hasNext(Iterator.scala:460)
	at org.apache.spark.shuffle.ColumnarShuffleWriter.internalWrite(ColumnarShuffleWriter.scala:116)
	at org.apache.spark.shuffle.ColumnarShuffleWriter.write(ColumnarShuffleWriter.scala:236)
	at org.apache.spark.shuffle.ShuffleWriteProcessor.write(ShuffleWriteProcessor.scala:59)
	at org.apache.spark.scheduler.ShuffleMapTask.runTask(ShuffleMapTask.scala:99)
	at org.apache.spark.scheduler.ShuffleMapTask.runTask(ShuffleMapTask.scala:52)
	at org.apache.spark.scheduler.Task.run(Task.scala:136)
	at org.apache.spark.executor.Executor$TaskRunner.$anonfun$run$3(Executor.scala:548)
	at org.apache.spark.util.Utils$.tryWithSafeFinally(Utils.scala:1504)
	at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:551)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:750)
Caused by: java.lang.RuntimeException: Exception: VeloxRuntimeError

**Comment by surnaik** [comment]
> > However off-heap memory leak still persists.
> 
> May I ask if the community is aware of off-heap memory leaks? I tested the version up to 2024_01_24, and the off-heap memory leak still persists. When I run TPC-DS by concating q1 to q99, the following error occurs in running of q95 and the entire system's memory is exhausted.
> 
> ```
> 24/02/04 12:35:08 ERROR TaskResources: Task 656928 failed by error: 
> io.glutenproject.exception.GlutenException: java.lang.RuntimeException: Exception: VeloxRuntimeError
> Error Source: RUNTIME
> Error Code: INVALID_STATE
> Reason: Operator::getOutput failed for [operator: ValueStream, plan node ID: 1]: Error during calling Java code from native code: org.apache.spark.TaskKilledException
> 	at org.apache.spark.TaskContextImpl.killTaskIfInterrupted(TaskContextImpl.scala:217)
> 	at org.apache.spark.InterruptibleIterator.hasNext(InterruptibleIterator.scala:36)
> 	at scala.collection.Iterator$$anon$10.hasNext(Iterator.scala:460)
> 	at scala.collection.convert.Wrappers$IteratorWrapper.hasNext(Wrappers.scala:32)
> 	at io.glutenproject.vectorized.GeneralInIterator.hasNext(GeneralInIterator.java:31)
> 	at io.glutenproject.vectorized.ColumnarBatchOutIterator.nativeHasNext(Native Method)
> 	at io.glutenproject.vectorized.ColumnarBatchOutIterator.hasNextInternal(ColumnarBatchOutIterator.java:65)
> 	at io.glutenproject.vectorized.GeneralOutIterator.hasNext(GeneralOutIterator.java:37)
> 	at scala.collection.convert.Wrappers$JIteratorWrapper.hasNext(Wrappers.scala:45)
> 	at io.glutenproject.utils.IteratorCompleter.hasNext(Iterators.scala:69)
> 	at io.glutenproject.utils.PayloadCloser.hasNext(Iterators.scala:35)
> 	at io.glutenproject.utils.PipelineTimeAccumulator.hasNext(Iterators.scala:98)
> 	at scala.collection.Iterator$$anon$10.hasNext(Iterator.scala:460)
> 	at org.apache.spark.shuffle.ColumnarShuffleWriter.internalWrite(ColumnarShuffleWriter.scala:116)
> 	at org.apache.spark.shuffle.ColumnarShuffleWriter.write(ColumnarShuffleWriter.scala:236)
> 	at org.apache.spark.shuffle.ShuffleWriteProcessor.write(ShuffleWriteProcessor.scala:59)
> 	at org.apache.spark.scheduler.ShuffleMapTask.runTask(ShuffleMapTask.scala:99)
> 	at org.apache.spark.scheduler.ShuffleMapTask.runTask(ShuffleMapTask.scala:52)
> 	at org.apache.spark.scheduler.Task.run(Task.scala:136)
> 	at org.apache.spark.executor.Executor$TaskRunner.$anonfun$run$3(Executor.scala:548)
> 	at org.apache.spark.util.Utils$.tryWithSafeFinally(Utils.scala:1504)
> 	at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:551)
> 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
> 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
> 	at java.lang.Thread.run(Thread.java:750)
> 
> Retriable: False
> Function: runInternal
> File: ../../velox/exec/Driver.cpp
> Line: 582
> Stack trace:
> # 0  _ZN8facebook5velox7process10StackTraceC1Ei
> # 1  _ZN8facebook5velox14VeloxExceptionC1EPKcmS3_St17basic_string_viewIcSt11char_traitsIcEES7_S7_S7_bNS1_4TypeES7_
> # 2  _ZN8facebook5velox6detail14veloxCheckFailINS0_17VeloxRuntimeErrorERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEEEvRKNS1_18VeloxCheckFailArgsET0_
> # 3  _ZN8facebook5velox4exec6Driver11runInternalERSt10shared_ptrIS2_ERS3_INS1_13BlockingStateEERS3_INS0_9RowVectorEE
> # 4  _ZN8facebook5velox4exec6Driver4nextERSt10shared_ptrINS1_13BlockingStateEE
> # 5  _ZN8facebook5velox4exec4Task4nextEPN5folly10SemiFutureINS3_4UnitEEE
> # 6  _ZN6gluten24WholeStageResultIterator4nextEv
> # 7  Java_io_glutenproject_vectorized_ColumnarBatchOutIterator_nativeHasNext
> # 8  0x0000ffff8b042678
> 
> 	at io.glutenproject.vectorized.GeneralOutIterator.hasNext(GeneralOutIterator.java:39)
> 	at scala.collection.convert.Wrappers$JIteratorWrapper.hasNext(Wrappers.scala:45)
> 	at io.glutenproject.utils.IteratorCompleter.hasNext(Iterators.scala:69)
> 	at io.glutenproject.utils.PayloadCloser.hasNext(Iterators.scala:35)
> 	at io.glutenproject.utils.PipelineTimeAccumulator.hasNext(Iterators.scala:98)
> 	at scala.collection.Iterator$$anon$10.hasNext(Iterator.scala:460)
> 	at org.apache.spark.shuffle.ColumnarShuffleWriter.internalWrite(ColumnarShuffleWriter.scala:116)
> 	at org.apache.spark.shuffle.ColumnarShuffleWriter.write(ColumnarShuffleWriter.scala:236)
> 	at org.apache.spark.shuffle.ShuffleWriteProcessor.write(ShuffleWriteProcessor.scala:59)
> 	at org.apache.spark.scheduler.ShuffleMapTask.runTask(ShuffleMapTask.scala:99)
> 	at org.apache.spark.scheduler.ShuffleMapTask.runTask(ShuffleMapTask.scala:52)
> 	at org.apache.spark.scheduler.Task.run(Task.scala:136)
> 	at org.apache.spark.executor.Executor$TaskRunner.$anonfun$run$3(Executor.scala:548)
> 	at org.apache.spark.util.Utils$.tryWithSafeFinally(Utils.scala:1504)
> 	at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:551)
> 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
> 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
> 	at java.lang.Thread.run(Thread.java:750)
> Caused by: java.lang.RuntimeException: Exception: VeloxRuntimeError
> ```

Yes, we're aware of this. We haven't addressed any specific fix for the off heap memory leak yet. 

Could you please provide the spark and gluten configuration used for your run, the scale factor for benchmark used.

**Comment by surnaik** [comment]
cc: @srinivasst @zhztheplayer

**Comment by zhouyuan** [comment]
Hi @srinivasst @aqluheng @surnaik 

If I understand correctly, the issue is due to big memory footprint rather then leakage. 
- the memory showed in the picture is using RSS memory from `top`
- TPC-DS Q95 has two big joins on the `store_sales`, and it will introduce big memory footprint as Gluten currently used "Hash Join". In your case, it seems in run into some bug on the spill code path
- There's one pending patch to reduce the footprint for Q95 in Velox but merged yet

Modern memory allocators will not return the just freed memory to OS to achieve better performance, also a set of memory allocation pools will be used to reduce the lock contention. Recent version of glibc also [used](https://sourceware.org/bugzilla/show_bug.cgi?id=11261) similar design - by default it has 8 * cores pools, each with 64MB size. This will introduce a big memory footprint. Jemalloc's pool is smaller relatively - it has 4 * cores pools, each with 2MB size. Both glibc/jemalloc provides turning knobs to control these behaviors. Using lower number of pools can reduce the memory footprint, but also may impact the performance. It's a tradeoff on memory vs. performance.

You may have a try to switch to jemalloc based allocator by adding below config: 
`--conf spark.executorEnv.LD_PRELOAD=/path/to/libjemalloc.so`

Here's one example run on my testing env, you may notice there's a spike on the end of the curve which is the Q95
![rssmem](https://github.com/oap-project/gluten/assets/43917/8a5c2dba-0039-411c-8ac2-6d94a3ebce30)

Thanks, 
-yuan

**Comment by aqluheng** [comment]
> > > However off-heap memory leak still persists.
> > 
> > 
> > May I ask if the community is aware of off-heap memory leaks? I tested the version up to 2024_01_24, and the off-heap memory leak still persists. When I run TPC-DS by concating q1 to q99, the following error occurs in running of q95 and the entire system's memory is exhausted.
> > ```
> > 24/02/04 12:35:08 ERROR TaskResources: Task 656928 failed by error: 
> > io.glutenproject.exception.GlutenException: java.lang.RuntimeException: Exception: VeloxRuntimeError
> > Error Source: RUNTIME
> > Error Code: INVALID_STATE
> > Reason: Operator::getOutput failed for [operator: ValueStream, plan node ID: 1]: Error during calling Java code from native code: org.apache.spark.TaskKilledException
> > 	at org.apache.spark.TaskContextImpl.killTaskIfInterrupted(TaskContextImpl.scala:217)
> > 	at org.apache.spark.InterruptibleIterator.hasNext(InterruptibleIterator.scala:36)
> > 	at scala.collection.Iterator$$anon$10.hasNext(Iterator.scala:460)
> > 	at scala.collection.convert.Wrappers$IteratorWrapper.hasNext(Wrappers.scala:32)
> > 	at io.glutenproject.vectorized.GeneralInIterator.hasNext(GeneralInIterator.java:31)
> > 	at io.glutenproject.vectorized.ColumnarBatchOutIterator.nativeHasNext(Native Method)
> > 	at io.glutenproject.vectorized.ColumnarBatchOutIterator.hasNextInternal(ColumnarBatchOutIterator.java:65)
> > 	at io.glutenproject.vectorized.GeneralOutIterator.hasNext(GeneralOutIterator.java:37)
> > 	at scala.collection.convert.Wrappers$JIteratorWrapper.hasNext(Wrappers.scala:45)
> > 	at io.glutenproject.utils.IteratorCompleter.hasNext(Iterators.scala:69)
> > 	at io.glutenproject.utils.PayloadCloser.hasNext(Iterators.scala:35)
> > 	at io.glutenproject.utils.PipelineTimeAccumulator.hasNext(Iterators.scala:98)
> > 	at scala.collection.Iterator$$anon$10.hasNext(Iterator.scala:460)
> > 	at org.apache.spark.shuffle.ColumnarShuffleWriter.internalWrite(ColumnarShuffleWriter.scala:116)
> > 	at org.apache.spark.shuffle.ColumnarShuffleWriter.write(ColumnarShuffleWriter.scala:236)
> > 	at org.apache.spark.shuffle.ShuffleWriteProcessor.write(ShuffleWriteProcessor.scala:59)
> > 	at org.apache.spark.scheduler.ShuffleMapTask.runTask(ShuffleMapTask.scala:99)
> > 	at org.apache.spark.scheduler.ShuffleMapTask.runTask(ShuffleMapTask.scala:52)
> > 	at org.apache.spark.scheduler.Task.run(Task.scala:136)
> > 	at org.apache.spark.executor.Executor$TaskRunner.$anonfun$run$3(Executor.scala:548)
> > 	at org.apache.spark.util.Utils$.tryWithSafeFinally(Utils.scala:1504)
> > 	at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:551)
> > 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
> > 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
> > 	at java.lang.Thread.run(Thread.java:750)
> > 
> > Retriable: False
> > Function: runInternal
> > File: ../../velox/exec/Driver.cpp
> > Line: 582
> > Stack trace:
> > # 0  _ZN8facebook5velox7process10StackTraceC1Ei
> > # 1  _ZN8facebook5velox14VeloxExceptionC1EPKcmS3_St17basic_string_viewIcSt11char_traitsIcEES7_S7_S7_bNS1_4TypeES7_
> > # 2  _ZN8facebook5velox6detail14veloxCheckFailINS0_17VeloxRuntimeErrorERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEEEvRKNS1_18VeloxCheckFailArgsET0_
> > # 3  _ZN8facebook5velox4exec6Driver11runInternalERSt10shared_ptrIS2_ERS3_INS1_13BlockingStateEERS3_INS0_9RowVectorEE
> > # 4  _ZN8facebook5velox4exec6Driver4nextERSt10shared_ptrINS1_13BlockingStateEE
> > # 5  _ZN8facebook5velox4exec4Task4nextEPN5folly10SemiFutureINS3_4UnitEEE
> > # 6  _ZN6gluten24WholeStageResultIterator4nextEv
> > # 7  Java_io_glutenproject_vectorized_ColumnarBatchOutIterator_nativeHasNext
> > # 8  0x0000ffff8b042678
> > 
> > 	at io.glutenproject.vectorized.GeneralOutIterator.hasNext(GeneralOutIterator.java:39)
> > 	at scala.collection.convert.Wrappers$JIteratorWrapper.hasNext(Wrappers.scala:45)
> > 	at io.glutenproject.utils.IteratorCompleter.hasNext(Iterators.scala:69)
> > 	at io.glutenproject.utils.PayloadCloser.hasNext(Iterators.scala:35)
> > 	at io.glutenproject.utils.PipelineTimeAccumulator.hasNext(Iterators.scala:98)
> > 	at scala.collection.Iterator$$anon$10.hasNext(Iterator.scala:460)
> > 	at org.apache.spark.shuffle.ColumnarShuffleWriter.internalWrite(ColumnarShuffleWriter.scala:116)
> > 	at org.apache.spark.shuffle.ColumnarShuffleWriter.write(ColumnarShuffleWriter.scala:236)
> > 	at org.apache.spark.shuffle.ShuffleWriteProcessor.write(ShuffleWriteProcessor.scala:59)
> > 	at org.apache.spark.scheduler.ShuffleMapTask.runTask(ShuffleMapTask.scala:99)
> > 	at org.apache.spark.scheduler.ShuffleMapTask.runTask(ShuffleMapTask.scala:52)
> > 	at org.apache.spark.scheduler.Task.run(Task.scala:136)
> > 	at org.apache.spark.executor.Executor$TaskRunner.$anonfun$run$3(Executor.scala:548)
> > 	at org.apache.spark.util.Utils$.tryWithSafeFinally(Utils.scala:1504)
> > 	at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:551)
> > 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
> > 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
> > 	at java.lang.Thread.run(Thread.java:750)
> > Caused by: java.lang.RuntimeException: Exception: VeloxRuntimeError
> > ```
> 
> Yes, we're aware of this. We haven't addressed any specific fix for the off heap memory leak yet.
> 
> Could you please provide the spark and gluten configuration used for your run, the scale factor for benchmark used.

I used 1master+3worker to run tpcds3T, the configuration is as below.
The yarn memory is set to 110.5GB, the total memory of system is 122G.
```
spark.executor.cores 7
spark.executor.memory 2G
spark.executor.memoryOverhead 1g
spark.memory.offHeap.enabled true
spark.memory.offHeap.size 10g
spark.driverEnv.LD_PRELOAD /usr/lib64/libjemalloc.so.2
spark.executorEnv.LD_PRELOAD /usr/lib64/libjemalloc.so.2
spark.executorEnv.MALLOC_CONF narenas:2  
spark.gluten.sql.columnar.maxBatchSize 4096
```

**Comment by aqluheng** [comment]
> Hi @srinivasst @aqluheng @surnaik
> 
> If I understand correctly, the issue is due to big memory footprint rather then leakage.
> 
> * the memory showed in the picture is using RSS memory from `top`
> * TPC-DS Q95 has two big joins on the `web_sales`, and it will introduce big memory footprint as Gluten currently used "Hash Join". In your case, it seems in run into some bug on the spill code path
> * There's one pending patch to reduce the footprint for Q95 in Velox but merged yet
> 
> Modern memory allocators will not return the just freed memory to OS to achieve better performance, also a set of memory allocation pools will be used to reduce the lock contention. Recent version of glibc also [used](https://sourceware.org/bugzilla/show_bug.cgi?id=11261) similar design - by default it has 8 * cores pools, each with 64MB size. This will introduce a big memory footprint. Jemalloc's pool is smaller relatively - it has 4 * cores pools, each with 2MB size. Both glibc/jemalloc provides turning knobs to control these behaviors. Using lower number of pools can reduce the memory footprint, but also may impact the performance. It's a tradeoff on memory vs. performance.
> 
> You may have a try to switch to jemalloc based allocator by adding below config: `--conf spark.executorEnv.LD_PRELOAD=/path/to/libjemalloc.so`
> 
> Here's one example run on my testing env, you may notice there's a spike on the end of the curve which is the Q95 ![rssmem](https://private-user-images.githubusercontent.com/43917/302145990-8a5c2dba-0039-411c-8ac2-6d94a3ebce30.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDcwOTkwMjEsIm5iZiI6MTcwNzA5ODcyMSwicGF0aCI6Ii80MzkxNy8zMDIxNDU5OTAtOGE1YzJkYmEtMDAzOS00MTFjLThhYzItNmQ5NGEzZWJjZTMwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjA1VDAyMDUyMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWNlOWZlYTQ4NjMwNTliZjg5ODI0NTlmNWY0OWQzMzkxYWY1YzU2OTRiNDcxMGE0ZGNhYjRhODk3Zjk3OTNiZmMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.oHg8hmJQ-SMTBuuQBm6hRfq7mDgHdGcw4rJhKNCYgPE)
> 
> Thanks, -yuan

I test this patch https://github.com/facebookincubator/velox/pull/7066, but q95 still crash.
In my observation, running q95 alone can pass, and it occupies 92GB of system memory. 
However, when I run from q1 to q95, there is about 40GB of memory that cannot be released. 
With q95 using 92GB, this will lead to insufficient system space (40GB + 92GB > 122GB). 
In addition, the memory used by the Executors also exceeds the maximum memory configured in Yarn(115GB>110GB).

**Comment by zhouyuan** [comment]
@aqluheng thanks for analysis and the update!
based on the description, it's likely you may hit the "post join spill" issue, which Velox community is working on to support.
https://github.com/oap-project/gluten/issues/3030

would it be convenient for you to increase the shuffle parallelism(spark.sql.shuffle.partitions) to check if Q95 can pass?

I'm also attaching the memory usage for repeat Q95 for 10 times in my env.
![image](https://github.com/oap-project/gluten/assets/43917/94f4f6ba-ce76-4f3d-a733-71fd809a7ef0)


-yuan

**Comment by srinivasst** [comment]
Hi @zhouyuan 

As per my test it does not crash during query 95. It crashes at around the 4th iteration of TPCDS 3TB Scale Factor benchmark run.
As you can see in the image the RES memory gradually keeps increasing and memory is never released.
By the 400th minute it reaches the maximum memory available in the VM and crashes. This behaviour is reproducible even with 1TB Scale Factor.

I am using Gluten v1.1.0.

![image](https://github.com/oap-project/gluten/assets/40173930/3806c787-a764-4090-b8c0-e543fca9b625)

**Comment by FelixYBW** [comment]
@zhouyuan I set muzzy_decay_ms:0,dirty_decay_ms:0,background_thread:false,narenas:1,tcache:false,stats_print:true but looks no help. Looks some memory not allocated for velox is leaking

**Comment by zhztheplayer** [comment]
@srinivasst Would you like to share the executor process crash log? Which may probably help diagnose. Thanks.

**Comment by FelixYBW** [comment]
With PR4748 fix, Looks the leak is solved. @srinivasst . Can you verify? Let's close the issue once you confirm.

![image](https://github.com/oap-project/gluten/assets/47296334/85676e94-0d1c-4aca-ad3e-19ab38a3ba5b)

**Comment by srinivasst** [comment]
I can confirm the same
The issue is not happening after this fix.
![image](https://github.com/oap-project/gluten/assets/40173930/0862f17c-6ef7-4ee1-9d2e-b0dd74dbdc3a)
