### ISSUE TITLE
Documentation: Not clear libhdfs3 installation instruction

### ISSUE THREAD

**Issue by j-buczak** [oap-project/gluten#417]
**Describe the bug**
Documentation is not clear about `libhdfs3` [installation instructions](https://github.com/oap-project/gluten/blob/main/docs/GlutenInstallation.md#use-libhdfs3-library-for-better-performanceoptional). 

The question I have:
1.Are steps described in _"Option1: Overwrite the soft link for libhdfs.so"_ / _"Option2: Add env variable to the system"_ necessary after installation with Conda?
2. Can I use apt-get installation option as described in [hdfs3 official installation instructions](https://hdfs3.readthedocs.io/en/latest/install.html#pypi-and-apt-get)

**Additional context**
I'm trying to create Docker image with Gluten + Velox installation.

**Comment by FelixYBW** [comment]
The document is copied from Gazelle, it's outdated. PR425 removed it. 
We haven't add hdfs support for Velox backed. It's still WIP.
