### ISSUE TITLE
Documentation: Spark version not consistent across instructions

### ISSUE THREAD

**Issue by j-buczak** [oap-project/gluten#418]
**Describe the bug**
In main readme you there is a statement:
>  Spark3.2.x is the only version to be supported currently

However in installation instructions you use `3.1.1` version

**Additional context**
I'm trying to create Docker image with Gluten + Velox installation.

**Comment by FelixYBW** [comment]
The doc is copied from Gazelle. Removed. Assume that customer is familar with Spark and Hadoop installation.
