### ISSUE TITLE
Support for Java 17

### ISSUE THREAD

**Issue by j-buczak** [oap-project/gluten#420]
**Is your feature request related to a problem or challenge? Please describe what you are trying to do.**
I was checking if Gluten + Velox can be used with Java 17. I managed to successfully build it with `sun.misc.Cleaner` disabled (so it's not workable solution).
Do you plan to support Java 17?

**Describe the solution you'd like**
Remove functions deprecated in Java 17.

**Comment by FelixYBW** [comment]
No, We have no plan to support java17.
