### ISSUE TITLE
spark.test.home config in Spark 3.4 workflow point to /opt/spark331

### ISSUE THREAD

**Issue by ayushi-agarwal** [oap-project/gluten#4203]
### Backend

VL (Velox)

### Bug description

Line 224 and Line 260 in file https://github.com/oap-project/gluten/blob/main/.github/workflows/velox_be.yml points to spark 331 path, instead it should be pointing to spark 341 path. Tried changing it to /opt/spark341 but build failed with no such path found.
This results in some UT failures with spark 3.4 version like GlutenExpressionsSchemaSuite.

### Spark version

None

**Comment by ayushi-agarwal** [comment]
@zhouyuan Could you please take a look at this?
cc @zhli1142015

**Comment by zhouyuan** [comment]
@ayushi-agarwal thanks for reporting, the issue is due to old CI images were used - will update the image to include spark341 this week

thanks, -yuan

**Comment by ayushi-agarwal** [comment]
Thanks @zhouyuan

**Comment by vibhaska** [comment]
I think CI/CD failures for https://github.com/oap-project/gluten/pull/4273 is related.

@zhouyuan @ayushi-agarwal Maybe we can consider spark342 now

**Comment by ayushi-agarwal** [comment]
Fixed with this https://github.com/oap-project/gluten/pull/4362/files
