### ISSUE TITLE
/home/yarn/java-current/bin/java': free(): invalid pointer: 0x00007f87cd7cac80 ***

### ISSUE THREAD

**Issue by guixiaowen** [oap-project/gluten#4216]
### Backend

VL (Velox)

### Bug description

[Expected behavior] and [actual behavior].

1. ERROR INFO
`*** Error in `/home/yarn/java-current/bin/java': free(): invalid pointer: 0x00007f87cd7cac80 ***
======= Backtrace: =========
/lib64/[libc.so](http://libc.so/).6(+0x7d053)[0x7f881c0e8053]
/lib64/libstdc++.so.6(_ZNSt6locale5_Impl16_M_install_facetEPKNS_2idEPKNS_5facetE+0x142)[0x7f87cd5340d2]
/lib64/libstdc++.so.6(_ZNSt6locale5_ImplC1Em+0x1e3)[0x7f87cd534523]
/lib64/libstdc++.so.6(+0x71495)[0x7f87cd535495]
/lib64/[libpthread.so](http://libpthread.so/).0(pthread_once+0x50)[0x7f881c853bb0]
/lib64/libstdc++.so.6(+0x714e1)[0x7f87cd5354e1]
/lib64/libstdc++.so.6(_ZNSt6localeC2Ev+0x13)[0x7f87cd535523]
/lib64/libstdc++.so.6(_ZNSt8ios_base4InitC2Ev+0xbc)[0x7f87cd53237c]
/data1/hadoopdata/nodemanager/local/usercache/prod_prod_bigdata_qa/appcache/application_1699342592674_7708850/container_e1095_1699342592674_7708850_01_000010/tmp/jnilib-3418461805491270847.tmp(+0x2a90)[0x7f87d0487a90]
/lib64/ld-linux-x86-64.so.2(+0xf3a3)[0x7f881cc7b3a3]
/lib64/ld-linux-x86-64.so.2(+0x13ab6)[0x7f881cc7fab6]
/lib64/ld-linux-x86-64.so.2(+0xf1b4)[0x7f881cc7b1b4]
/lib64/ld-linux-x86-64.so.2(+0x131ab)[0x7f881cc7f1ab]
/lib64/[libdl.so](http://libdl.so/).2(+0x102b)[0x7f881c42e02b]
/lib64/ld-linux-x86-64.so.2(+0xf1b4)[0x7f881cc7b1b4]
/lib64/[libdl.so](http://libdl.so/).2(+0x162d)[0x7f881c42e62d]
/lib64/[libdl.so](http://libdl.so/).2(dlopen+0x31)[0x7f881c42e0c1]
/usr/local/jdk1.8.0_77/jre/lib/amd64/server/[libjvm.so](http://libjvm.so/)(+0x91e8ee)[0x7f881b9a98ee]
/usr/local/jdk1.8.0_77/jre/lib/amd64/server/[libjvm.so](http://libjvm.so/)(JVM_LoadLibrary+0x14c)[0x7f881b7a02ac]
/usr/local/jdk1.8.0_77/jre/lib/amd64/[libjava.so](http://libjava.so/)(Java_java_lang_ClassLoader_00024NativeLibrary_load+0x138)[0x7f881a754da8]
[0x7f8805015994]`

2. detail infomation
OS : Centos7 x86_64

Spark Version : Spark 3.2.x

JDK: sun jdk 1.8.0_77-b03

3. Gluten Version

V1.0.0

### Spark version

Spark-3.2.x

### Spark configurations

nothing special

### System information

OS : Centos7 x86_64

Spark Version : Spark 3.2.x

JDK: sun jdk 1.8.0_77-b03

### Relevant logs

```bash
nothing special
```

**Comment by PHILO-HE** [comment]
Assume fixed. Closing this issue. Thanks!
