### ISSUE TITLE
Using wrong symbol for ARM64 throws error while building Arrow

### ISSUE THREAD

**Issue by theosib-amazon** [oap-project/gluten#422]
When attempting to find out if _M_ARM64 exists, an error is thrown. It should probably be using __amd64 instead. Note that I am using compiler versions higher than the minimum recommended.

```
Determining if the _M_ARM64 exist failed with the following output:
Change Dir: /local/home/theosib/gluten/gluten/tools/build/arrow_ep/cpp/build/CMakeFiles/CMakeTmp

Run Build Command(s):/usr/bin/ninja-build cmTC_c7dde && [1/2] Building CXX object CMakeFiles/cmTC_c7dde.dir/CheckSymbolExists.cxx.o
FAILED: CMakeFiles/cmTC_c7dde.dir/CheckSymbolExists.cxx.o
/usr/bin/c++   -fdiagnostics-color=always -O2 -DNDEBUG -ftree-vectorize  -fPIE -o CMakeFiles/cmTC_c7dde.dir/CheckSymbolExists.cxx.o -c /local/home/theosib/gluten/gluten/tools/build/arrow_ep/cpp/build/CMakeFiles/CMakeTmp/CheckSymbolExists.cxx
/local/home/theosib/gluten/gluten/tools/build/arrow_ep/cpp/build/CMakeFiles/CMakeTmp/CheckSymbolExists.cxx: In function ‘int main(int, char**)’:
/local/home/theosib/gluten/gluten/tools/build/arrow_ep/cpp/build/CMakeFiles/CMakeTmp/CheckSymbolExists.cxx:7:19: error: ‘_M_ARM64’ was not declared in this scope
   return ((int*)(&_M_ARM64))[argc];
                   ^~~~~~~~
/local/home/theosib/gluten/gluten/tools/build/arrow_ep/cpp/build/CMakeFiles/CMakeTmp/CheckSymbolExists.cxx:7:19: note: suggested alternative: ‘__amd64’
   return ((int*)(&_M_ARM64))[argc];
                   ^~~~~~~~
                   __amd64
ninja: build stopped: subcommand failed.


File /local/home/theosib/gluten/gluten/tools/build/arrow_ep/cpp/build/CMakeFiles/CMakeTmp/CheckSymbolExists.cxx:
/* */

int main(int argc, char** argv)
{
  (void)argv;
#ifndef _M_ARM64
  return ((int*)(&_M_ARM64))[argc];
#else
  (void)argc;
  return 0;
#endif
}
```

**Comment by theosib-amazon** [comment]
Wanted to try building Arrow myself, but the instructions are missing:
https://github.com/oap-project/gluten/blob/main/docs/ArrowInstallation.md

**Comment by theosib-amazon** [comment]
This very same issue shows up on both Amazon Linux and Ubuntu 20.04. The script at downloads Arrow must be downloading a different version from what you're expecting, because it's properly broken.

**Comment by FelixYBW** [comment]
Is it solved after remove the  child-prc proxy?

**Comment by theosib-amazon** [comment]
No. I had to install that manually. The child-prc proxy was only related to Java artifacts. This is related to building C/C++ code.

**Comment by FelixYBW** [comment]
Done by this PR: https://github.com/oap-project/gluten/pull/433/

**Comment by loukey-lj** [comment]
@FelixYBW hellow, Is this problem solved? I am doing build_arrow.sh error in the 0.5.0 branch,

Determining if the pthread_create exist failed with the following output:
Change Dir: /app/lj/gluten/ep/build-arrow/build/arrow_ep/cpp/build/CMakeFiles/CMakeTmp

Run Build Command:"/app/lj/ninja_bin/ninja" "cmTC_ceca4"
[1/2] Building C object CMakeFiles/cmTC_ceca4.dir/CheckSymbolExists.c.o
[2/2] Linking C executable cmTC_ceca4
FAILED: cmTC_ceca4 
: && /app/lj/gcc-9.5.0/bin/gcc     CMakeFiles/cmTC_ceca4.dir/CheckSymbolExists.c.o  -o cmTC_ceca4   && :
CMakeFiles/cmTC_ceca4.dir/CheckSymbolExists.c.o: In function `main':
CheckSymbolExists.c:(.text+0x1b): undefined reference to `pthread_create'
collect2: error: ld returned 1 exit status
ninja: build stopped: subcommand failed.

File /app/lj/gluten/ep/build-arrow/build/arrow_ep/cpp/build/CMakeFiles/CMakeTmp/CheckSymbolExists.c:
/* */
#include <pthread.h>

int main(int argc, char** argv)
{
  (void)argv;
#ifndef pthread_create
  return ((int*)(&pthread_create))[argc];
#else
  (void)argc;
  return 0;
#endif
}

Determining if the _M_ARM64 exist failed with the following output:
Change Dir: /app/lj/gluten/ep/build-arrow/build/arrow_ep/cpp/build/CMakeFiles/CMakeTmp

Run Build Command:"/app/lj/ninja_bin/ninja" "cmTC_59a5d"
[1/2] Building CXX object CMakeFiles/cmTC_59a5d.dir/CheckSymbolExists.cxx.o
FAILED: CMakeFiles/cmTC_59a5d.dir/CheckSymbolExists.cxx.o 
/app/lj/gcc-9.5.0/bin/g++     -fdiagnostics-color=always  -fPIE -o CMakeFiles/cmTC_59a5d.dir/CheckSymbolExists.cxx.o -c CheckSymbolExists.cxx
CheckSymbolExists.cxx: In function ‘int main(int, char**)’:
CheckSymbolExists.cxx:7:19: error: ‘_M_ARM64’ was not declared in this scope
    7 |   return ((int*)(&_M_ARM64))[argc];
      |                   ^~~~~~~~
ninja: build stopped: subcommand failed.

File /app/lj/gluten/ep/build-arrow/build/arrow_ep/cpp/build/CMakeFiles/CMakeTmp/CheckSymbolExists.cxx:
/* */

int main(int argc, char** argv)
{
  (void)argv;
#ifndef _M_ARM64
  return ((int*)(&_M_ARM64))[argc];
#else
  (void)argc;
  return 0;
#endif
}

**Comment by zhejiangxiaomai** [comment]
--cmake version 3.6.3
please upgrade cmake version.
 https://github.com/oap-project/gluten/blob/main/cpp/CMakeLists.txt#L18
