### ISSUE TITLE
[VL] Dependency on libcrypto not explicit

### ISSUE THREAD

**Issue by theosib-amazon** [oap-project/gluten#423]
Among the numerous dependencies that Gluten fails to find, another one is libcrypto. I'm using a clean Ubuntu 20.04. It would be good if the instructions included ALL dependencies that are required. Some are really hard to figure out from the relatively useless error messages.

https://superuser.com/questions/1059499/error-openssl-crypto-development-libraries-are-not-installed-properly-in-requir

**Comment by FelixYBW** [comment]
Is it solved after remove the  child-prc proxy?

**Comment by theosib-amazon** [comment]
No. I had to install OpenSSL manually.

**Comment by FelixYBW** [comment]
Should we modify the doc here? https://github.com/oap-project/gluten/blob/main/docs/Velox.md. What's the apt command you used?

**Comment by theosib-amazon** [comment]
Ubuntu seems to have this installed by default. I hacked the heck out of everything to get it to build on Amazon Linux 2.

So I had to do all this:

704 mkdir openssl
705 cd openssl
706 wget https://www.openssl.org/source/openssl-1.1.1q.tar.gz
708 tar zxvf openssl-1.1.1q.tar.gz
710 cd openssl-1.1.1q
717 ./config —prefix=/opt/local —openssldir=/opt/local/ssl
718 sudo mkdir /opt/local
719 make
722 sudo make install
723 cd /opt
725 cd local
727 cd bin
729 export PATH=$(pwd):$PATH
730 cd ..
732 cd lib
734 export OPENSSL_LIB_DIR=$(pwd)
735 cd ..
737 cd include
738 export OPENSSL_INCLUDE_DIR=$(pwd)
739 cd ..
740 export OPENSSL_DIR=$(pwd)
748 export OPENSSL_ROOT_DIR=$OPENSSL_DIR
753 export OPENSSL_LIBRARIES=$OPENSSL_LIB_DIR

**Comment by zhouyuan** [comment]
closing this this has been for a while, feel free to re-open if this still stands
