### ISSUE TITLE
[VL] Support cross join type with Merge join and Hash join

### ISSUE THREAD

**Issue by Surbhi-Vijay** [oap-project/gluten#4266]
### Description

A join gets converted to hash join or merge join only when there are equi join conditions.

Consider query `select * from Tbl1 cross join Tbl2 on Tbl1.c1 = Tbl2.c1` This join will be converted to hash join or merge join depending on data type and size. This query is equivalent to `select * from Tbl1 inner join Tbl2 on Tbl1.c1 = Tbl2.c1`.

Cross join with non equi join conditions will never get converted to hash or merge join. Considering these facts cross join with equi join conditions can safely be added to hash/merge joins. 

There will only be need to add it in supported join type and it can be mapped to `JoinRel.JoinType.JOIN_TYPE_INNER` in substrait.

**Comment by Surbhi-Vijay** [comment]
There is `TODO` in code to support it with `crossRel` but this will not be required.
```
object SubstraitUtil {
  def toSubstrait(sparkJoin: JoinType): JoinRel.JoinType = sparkJoin match {
    case Inner =>
      JoinRel.JoinType.JOIN_TYPE_INNER
    case FullOuter =>
      JoinRel.JoinType.JOIN_TYPE_OUTER
    case LeftOuter | RightOuter =>
      // The right side is required to be used for building hash table in Substrait plan.
      // Therefore, for RightOuter Join, the left and right relations are exchanged and the
      // join type is reverted.
      JoinRel.JoinType.JOIN_TYPE_LEFT
    case LeftSemi =>
      JoinRel.JoinType.JOIN_TYPE_LEFT_SEMI
    case LeftAnti =>
      JoinRel.JoinType.JOIN_TYPE_ANTI
    case _ =>
      // TODO: Support cross join with Cross Rel
      // TODO: Support existence join
      JoinRel.JoinType.UNRECOGNIZED
  }
}

```

Cross join with non equi join conditions will get converted to either `BroadcastNestedLoopJoinExec` or `CartesianProductExec`. Both of these will be supported with `crossRel`.

**Comment by Surbhi-Vijay** [comment]
@zhouyuan @rui-mo Can you please check this issue and let me know if you see any issue with it?

**Comment by zhouyuan** [comment]
@Surbhi-Vijay I think you are correct, the code is introduced by CK backend - maybe something different in CK impl
