### ISSUE TITLE
[GLUTEN-4336][VL]Questions about Parquet compression format

### ISSUE THREAD

**Issue by rhh777** [oap-project/gluten#4336]
### Backend

VL (Velox)

### Bug description

As described in velox-backend-limitations.md, parquetscan does not support lzo, lz4, and zlib compression formats. During the actual test, there was no problem in reading.

https://github.com/oap-project/gluten/blob/main/docs/velox-backend-limitations.md#exception-caused-by-file-compression-codec

create table sql:
```
create table parquet_compress_lzo (col1 string, col2 int) stored as parquet tblproperties ("parquet.compression"="lzo");

create table parquet_compress_lz4 (col1 string, col2 int) stored as parquet tblproperties ("parquet.compression"="lz4");
```

table  data file
```
(venvs) [hdfs@offline1 ~]$ hadoop fs -ls /warehouse/tablespace/managed/hive/parquet_compress_lzo
-rw-rw----+  2 hdfs hadoop          0 2024-01-09 16:58 /warehouse/tablespace/managed/hive/parquet_compress_lzo/_SUCCESS
-rw-rw----+  2 hdfs hadoop        757 2024-01-09 16:58 /warehouse/tablespace/managed/hive/parquet_compress_lzo/part-00000-ad96f08c-9d21-4764-a659-65bb9ed59de6-c000.lzo.parquet
(venvs) [hdfs@offline1 ~]$ hadoop fs -ls /warehouse/tablespace/managed/hive/parquet_compress_lz4
-rw-rw----+  2 hdfs hadoop          0 2024-01-09 17:01 /warehouse/tablespace/managed/hive/parquet_compress_lz4/_SUCCESS
-rw-rw----+  2 hdfs hadoop        752 2024-01-09 17:01 /warehouse/tablespace/managed/hive/parquet_compress_lz4/part-00000-5f5b03ef-b2f3-422d-8066-f7252abba841-c000.lz4.parquet
```

query sql:
```
spark-sql> select * from parquet_compress_lzo;
compress_lzo    5
Time taken: 0.187 seconds, Fetched 1 row(s)
spark-sql> select * from parquet_compress_lz4;
compress_lz4    6
Time taken: 0.216 seconds, Fetched 1 row(s)
```

sparkui 
![image](https://github.com/oap-project/gluten/assets/41908930/3901a045-dce6-4126-83da-f4c0f13692e0)

### Spark version

Spark-3.3.x

### Spark configurations

spark-sql 
--conf spark.plugins=io.glutenproject.GlutenPlugin 
--conf spark.shuffle.manager=org.apache.spark.shuffle.sort.ColumnarShuffleManager 
--conf spark.memory.offHeap.enabled=true 
--conf spark.memory.offHeap.size=2G

**Comment by zhouyuan** [comment]
@rhh777 thanks for reporting, you are correct, I remember Velox did a big refactor on the compression support in some stage, and during that stage it only snappy and gzip are supported - @marin-ma can confirm 
will update the document 

thanks, -yuan

**Comment by marin-ma** [comment]
@rhh777 @zhouyuan Thanks. I checked Velox latest code, and all codecs are supported. We can remove this section. https://github.com/oap-project/gluten/blob/main/docs/velox-backend-limitations.md#exception-caused-by-file-compression-codec
