### ISSUE TITLE
[VL] Build on Mac may trigger 'command not found: nproc'

### ISSUE THREAD

**Issue by zdx19981006** [oap-project/gluten#4636]
### Problem description

this is a line in \builddeps-veloxbe.sh'
`NUM_THREADS=${NUM_THREADS:-$(nproc --ignore=2)}`
However, MacOS system do not have command ‘nproc’

### System information

Velox System Info v0.0.2
Commit: b127dfbb4d0c350c6fd729a8de4b6fa4e7c00bc8
CMake Version: 3.28.2
System: Darwin-22.3.0
Arch: x86_64
C++ Compiler: /Library/Developer/CommandLineTools/usr/bin/c++
C++ Compiler Version: 14.0.3.14030022
C Compiler: /Library/Developer/CommandLineTools/usr/bin/cc
C Compiler Version: 14.0.3.14030022
CMake Prefix Path: /Library/Developer/CommandLineTools/SDKs/MacOSX13.3.sdk/usr;/usr/local;/usr;/;/opt/homebrew/Cellar/cmake/3.28.2;/usr/local;/usr/X11R6;/usr/pkg;/opt;/sw;/opt/local

**Comment by ulysses-you** [comment]
does it work `brew install coreutils` ?
