### ISSUE TITLE
Debug build with vcpkg enabled fails to run

### ISSUE THREAD

**Issue by ayushi-agarwal** [oap-project/gluten#4694]
### Problem description

Built gluten in debug mode with vcpkg enabled.
cmake -DCMAKE_BUILD_TYPE=Debug -DBUILD_VELOX_BACKEND=ON -DENABLE_ABFS=ON -DBUILD_JEMALLOC=ON -DVELOX_HOME=/home/workspace/Velox -DARROW_HOME=/home/workspace/Velox/_build/release/third_party/arrow_ep .. && make -j

Any UT run fails with this error message:
/tmp/gluten-b80df343-1127-4ff0-abdd-40c452a27471/jni/2130db13-0e8c-4057-b08c-7c42b816eb81/gluten-6157225837186380411/libgluten.so: undefined symbol: _ZN6google10LogMessageC1EPKci
It works fine with normal release build.

### System information

Ubuntu 22.04

**Comment by mskapilks** [comment]
![image](https://github.com/oap-project/gluten/assets/106726387/50d0d0e0-cf57-46a9-b497-d0a5521230e4)

Adding `google::glog` during linking to `cpp/core/CMakeLists.txt` does make this error go away

**Comment by PHILO-HE** [comment]
> ![image](https://private-user-images.githubusercontent.com/106726387/305074672-50d0d0e0-cf57-46a9-b497-d0a5521230e4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDgwMDMyNTIsIm5iZiI6MTcwODAwMjk1MiwicGF0aCI6Ii8xMDY3MjYzODcvMzA1MDc0NjcyLTUwZDBkMGUwLWNmNTctNDZhOS1iNDk3LWQwYTU1MjEyMzBlNC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMjE1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDIxNVQxMzE1NTJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1jZmVlMTJjY2I2MDg4YTMwMjIyZWRmNzQ1NWIzOGVhZGFjMGVlNjlmMTZmMTgwM2RmMTQ5M2EyNDg0ZWM0MDY4JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.tXANzh4KPNqYxBRXi8-0OIrqll87GzWujUKqu98RFGo)
> 
> Adding `google::glog` during linking to `cpp/core/CMakeLists.txt` does make this error go away

Hi @ayushi-agarwal, we have included this in the main branch since this commit: https://github.com/oap-project/gluten/commit/4ae93d1f8731b0ebea704f6fda69b511e510abf3.

**Comment by ayushi-agarwal** [comment]
Thanks @PHILO-HE. Marking it as resolved.
