### ISSUE TITLE
[VL] Wrong preceding/following convert in window function node 

### ISSUE THREAD

**Issue by WangGuangxin** [oap-project/gluten#4789]
### Backend

VL (Velox)

### Bug description

The convert logic in. WindowFuncitonNode.java  make the assumption that the lower bound of a row/range frame are always `preceding offset`, and the upper bound are always `following offset`,  which is not the case.

https://github.com/oap-project/gluten/blob/6acd1b367a669bcca8af3708c00328cc3e707d2a/gluten-core/src/main/java/io/glutenproject/substrait/expression/WindowFunctionNode.java#L80

For example, following case is also a valid row frame.
```
select max(l_suppkey) over  (partition by l_suppkey order by l_orderkey rows between 2 preceding and 1 preceding) from lineitem
```

In fact, the spark row frame will convert preceding offset A to -A, so that the lower and upper bound params in `SpecifiedWindowFrame` are always **following offset**. 

Since Velox requires the input offset must be positive, so we just need to convert negative following offset to preceding, and vice versa.

### Spark version

None

**Comment by PHILO-HE** [comment]
Assume fully fixed. Thanks @WangGuangxin!
