### ISSUE TITLE
gluten jar doesn't include libhdfs3 dependency

### ISSUE THREAD

**Issue by theosib-amazon** [oap-project/gluten#483]
Evidently a recent PR has made gluten unconditionally depend on hdfs3, but the corresponding .so doesn't get included in the gluten jar, and there's no standard apt package for it in Ubuntu. So when I move the gluten jar to another machine, it has a dynamic linking failure.

```
Exception in thread "main" java.lang.UnsatisfiedLinkError: /tmp/spark_columnar_plugin_792525253487158829/libvelox.so: libhdfs3.so.1: cannot open shared object file: No such file or directory                                                                                                        
```

**Comment by FelixYBW** [comment]
Yes, we plan to add the .so built by gluten to jar only. Currently they are libprotobuf and libhdfs3. All other dependency libraries for velox, libhdfs, libarrow, etc. will be added to the deployment script to install manually. 

The dependency libraries of libhdfs3 is mentioned here:
https://github.com/oap-project/gluten/blob/main/docs/Velox.md#hdfs-support

**Comment by theosib-amazon** [comment]
Yeah. I had to manually add libprotobuf and libhdfs3 to /lib on the cluster nodes.

**Comment by FelixYBW** [comment]
@zhejiangxiaomai is adding them to jar.

**Comment by theosib-amazon** [comment]
libgsasl.so.7 is also missing.

**Comment by FelixYBW** [comment]
thank you, will add it to readme.

**Comment by zhouyuan** [comment]
@theosib-amazon 
we noted this in the [doc](https://github.com/oap-project/gluten/blob/main/docs/Velox.md#hdfs-support), the `libgsasl7-dev` should contain this lib

https://packages.ubuntu.com/focal/libgsasl7-dev
