### ISSUE TITLE
Worker node throws exception trying to use protobuf

### ISSUE THREAD

**Issue by theosib-amazon** [oap-project/gluten#484]
From what I can tell, version 3.21.9 of protobuf should be acceptable for Gluten. In the jars folder, I have "protobuf-java-3.21.9.jar", and in /lib, I have this:

libprotobuf.so.32.0.4
libprotobuf.so.32 -> libprotobuf.so.32.0.4
libprotobuf.so -> libprotobuf.so.32.0.4

But when I look at the log for the worker node, I see this exception thrown:

```
...
22/10/27 20:00:03 INFO JniLibLoader: Successfully loaded library libarrow.so.1000.0.0
22/10/27 20:00:03 INFO JniLibLoader: Trying to load library libgandiva.so.1000.0.0
22/10/27 20:00:03 INFO JniLibLoader: Library /tmp/spark_columnar_plugin_5688917933388226952/libgandiva.so.1000.0.0 has been loaded using path-loading method
22/10/27 20:00:03 INFO JniLibLoader: Library /tmp/spark_columnar_plugin_5688917933388226952/libgandiva.so.1000.0.0 has been loaded
22/10/27 20:00:03 INFO JniLibLoader: Symbolic link /tmp/spark_columnar_plugin_5688917933388226952/libgandiva.so.1000 created for library /tmp/spark_columnar_plugin_5688917933388226952/libgandiva.so.1000.0.0
22/10/27 20:00:03 INFO JniLibLoader: Successfully loaded library libgandiva.so.1000.0.0
22/10/27 20:00:03 INFO JniLibLoader: Trying to load library libspark_columnar_jni.so
22/10/27 20:00:03 INFO JniLibLoader: Library /tmp/spark_columnar_plugin_5688917933388226952/libspark_columnar_jni.so has been loaded using path-loading method
22/10/27 20:00:03 INFO JniLibLoader: Library /tmp/spark_columnar_plugin_5688917933388226952/libspark_columnar_jni.so has been loaded
22/10/27 20:00:03 INFO JniLibLoader: Successfully loaded library libspark_columnar_jni.so
22/10/27 20:00:04 INFO JniLibLoader: Trying to load library libvelox.so
22/10/27 20:00:04 INFO JniLibLoader: Library /tmp/spark_columnar_plugin_5688917933388226952/libvelox.so has been loaded using path-loading method
22/10/27 20:00:04 INFO JniLibLoader: Library /tmp/spark_columnar_plugin_5688917933388226952/libvelox.so has been loaded
22/10/27 20:00:04 INFO JniLibLoader: Successfully loaded library libvelox.so
22/10/27 20:00:04 INFO JniResourceHelper: Trying to extract headers to work directory /tmp/spark_columnar_plugin_5688917933388226952
22/10/27 20:00:04 INFO JniResourceHelper: Successfully extracted headers to work directory /tmp/spark_columnar_plugin_5688917933388226952
22/10/27 20:00:04 ERROR Inbox: An error happened while processing message in the inbox for Executor
java.lang.NoSuchMethodError: com.google.protobuf.Descriptors$FileDescriptor.internalBuildGeneratedFileFrom([Ljava/lang/String;[Lcom/google/protobuf/Descriptors$FileDescriptor;)Lcom/google/protobuf/Descriptors$FileDescriptor;
        at com.google.protobuf.AnyProto.<clinit>(AnyProto.java:39)
        at io.substrait.proto.Algebra.<clinit>(Algebra.java:915)
...
```

**Comment by theosib-amazon** [comment]
Evidently there was a jars/protobuf-java-2.5.0.jar that came with Spark. I had to delete that, and the missing exception went away. However, I have a new problem:

```
E1027 20:16:39.768878 97886 Exceptions.h:68] Line: ../../velox/common/file/FileSystems.cpp:60, Function:getFileSystem, Expression:  No registered file system matched with filename 's3a://theosib-v3-tpcds-hive/warehouse/theosib_tpcds_3000_hive/data/date_dim/part-00000-341e6443-b5cb-4456-91e4-eef70d0a2aaf-c000.snappy.parquet', Source: RUNTIME, ErrorCode: INVALID_STATE
22/10/27 20:16:39 ERROR Executor: Exception in task 0.1 in stage 7.0 (TID 2301)
java.lang.RuntimeException: Exception: VeloxRuntimeError
Error Source: RUNTIME
Error Code: INVALID_STATE
Reason: No registered file system matched with filename 's3a://theosib-v3-tpcds-hive/warehouse/theosib_tpcds_3000_hive/data/date_dim/part-00000-341e6443-b5cb-4456-91e4-eef70d0a2aaf-c000.snappy.parquet'
Retriable: False
Function: getFileSystem
File: ../../velox/common/file/FileSystems.cpp
Line: 60
Stack trace:
# 0
[cut]
# 16

        at io.glutenproject.vectorized.ArrowOutIterator.nativeHasNext(Native Method)
        at io.glutenproject.vectorized.ArrowOutIterator.hasNextInternal(ArrowOutIterator.java:45)
        at io.glutenproject.vectorized.GeneralOutIterator.hasNext(GeneralOutIterator.java:48)
```

Is Velox actually trying to access s3 directly? Why is it not falling back to Spark's Java code to do the I/O?

**Comment by FelixYBW** [comment]
We must offload whole table scan operator to Velox where Velox accesses S3 directly or fallback table scan operator to vanilla Spark. We can't offload the I/O only to Spark.

@zhouyuan We need to add a check that if the data storage is not supported then fallback table scan. We should only offload localfs and hdfs now.

**Comment by theosib-amazon** [comment]
Is there anything I can do to help? I don't really know the codebase well enough to just jump in there and work on it, but if you have any hints....

**Comment by FelixYBW** [comment]
Thank you, @theosib-amazon .

@zhouyuan @rui-mo Can you comment where to add the check?

**Comment by rui-mo** [comment]
> Thank you, @theosib-amazon .
> 
> @zhouyuan @rui-mo Can you comment where to add the check?

Hi Binwei, I think the data storage can be got through file path, but at below place, the whole stage transformer is already created.

[WholeStageTransformerExec](https://github.com/oap-project/gluten/blob/main/jvm/src/main/scala/io/glutenproject/execution/WholeStageTransformerExec.scala#L284-L285)
[VeloxIteratorApi](https://github.com/oap-project/gluten/blob/main/backends-velox/src/main/scala/io/glutenproject/backendsapi/velox/VeloxIteratorApi.scala#L72)

Is there any other way to know the data storage in advance?

**Comment by FelixYBW** [comment]
@zhouyuan do you know?

**Comment by zhouyuan** [comment]
@theosib-amazon this maybe a corner case we didn't covered yet. First, not all Spark job are offloaded - gluten generally only touch the physical plans due to [ColumnarAPI framework limit](https://issues.apache.org/jira/browse/SPARK-27396) and later execution part.
```
val df = spark.read.parquet("s3a://tpch/part-00000-b7eace05-f062-4f83-863f-6df6c7446980-c000.snappy.parquet")
val lineitem=df.createTempView("lineitem")
```
These two jobs are actually running with vanilla Spark, and in your case Spark is configured to work with S3, so it didn't do the fall back and worked(as it should)
in more details, the data frame will be convert to LogicalRelation first, the s3a IO is implemented in Hadoop S3a filesystem thus is actually "transparent" for Spark
```
spark.sql("select l_orderkey from lineitem").show
```
In this step, Spark will try to parse the sql, generate the logical plan, then to physicals plans, then gluten will convert to columnar plans to worker will try to execute those plans.
during the plan replacement Gluten could do the check and decided if it's OK to continue offloading or should fallback to vanilla Spark. 
I think the `scan` param should contain the filesystem schema like `s3a://` and we could try to do a check there to decided to do the transform or not
https://github.com/oap-project/gluten/blob/main/jvm/src/main/scala/io/glutenproject/extension/columnar/TransformHintRule.scala#L133-L135

**Comment by FelixYBW** [comment]
there are many other sources like minio we don't support. we need to fallback to vanilla spark on these data sources.

**Comment by theosib-amazon** [comment]
Initially, I tried running queries where I did this for each TPC-DS table:

```
val df = sqlContext.read.parquet("s3a://theosib-v3-tpcds-hive/warehouse/theosib_tpcds_3000_hive/data/household_demographics")
df.registerTempTable("household_demographics")
```

But this would always run out of memory. If I did it for all tables, it would run out of memory right away. If I did it for only the tables I needed, it would run out of memory later.

So I switched to rewriting the queries by prepending a with clause like this, and it worked a lot better:

```
with ${t} as (select * from parquet.`${s3RootPath}${t}`)
```

Could this be a corner case you hadn't accounted for?

**Comment by FelixYBW** [comment]
Is it running on Gluten? @zhouyuan is still working on the S3 PR. Did you use his PR?

**Comment by FelixYBW** [comment]
> Is there anything I can do to help? I don't really know the codebase well enough to just jump in there and work on it, but if you have any hints....

Fallback PR submitted by @zhouyuan 
https://github.com/oap-project/gluten/pull/499

**Comment by estoianovici** [comment]
I'm also trying to get this to work. Using the linked PR gets things moving a bit, but runs into the crash below.
[hs_err_pid150447.log](https://github.com/oap-project/gluten/files/9954095/hs_err_pid150447.log)

It looks like the cluster is still doing some work, but reading the query never completes. I'm running "select count(*) from store_returns" which completes fairly quick (seconds) with vanilla spark, but is still doing some work after 20 minutes with gluten + velox + s3.

**Comment by FelixYBW** [comment]
@akashsha1 Let's see if you will meet the same issue

**Comment by estoianovici** [comment]
this is fixed by https://github.com/oap-project/gluten/pull/491, right? I think it can be closed
