### ISSUE TITLE
[CH] The result order is reversed for `count` and `count distinct`

### ISSUE THREAD

**Issue by KevinyhZou** [oap-project/gluten#4853]
### Backend

CH (ClickHouse)

### Bug description

Test on gluten with clickhouse backend, the test table `test_tbl(id bigint, name string, sex string) stored as parquet`;  the test query sql `select day, count(distinct if(sex = 'x', id, null)) as uv, count(if(sex = 'x', id, null)) as pv from test_tbl where day = '2024-03-05' and id < 57 group by day `

and we get result below
![image](https://github.com/oap-project/gluten/assets/37431499/ffba032e-f599-4e7b-96d0-647dea3b83db)

and the correct result should be uv = 12 pv = 26, which the query result is reversed.

### Spark version

Spark-3.3.x

**Comment by liujiayi771** [comment]
@KevinyhZou I will take a look.

**Comment by liujiayi771** [comment]
I can reproduce this issue, I will fix it as soon as possible, thanks.

**Comment by KevinyhZou** [comment]
ok

**Comment by liujiayi771** [comment]
But the original code coincidentally obtained the correct result in this place. The `allAggregateResultAttributes` do not include Alias, so it's impossible to distinguish whether their order is consistent.

<img width="594" alt="image" src="https://github.com/oap-project/gluten/assets/13622031/e3669d98-5f75-4e2e-8b9f-165666dfb751">

**Comment by liujiayi771** [comment]
https://github.com/oap-project/gluten/pull/4726
