### ISSUE TITLE
Celeborn 0.3.0 is not found

### ISSUE THREAD

**Issue by ulysses-you** [oap-project/gluten#4860]
### Backend

CH (ClickHouse)

### Bug description

The clickhouse CI failed
```
09:03:42  + wget https://dlcdn.apache.org/incubator/celeborn/celeborn-0.3.0-incubating/apache-celeborn-0.3.0-incubating-bin.tgz
09:03:42  --2024-03-06 01:03:42--  https://dlcdn.apache.org/incubator/celeborn/celeborn-0.3.0-incubating/apache-celeborn-0.3.0-incubating-bin.tgz
09:03:42  Resolving dlcdn.apache.org (dlcdn.apache.org)... 151.101.2.132, 2a04:4e42::644
09:03:42  Connecting to dlcdn.apache.org (dlcdn.apache.org)|151.101.2.132|:443... connected.
09:03:42  HTTP request sent, awaiting response... 404 Not Found
09:03:42  2024-03-06 01:03:42 ERROR 404: Not Found.
```

### Spark version

None

**Comment by ulysses-you** [comment]
cc @zzcclp @kerwin-zk

**Comment by PHILO-HE** [comment]
Also note this issue. The link is not available since last night. We may need to replace 0.3.0 with 0.3.2 in the link. Same for CH CI.

https://github.com/oap-project/gluten/pull/4852/files#diff-92077173e6a535009e50974639976b3c49d45cfb05141bac9d291fc13bb06a8aR439

**Comment by kerwin-zk** [comment]
@ulysses-you @PHILO-HE  I'll handle it.

**Comment by kerwin-zk** [comment]
> Also note this issue. The link is not available since last night. We may need to replace 0.3.0 with 0.3.2 in the link. Same for CH CI.
> 
> https://github.com/oap-project/gluten/pull/4852/files#diff-92077173e6a535009e50974639976b3c49d45cfb05141bac9d291fc13bb06a8aR439

@PHILO-HE  Only need to replace the link of 0.3.0. 0.3.2 cannot be upgraded directly. Some APIs need to be adapted.

**Comment by PHILO-HE** [comment]
> > Also note this issue. The link is not available since last night. We may need to replace 0.3.0 with 0.3.2 in the link. Same for CH CI.
> > https://github.com/oap-project/gluten/pull/4852/files#diff-92077173e6a535009e50974639976b3c49d45cfb05141bac9d291fc13bb06a8aR439
> 
> @PHILO-HE Only need to replace the link of 0.3.0. 0.3.2 cannot be upgraded directly. Some APIs need to be adapted.

@kerwin-zk, could you please provide us a stable link to download 0.3.0? Thanks!
