### ISSUE TITLE
[VL] spark.read.csv("/tmp/test.csv") throws Exception

### ISSUE THREAD

**Issue by xumingming** [oap-project/gluten#5044]
### Backend

VL (Velox)

### Bug description

```scala
scala> var df = spark.read.csv("/tmp/test.csv");
E20240320 13:21:15.767925 16464018 Exceptions.h:69] Line: /path-to-gluten/ep/build-velox/build/velox_ep/velox/exec/Task.cpp:1811, Function:terminate, Expression:  Cancelled, Source: RUNTIME, ErrorCode: INVALID_STATE
df: org.apache.spark.sql.DataFrame = [_c0: string, _c1: string ... 1 more field]
```

### Spark version

Spark-3.2.x

### System information

Velox System Info v0.0.2
Commit: 57d36593a8f936814f0a8e2f75488c97225d8bdb
CMake Version: 3.24.4
System: Darwin-21.6.0
Arch: arm64
C++ Compiler: /Library/Developer/CommandLineTools/usr/bin/c++
C++ Compiler Version: 14.0.0.14000029
C Compiler: /Library/Developer/CommandLineTools/usr/bin/cc
C Compiler Version: 14.0.0.14000029
CMake Prefix Path: /Library/Developer/CommandLineTools/SDKs/MacOSX13.1.sdk/usr;/opt/homebrew;/usr/local;/usr;/;/usr/local/cmake-3.24.4/CMake.app/Contents;/usr/local;/usr/X11R6;/usr/pkg;/opt;/sw;/opt/local

**Comment by zhztheplayer** [comment]
Was the query result correct?

Sometimes this log doesn't mean there is anything wrong. If it's the case we can find a way to suppress that log from Velox.

**Comment by PHILO-HE** [comment]
Hi @xumingming, the exception looks irrelevant. Currently, Gluten doesn't support CSV format. So reading CSV will fall back to vanilla Spark. You can check the fallback summary in `Gluten SQL / DataFrame` tab of history server UI.

<img width="554" alt="image" src="https://github.com/apache/incubator-gluten/assets/13806761/9b828b7d-7611-4c77-b4c1-f4e7e054ff76">

**Comment by PHILO-HE** [comment]
> @PHILO-HE Thanks for the information! I tried with parquet data(nation table in TPCH), the details are the following:
> 
> ```
> == Fallback Summary ==
> (4) Project: Not supported to map spark function name to substrait function name: toprettystring(n_nationkey#23, Some(Asia/Shanghai)), class name: ToPrettyString.
> (5) CollectLimit: Gluten does not touch it or does not support it
> 
> == Physical Plan ==
> CollectLimit (5)
> +- Project (4)
>    +- VeloxColumnarToRowExec (3)
>       +- ^ Scan parquet  (1)
> ```
> 
> Is the fallback for `Project` expected?

Yes, because `toprettystring` is not supported in Gluten.
