### ISSUE TITLE
Build Velox from its folder

### ISSUE THREAD

**Issue by FelixYBW** [oap-project/gluten#517]
**Is your feature request related to a problem or challenge? Please describe what you are trying to do.**

Currently we can clone Velox into a seperate folder, but we must specify velox_home to MVN and let mvn to build Velox. We can't build Velox for Gluten seperately. It's inconvenient. 

**Describe the solution you'd like**
It's ideally if we can clone Velox to a seperate folder, then run some script to automatically patch the setup script, use the correct flags for Gluten to build the Velox binary there. We can modify and debug velox from the folder, pass the UT, then use mvn to pack it into jar.

**Comment by zhejiangxiaomai** [comment]
https://github.com/oap-project/gluten/pull/568  Can solve this Issue.  
The  command is :
#Just recompile velox without compiling third-party libraries

```shell
mvn clean package -Pspark-3.2 -DskipTests -Dcheckstyle.skip -Pbackends-velox \
                  -Dbuild_cpp=ON \
                  -Dbuild_velox_backend=ON \
                  -Dvelox_home=${VELOX_HOME} \
                  -Dbuild_arrow=OFF \
                  -Dbuild_protobuf=OFF \
                  -Dbuild_folly=OFF \
                  -Dcompile_velox=ON \
                  -Dbuild_type=release 
```

And will make further optimization in future.
