### ISSUE TITLE
archives for Spark patch versions become unavailable on new releases affecting shims versioning

### ISSUE THREAD

**Issue by estoianovici** [oap-project/gluten#527]
SparkShimProvider.scala creates a full version of the SparkShimDescriptor (e.g. 3.3.0) but spark doesn't keep these versions available (e.g. 3.3.0 is not available for download anymore, only 3.3.1 and 3.3.2, see https://spark.apache.org/downloads.html).

Consider changing the versioning to only reference Major.Minor versioning (i.e. 3.3 instead of 3.3.0)

**Comment by FelixYBW** [comment]
@jinchengchenghh  can we do this in shim layer?

**Comment by jinchengchenghh** [comment]
Yes, I think we can. But in the pom.xml, we specify spark.version as 3.3.0, and do some check, if user uses it for other version, it may raise some unexpected error

**Comment by jinchengchenghh** [comment]
Our team discuss about this issue,  and decide to always support the newest spark minor version. https://github.com/oap-project/gluten/pull/534

**Comment by jinchengchenghh** [comment]
For the stable reason,  we will not support all the spark minor version such as 3.3.x, does this solve your problem?

**Comment by estoianovici** [comment]
Yes, the patch in the pull request would solve the issue.

Thanks!
