### ISSUE TITLE
Jackson databind missing from gluten jar

### ISSUE THREAD

**Issue by theosib-amazon** [oap-project/gluten#538]
I'm attempting to use the S3 support from https://github.com/oap-project/gluten/pull/491, but I find that a module is missing. The steps to reproduce are simple. Start up spark-shell with gluten configured, and do this:

```
scala> val df = spark.read.parquet("s3a://theosib-v3-tpcds-hive/warehouse/theosib_tpcds_3000_hive/data/call_center")
22/11/09 19:22:30 WARN MetricsConfig: Cannot locate configuration: tried hadoop-metrics2-s3a-file-system.properties,hadoop-metrics2.properties
com.fasterxml.jackson.databind.JsonMappingException: Scala module 2.12.3 requires Jackson Databind version >= 2.12.0 and < 2.13.0
  at com.fasterxml.jackson.module.scala.JacksonModule.setupModule(JacksonModule.scala:61)
  at com.fasterxml.jackson.module.scala.JacksonModule.setupModule$(JacksonModule.scala:46)
  at com.fasterxml.jackson.module.scala.DefaultScalaModule.setupModule(DefaultScalaModule.scala:17)
...
```

**Comment by theosib-amazon** [comment]
Well, I dropped jackson-databind-2.12.3.jar into the jars directory, but that didn't help. No idea what's going on here.

**Comment by theosib-amazon** [comment]
This seems related:
https://stackoverflow.com/questions/67769492/scala-module-2-12-3-requires-jackson-databind-version-2-12-0-and-2-13-0-but

**Comment by theosib-amazon** [comment]
These are the jars I have that came with Spark, other than the databind module I just added. Is one of these the wrong version?

```
.2/jars$ ls -lrt *jackson*
parquet-jackson-1.12.2.jar
json4s-jackson_2.12-3.7.0-M11.jar
jackson-module-scala_2.12-2.12.3.jar
jackson-mapper-asl-1.9.13.jar
jackson-datatype-jsr310-2.11.2.jar
jackson-dataformat-yaml-2.12.3.jar
jackson-core-asl-1.9.13.jar
jackson-core-2.12.3.jar
jackson-annotations-2.12.3.jar
jackson-databind-2.12.3.jar
```

**Comment by theosib-amazon** [comment]
Something in gluten-spark3.2_2.12-1.0.0-SNAPSHOT-jar-with-dependencies.jar is causing this. If I leave that jar in the jars directory but disable gluten from spark-defaults.conf, I still get the error. I have to remove the jar from the classpath entirely, and then I don't get this exception.

**Comment by zhouyuan** [comment]
@theosib-amazon 
hi, the issue should be fixed in https://github.com/oap-project/gluten/pull/532, I'll rebase on #491  and it should be fixed

**Comment by theosib-amazon** [comment]
Thanks! Does this mean I should check out 532 or 491?

**Comment by zhouyuan** [comment]
> Thanks! Does this mean I should check out 532 or 491?

#491 is rebased and included the fix already 

-yuan
