### ISSUE TITLE
compiler failture due to boots lib version

### ISSUE THREAD

**Issue by qingyuan18** [oap-project/gluten#570]
[ 46%] Building CXX object src/CMakeFiles/spark_columnar_jni.dir/proto/substrait/capabilities.pb.cc.o
In file included from /opt/gluten/gluten/cpp/src/operators/c2r/arrow_columnar_to_row_converter.h:20:0,
                 from /opt/gluten/gluten/cpp/src/compute/exec_backend.h:28,
                 from /opt/gluten/gluten/cpp/src/jni/jni_wrapper.cc:33:
/opt/gluten/gluten/cpp/src/operators/c2r/columnar_to_row_base.h:28:10: fatal error: boost/align.hpp: No such file or directory
 #include <boost/align.hpp>
          ^~~~~~~~~~~~~~~~~
compilation terminated.

mvn package -Dcheckstyle.skip=true -DskipTests -Dencoding=utf-8 -Pbackends-gazelle -DskipTests -Dbuild_arrow=ON

can anyone tell me which version of boost this gluten version needs?  no documents infers these details

Thanks

**Comment by zhouyuan** [comment]
hi @qingyuan18 

thanks for reporting, 
boost 1.66+ is required in Velox.   
https://github.com/facebookincubator/velox/blob/main/CMakeLists.txt#L249
If you are testing on Ubuntu 20.04/22.04, please have a try with `apt install libboost-dev`

Will update the doc to add this. 

thanks, -yuan

**Comment by qingyuan18** [comment]
have you tried CentOs 7 ?  Got another compatibility error when compile folly which your gluten volex backend needs:
CMake Error at /usr/share/cmake/Modules/FindPackageHandleStandardArgs.cmake:146 (message):
  Could NOT find OpenSSL, try to set the path to OpenSSL root folder in the
  system variable OPENSSL_ROOT_DIR: Found unsuitable version "1.0.2k", but
  required is at least "1.1.1" (found /usr/lib64/libcrypto.so)
Call Stack (most recent call first):

I have already upgraded the openssl lib to 1.1 version:
[root@ip-172-31-40-213 _build]# openssl version
OpenSSL 1.1.1i  8 Dec 2020 (Library: OpenSSL 1.1.1g FIPS  21 Apr 2020)

also add my upgrade openssl lib path into cmake params not works:
cmake -DOPENSSL_ROOT_DIR=/opt/folly/folly/_build/openssl-1.1.1i  configure ..

there are so many native C/C++ lib gluten needs , better to have a clear requriment list for users to adapter into their own prod env

Thanks

**Comment by FelixYBW** [comment]
CentOS 7 isn't supported yet. We are working on CentOS 8 now.

**Comment by qingyuan18** [comment]
seems like CentOS can't use gluten right now, I fixed the folly compile manually , but can't install volex libs as it's only supporting Ubuntu , but our prod env all runs on CentOS7.x version, which is blocked here so far....

any roadmap for Centos especially 7.x onboarding for gluten with Velox backend?

**Comment by FelixYBW** [comment]
The main issue is the library versions.  Lower OS version like CentOS7 or ubuntu18 only have pre-build libraries with lower version as well. But gluten and Velox use higher version libraries. So to solve the issue we must build these dependency libraries during compile, instead of using system's. It needs much effort. We are identifying the libraries we should build now.

Another solution is to use conda env to build the velox and gluten, unfortunately, the libraries from conda-forge channel also have conflicts :( Velox community is trying to solve it now.

**Comment by qingyuan18** [comment]
hi teams
     I have successfully compiled&packaged gluten arrow-backend on CentOs7 :
    [root@ip-172-31-40-213 gluten]# find ./ -name gluten*.jar
./gluten-core/target/gluten-core-1.0.0-SNAPSHOT-tests.jar
./gluten-core/target/gluten-core-1.0.0-SNAPSHOT.jar
./gluten-core/target/gluten-core-1.0.0-SNAPSHOT-3.2.jar
./gluten-data/target/gluten-data-1.0.0-SNAPSHOT.jar
./gluten-data/target/gluten-data-1.0.0-SNAPSHOT-3.2.jar
./package/gazelle/spark32/target/gluten-spark3.2_2.12-1.0.0-SNAPSHOT-jar-with-dependencies.jar

not sure what's the volex backend module in gluten's arrow backends' profile ? 
<profile>
      <id>backends-gazelle</id>
      <activation>
        <activeByDefault>false</activeByDefault>
      </activation>
      <modules>
        <module>ep/build-arrow</module>
        <module>ep/build-velox</module>
        <module>gluten-data</module>
        _**<module>backends-velox</module>**_
        <module>backends-gazelle</module>
        <module>package/gazelle</module>
      </modules>

**Comment by FelixYBW** [comment]
The arrow backend only support table scan and parquet write. All other operators are fallbacked. We do have a CI for it but didn't test it by us for a while.

**Comment by qingyuan18** [comment]
Got it , Thanks

Closing this ticket as there is no other compile options can do so far
