### ISSUE TITLE
[compile bug] there is a compilation error cased by bridge.h

### ISSUE THREAD

**Issue by zuochunwei** [oap-project/gluten#615]
**Describe the bug**
There is a C++ compilation error on the Docker environment hosted by MacBook Pro.

**To Reproduce**

**Expected behavior**
can fix by specifying the location of file `bridge.h`

**Additional context**

**Comment by zhejiangxiaomai** [comment]
https://github.com/oap-project/gluten/pull/614 fixed this issue.
