### ISSUE TITLE
TPCDS query execution fails

### ISSUE THREAD

**Issue by RamaMalladiAWS** [oap-project/gluten#623]
SQL query on TPCDS data seems to be failing (looks like a silent crash). This is an issue on the latest mainline code. It was working on an earlier commit ID. Details below. Issue is reproducible on an Intel x86 machine.

- Generate TPCDS data (https://github.com/databricks/tpcds-kit).
- Build Gluten + Velox backend and execute an SQL query on the TPCDS data. Correct output would result in some rows from the table being printed on the console output. Incorrect in my case was just not printing anything!

Last good commit ID:
commit 8dff535e5d1e61adced9b73b8ace4409fa91f251
Author: LiuNeng <1398775315@qq.com>
Date:   Mon Nov 14 11:50:43 2022 +0800

Latest (bad) commit ID:
commit 8c516b75a2d79661017b3607172f375475369882 (HEAD -> main, origin/main, origin/HEAD)
Author: JiaKe <ke.a.jia@intel.com>
Date:   Mon Nov 28 08:51:37 2022 +0000

So, something between this "good" and "bad" commit IDs is causing the issue. I will try to triage too. Thanks.

**Comment by RamaMalladiAWS** [comment]
Found this to be the offending commit:

7df4b1ea8fdec6646225830b98abac0c974e17ed is the first bad commit
commit 7df4b1ea8fdec6646225830b98abac0c974e17ed
Author: Jin Chengcheng <chengcheng.jin@intel.com>
Date:   Tue Nov 22 13:46:39 2022 +0800

    [OPPRO-309] Change spark3.3 version to 3.3.1 (#534)

**Comment by RamaMalladiAWS** [comment]
So, is this just that I need to switch to Spark v3.3.1?

**Comment by jinchengchenghh** [comment]
Yes, now we only support spark3.3.1

**Comment by RamaMalladiAWS** [comment]
Thank you. This issue can be closed.
