### ISSUE TITLE
suggestions for compiling and installing 

### ISSUE THREAD

**Issue by zuochunwei** [oap-project/gluten#638]
**Is your feature request related to a problem or challenge? Please describe what you are trying to do.**

the compiling and installing are too slow.

if I get an error in the middle steps, I have to go back to the first step and redo step by step.

the network is not good for me, this makes it worse.

it's difficult for me to understand the detailed procedure of compiling and installing.

if I can't get the detail, I can't complete my job.

for example:
the gluten uses too many building tools, such as mvn、cmake、ccache...

I can not execute the bash script manually, because these scripts take so many arguments, I don't know how to pass the correct arguments.

making the user think is not a good way, the best compiling script is without arguments provided when execute, of course, the user can modify the variable in the script to change its behavior. 

**Describe the solution you'd like**
1. make download、build、install separate
2. provide a script to compile CPP or a specified directory, it's no need to provide any arguments
3. think more about easy usage

**Describe alternatives you've considered**

**Additional context**

**Comment by zhejiangxiaomai** [comment]
https://github.com/oap-project/gluten/pull/610 will fix this issue.

**Comment by zuochunwei** [comment]
> #610 will fix this issue.

well done, thank you very much!
