### ISSUE TITLE
Undefine symbol in libvelox.so

### ISSUE THREAD

**Issue by theosib-amazon** [oap-project/gluten#641]
Steps:
- unzip the Gluten jar into a directory
- run "ldd -r libvelox.so"

The last thing printed is this:

```
undefined symbol: _ZN8facebook5velox9functions24getElementToTopLevelRowsEiRKNS0_17SelectivityVectorEPKiS6_PKmPNS0_6memory10MemoryPoolE  (./libvelox.so)
```

This doesn't cause a crash or anything that I have observed, but it's something that might need to be corrected.

**Comment by FelixYBW** [comment]
confirmed from our side. @zhztheplayer is it a bug?

**Comment by zhztheplayer** [comment]
Seems to me that the symbol should be defined in libvelox_functions_util.a which is introduced in a recent patch https://github.com/oap-project/gluten/pull/518.Not sure if this is a bug and I'll help checking the issue then get back to you

**Comment by zhztheplayer** [comment]
Should be fixed by https://github.com/oap-project/gluten/issues/641
