### ISSUE TITLE
WholeStageTransformerSuite#logForFailedTest() swallows exceptions

### ISSUE THREAD

**Issue by zhztheplayer** [oap-project/gluten#676]
Scalatest reports exceptions after logForFailedTest() is called. Thus we now swallow all exceptions in WholeStageTransformerSuite which is sub-optimal.

It's easy to reproduce the issue by adding a test case that only includes a throw statement.

**Comment by zhztheplayer** [comment]
> Do we fallback or fails on such query?

Yes the suits can be failed. But failed silently with no error reported which makes debugging harder.

**Comment by jinchengchenghh** [comment]
Fixed already
