### ISSUE TITLE
setup_ubuntu is executed twice

### ISSUE THREAD

**Issue by zhouyuan** [oap-project/gluten#694]
**Describe the bug**
below script executed setup_ubuntu twice, looks like a typo
https://github.com/oap-project/gluten/blob/main/ep/build-velox/src/build_velox.sh#L143-L145

**To Reproduce**
run a full build with hdfs/s3 enabled.

**Expected behavior**
should only run once

**Additional context**
N/A

**Comment by FelixYBW** [comment]
Is this fixed?

**Comment by zhejiangxiaomai** [comment]
This issue will be fixed by https://github.com/oap-project/gluten/pull/701.
