### ISSUE TITLE
org.apache.arrow:arrow-vector:jar:10.0.0-SNAPSHOT was not found in 

### ISSUE THREAD

**Issue by Aitozi** [oap-project/gluten#718]
**Describe the bug**

When loading the maven project, IDE complains with 
> org.apache.arrow:arrow-vector:jar:10.0.0-SNAPSHOT was not found in https://repository.kyligence.io/repository/maven-public/ during a previous attempt.

I check the repository, the `org.apache.arrow:arrow-vector:jar:10.0.0` is there, can we update the dependency to 10.0.0 ?

**Comment by FelixYBW** [comment]
Are you build CK backend? CK doesn't need arrow

**Comment by FelixYBW** [comment]
@zhejiangxiaomai can you help?

**Comment by zhejiangxiaomai** [comment]
Would you compile gluten use one_step_veloxbackend.sh? 
```
cd /path_to_gluten
./tools/one_step_veloxbackend.sh
```

**Comment by jinchengchenghh** [comment]
It found the jar in the wrong repository. Maybe the IDE issue. Try Invalidate the cache. And we have upgraded arrow to 11.0.0-gluten. And remove CH repo. Please try the new version, thanks!

**Comment by jinchengchenghh** [comment]
Since it is stale, I will close it, you can reopen it if has new progress.
