### ISSUE TITLE
build from local velox repo doesn't work

### ISSUE THREAD

**Issue by puchengy** [oap-project/gluten#727]
**Describe the bug**
Following the instructions at https://github.com/oap-project/gluten/blob/main/docs/Velox.md#21-specify-velox-home-directory. Saw below issue
```
-- Copy Arrow headers from /home/{mask}/code/gluten/ep/build-arrow/build/arrow_install/include to /home/{mask}/code/gluten/cpp/build/releases/include
CMake Error at CMake/ConfigArrow.cmake:85 (file):
  file COPY cannot find
  "/home/{mask}/code/gluten/ep/build-arrow/build/arrow_install/include/parquet":
  No such file or directory.
Call Stack (most recent call first):
  CMakeLists.txt:64 (include)
```

**To Reproduce**
1. download velox and gluten
2. same steps as described at https://github.com/oap-project/gluten/blob/main/docs/Velox.md#21-specify-velox-home-directory

**Expected behavior**
Success at compile stage.

**Additional context**
None

**Comment by zhejiangxiaomai** [comment]
Can you provide specific steps and I will reproduce it？

**Comment by puchengy** [comment]
@zhejiangxiaomai Thanks for checking, it is same as the steps mentioned in the document:

```
step 1:
`git clone https://github.com/oap-project/gluten.git`

step 2:
`git clone --recursive https://github.com/oap-project/velox.git`

step 3: recompile velox, set velox_home in build_velox.sh
cd /path_to_gluten/ep/build_velox/src
./build_velox.sh  --velox_home=/your_specified_velox_path

step 4: recompile gluten cpp folder, set velox_home in build_velox.sh
cd /path_to_gluten/cpp
./compile.sh --velox_home=/your_specified_velox_path
···

**Comment by zhejiangxiaomai** [comment]
Maybe you forget arrow install step？

## fetch arrow and compile
cd /path_to_gluten/ep/build-arrow/src/
./get_arrow.sh
./build_arrow_for_velox.sh

**Comment by puchengy** [comment]
@zhejiangxiaomai Thank you, but I still saw the same error
```
-- Copy Arrow headers from /home/{mask}/code/gluten/ep/build-arrow/build/arrow_install/include to /home/{mask}/code/gluten/cpp/build/releases/include
CMake Error at CMake/ConfigArrow.cmake:85 (file):
  file COPY cannot find
  "/home/{mask}/code/gluten/ep/build-arrow/build/arrow_install/include/parquet":
  No such file or directory.
Call Stack (most recent call first):
  CMakeLists.txt:64 (include)
```
steps
```
step 1:
git clone https://github.com/oap-project/gluten.git

step 2:
git clone --recursive https://github.com/oap-project/velox.git

step 3:
cd /path_to_gluten/ep/build-arrow/src/
./get_arrow.sh
./build_arrow_for_velox.sh

step 4: recompile velox, set velox_home in build_velox.sh
cd /path_to_gluten/ep/build_velox/src
./build_velox.sh  --velox_home=/your_specified_velox_path

step 5: recompile gluten cpp folder, set velox_home in build_velox.sh
cd /path_to_gluten/cpp
./compile.sh --velox_home=/your_specified_velox_path
```

**Comment by zhejiangxiaomai** [comment]
I will try to reproduce this problem as soon as possible.

**Comment by puchengy** [comment]
@zhejiangxiaomai Thanks a lot!

**Comment by zhejiangxiaomai** [comment]
use "./compile.sh --velox_home=/your_specified_velox_path --build_velox_backend=ON"  can fix your problem.

**Comment by puchengy** [comment]
@zhejiangxiaomai It did fixe the problem, thank you!

**Comment by puchengy** [comment]
@zhejiangxiaomai Hi, I built gluten with facebook's velox repo and failed with 
```
CMake Error at velox/CMakeLists.txt:58 (message):
  Velox library not exists:
  /home/{mask}/code/velox/_build/release/velox/substrait/libvelox_substrait_plan_converter.a
Call Stack (most recent call first):
  velox/CMakeLists.txt:75 (add_velox_dependency)
  velox/CMakeLists.txt:195 (add_velox_dependencies)
```

Do I have to build with oap-project/velox? What's the difference between the two?

**Comment by zhejiangxiaomai** [comment]
https://github.com/oap-project/velox/blob/main/velox/CMakeLists.txt#L73-L76 can fix your problem. In fact we do not try use fb/velox. lots of PR not upstream to fb/velox.

**Comment by puchengy** [comment]
@zhejiangxiaomai got it, do you have a regular rebase to the latest fb/velox? I plan to contribute some code to fb/velox, just want to make sure they will be in in the oap/velox sometime soon.

**Comment by zhejiangxiaomai** [comment]
In fact, I will rebase to the latest fb/velox weekly.

**Comment by puchengy** [comment]
@zhejiangxiaomai got it, that is good enough. Thanks
