### ISSUE TITLE
Minimal runtime apt packages needed for running Gluten with Velox

### ISSUE THREAD

**Issue by j-buczak** [oap-project/gluten#748]
**Is your feature request related to a problem or challenge? Please describe what you are trying to do.**
I am trying to build minimal Dockerfile for running Spark with Gluten on Velox backend with data stored on s3 in parquet format with metadata stored in Hive-metastore 

**Describe the solution you'd like**
In `Velox.md` there is a statement that jar file and additional configuration is needed to run Gluten. However while testing Gluten complains about missing .so files. I know that they are needed, but since we are trying to make Docker image as small as possible there would be nice to have a list with minimal runtime packages. 

**Describe alternatives you've considered**
Install the same set as during building.

**Comment by jinchengchenghh** [comment]
Can you follow this document https://github.com/oap-project/gluten/blob/main/docs/developers/docker_ubuntu22.04.md to set up your docker?

**Comment by jinchengchenghh** [comment]
And this is the minimum library list to run the gluten https://github.com/oap-project/gluten/pull/1173/files
