### ISSUE TITLE
Velox does not install folly in centos8 by default, break compile in centos8.

### ISSUE THREAD

**Issue by Yohahaha** [oap-project/gluten#772]
**Describe the bug**
Velox remove install folly in centos [4f528](https://github.com/facebookincubator/velox/commit/4f5288032d0c5c6808e95108f728f0e5a70fba2f), when compile gluten, find_package(folly) will throw error.

**To Reproduce**
./tools/one_step_veloxbackend.sh or separate build velox then build gluten can reproduce.

**Expected behavior**

**Additional context**
Velox still install folly in setup_ubuntu.
So, if i execute `cd /path-to-gluten/ep/build-velox/build/velox_ep/_build/release/_deps/ & cmake --install folly-build`, everything would be ok.

What's community's options about this? I could submit a PR if needed.

**Comment by jinchengchenghh** [comment]
How about using resolve_dependency macro as velox does in [4f528](https://github.com/facebookincubator/velox/commit/4f5288032d0c5c6808e95108f728f0e5a70fba2f)? @FelixYBW

**Comment by Fiooodooor** [comment]
This just should be added to the centos8 deployment
```bash
(
  git clone https://github.com/facebook/folly &&
  cd folly &&
  git checkout $FB_OS_VERSION &&
  cmake_install -DBUILD_TESTS=OFF -DBUILD_SHARED_LIBS=ON
)
```

**Comment by FelixYBW** [comment]
@zhejiangxiaomai

**Comment by zhejiangxiaomai** [comment]
I already fix this issue here https://github.com/oap-project/gluten/pull/994/files#diff-e2b6a0ac0f3384d96902fbc545a697d0aa305c7ed711493df5e1bddf6c6d401b. we can close this isssue.
