### ISSUE TITLE
Pass needed hadoop conf from driver to executor

### ISSUE THREAD

**Issue by Yohahaha** [oap-project/gluten#788]
**Is your feature request related to a problem or challenge? Please describe what you are trying to do.**
(This section helps developers understand the context and *why* for this feature, in addition to  the *what*)

I'm confused when use Gluten with HDFS, cause set extra env variable `VELOX_HDFS` in a Hadoop cluster does not make sense.

**Describe the solution you'd like**
Running Spark app in Hadoop cluster should always read hadoop config file default eg, core-site.xml etc. so we could make `VELOX_HDFS` construct from this config files in most situation.

**Describe alternatives you've considered**

**Additional context**

**Comment by FelixYBW** [comment]
@zhouyuan A better solution is to load the config from hadoop's config files

**Comment by Yohahaha** [comment]
> @zhouyuan A better solution is to load the config from hadoop's config files

I think so, maybe we could do a lot refactor for passing config in future when needed.

This issue will be closed.
