### ISSUE TITLE
The compatibility issues between Velox and Spark

### ISSUE THREAD

**Issue by rui-mo** [oap-project/gluten#822]
**Is your feature request related to a problem or challenge? Please describe what you are trying to do.**

To solve the compatibility issues between Velox and Spark, there are some changes to Velox. We are tracking them here for future improvement.

| Uncompatibility  | Detailed Information |
| ------------- | ------------- |
| The handling for dot in file path | Disable tokenizing the path by dot: https://github.com/oap-project/velox/pull/109.  |
| Presto sql function substr | Fix the result mismatch for right expression: https://github.com/oap-project/velox/pull/107.  |
| Presto sql sum | Spark sum can overflow: https://github.com/oap-project/velox/pull/101.|
| Presto sql avg | Align partial avg results: https://github.com/oap-project/velox/pull/56. |
| Support more datetime pattern | Datetime like YY, YY-MM are valid: https://github.com/oap-project/velox/pull/94 |
| Presto sql corr | Align corr accuracy with Spark: https://github.com/oap-project/velox/pull/147. |

**Comment by rui-mo** [comment]
cc @jinchengchenghh

**Comment by FelixYBW** [comment]
To the functions has different implementation. Let's check if presto has different implementation or not. If presto has different result, we should copy the function to sparksql foder. If presto has the same result, we should modify directly from presto's one. We may check if Velox has a UT for our error case to quickly identify if Presto implements differently
