### ISSUE TITLE
Support named struct type

### ISSUE THREAD

**Issue by lgbo-ustc** [oap-project/gluten#853]
**Is your feature request related to a problem or challenge? Please describe what you are trying to do.**
(This section helps developers understand the context and *why* for this feature, in addition to  the *what*)

At present, all types in substrait are defined without names, which has insufficient ability to express a named struct type.

For example, we have the following query
```SQL
select s.a, s.b from ( select from_json(x, 'a int, b string') as s from t)
```

`from_json` generates a named struct , `{a:int, b string}`.  what we get in the substraint plan is
```
  {
                  "scalarFunction": {
                    "functionReference": 3,
                    "outputType": {
                      "string": {
                        "nullability": "NULLABILITY_NULLABLE"
                      }
                    },
                    "arguments": [{
                      "value": {
                        "scalarFunction": {
                          "outputType": {
                            "struct": {
                              "types": [{
                                "string": {
                                  "nullability": "NULLABILITY_NULLABLE"
                                }
                              }],
                              "nullability": "NULLABILITY_NULLABLE"
                            }
                          },
                          "arguments": [{
                            "value": {
                              "selection": {
                                "directReference": {
                                  "structField": {
                                  }
                                }
                              }
                            }
                          }]
                        }
                      }
                    }, {
                      "value": {
                        "literal": {
                          "string": "b"
                        }
                      }
                    }]
                  }
   }
```
`"functionReference": 3`  corresponds to spark function `GetStructField`, since the struct type returned from `from_json(x, 'a int, b string') ` doesn's have names for each field. `GetStructField` cannot access the struct field by name `b`.

Previously, we have a similar problem in https://github.com/oap-project/gluten/pull/765. In that case we can take advantage of `NamedStruct` to solve the problem.

 
**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by rui-mo** [comment]
Hi, I think we have supported selecting a subfield from struct in Gluten, and it is based on `StructField`.

Link: https://github.com/oap-project/gluten/blob/main/gluten-core/src/main/resources/substrait/proto/substrait/algebra.proto#L683-L688

**Comment by rui-mo** [comment]
A child index is needed for selection at: [SelectionNode](https://github.com/oap-project/gluten/blob/main/gluten-core/src/main/java/io/glutenproject/substrait/expression/SelectionNode.java#L33-L36).
