### ISSUE TITLE
Selective query execution

### ISSUE THREAD

**Issue by glipner** [oap-project/gluten#882]
Currently, when Gluten is loaded into Spark, it'll be used by default for all queries and DataFrame operations.
This features allows the programmer to selectively toggle Gluten on or off from within the Spark application.
This might be valuable, e.g. for cases when you want to slowly evaluate the impact of Gluten on an existing code base.

The implementation defaults to always enable, so that there is no impact on users who are not using it.

**Comment by FelixYBW** [comment]
close this since it's sloved
