### ISSUE TITLE
[CH] enhance trim function

### ISSUE THREAD

**Issue by zheniantoushipashi** [oap-project/gluten#934]
**Describe the bug**

The functions in clickhouse can only trim whitespace, and the syntax of 'trim([[LEADING|TRAILING|BOTH] trim_character FROM] input_string)' is parsed into replaceRegexpAll in ExpressionListParsers.cpp, the logic is completely different from spark trim, sparkTrim is not It is easy to abstract with the trim function, because trim comes from a template class of FunctionStringToString, which only accepts one parameter, so I added a sparkTrim function to the backend, and use different functions according to different parameters.

**To Reproduce**

GlutenStringExpressionsSuite  can  reproduce this

**Comment by taiyang-li** [comment]
closed by https://github.com/oap-project/gluten/pull/1562

**Comment by zzcclp** [comment]
fixed
