### ISSUE TITLE
Docker for gluten running on centos 8

### ISSUE THREAD

**Issue by jinhaichen** [oap-project/gluten#969]
Can gluten run on centos 8？ And if so,  is it possible to provide a docker image?

**Comment by FelixYBW** [comment]
@zhejiangxiaomai @weiting-chen  Is Centos8 script ready now? if so let's add it to readme.

**Comment by zhejiangxiaomai** [comment]
I will test gluten+velox on centos8 soon.  Velox already use Centos8 as a part of their own CI.

**Comment by zhejiangxiaomai** [comment]
Sorry for late reply. I create a pr https://github.com/oap-project/gluten/pull/994  to add readme for centos8. And fix folly not found problem.

**Comment by jinhaichen** [comment]
Centos8 is now running well.
