### ISSUE TITLE
Failed to build velox

### ISSUE THREAD

**Issue by sharkdtu** [oap-project/gluten#990]
I tried to build gluten-velox on my centos8 and got following errors

```
...
+ DEPENDENCY_DIR=/opt/gluten/ep/build-velox/build/velox_ep
+ DEPENDENCY_DIR=/opt/gluten/ep/build-velox/build/velox_ep
+ dnf_install epel-release dnf-plugins-core
+ dnf install -y -q --setopt=install_weak_deps=False epel-release dnf-plugins-core
+ dnf config-manager --set-enabled powertools
Error: No matching repo to modify: powertools.
```
---

We can remove "dnf config-manager --set-enabled powertools" from "setup-centos8.sh" in oap-project/velox.  i have tested successfully.

**Comment by zhejiangxiaomai** [comment]
Would you make a pr to fix it at https://github.com/facebookincubator/velox?

**Comment by sharkdtu** [comment]
@zhejiangxiaomai  OK
