### ISSUE TITLE
Gluten shuffle service supports Celeborn

### ISSUE THREAD

**Issue by kerwin-zk** [oap-project/gluten#999]
**Is your feature request related to a problem or challenge? Please describe what you are trying to do.**
Gluten shuffle service supports Celeborn

**Describe the solution you'd like**
- [x] Celeborn Hash Based Columnar Shuffle

**Comment by FelixYBW** [comment]
After split, arrow record batch is converted to arrow IPC format. We should send the IPC through arrow java API to remote shuffle service, then reducer get it from remote shuffle service and restore as arrow record batch.

Currently the reducer side isn't optimal yet. We have hit an issue both network and CPU isn't bottleneck. Looks something is synced there. root cause still not identified.

**Comment by baibaichen** [comment]
@kerwin-zk 
> Mapper side in Gluten is to receive the arrow IPC format through arrow::io::BufferOutputStream, then convert it into a jbytearray
Can we chat offline?

1. My initial idea was using protocol like grpc(or brpc) to avoid c++to java memory conversion, but netty is fine until we found memory copying is bottle neck
2. Since CK has its own buffer stream,  it's better that Celeborn provoids jbytearry related interfaces
3. By the way, we currently support converting columnar data to UnsafeRow's KV format.   we can try this first.

**Comment by kerwin-zk** [comment]
OK

**Comment by zhanglistar** [comment]
Why not design TCP protocol instead of other data format to archive high performance?

**Comment by zhanglistar** [comment]
> 

Yes, I think Celeborn should support C++ API for better performance.

**Comment by kerwin-zk** [comment]
> > 
> 
> Yes, I think Celeborn should support C++ API for better performance, then we can read or write data directly from native layer to instead of converting data to JVM layer.

We have also received requests from users to support other languages like python. We assessed that this means a lot of work for Celeborn. We suggest to evaluate the performance data scene after the first version is done. If the performance of reading and writing data is indeed bottleneck, let's discuss how to deal with it together.

**Comment by zhanglistar** [comment]
> > > 
> > 
> > 
> > Yes, I think Celeborn should support C++ API for better performance, then we can read or write data directly from native layer to instead of converting data to JVM layer.
> 
> We have also received requests from users to support other languages like python. We assessed that this means a lot of work for Celeborn. We suggest to evaluate the performance data scene after the first version is done. If the performance of reading and writing data is indeed bottleneck, let's discuss how to deal with it together.

Got it. Maybe it's not vital for overall duration, let's roll it out first.

**Comment by baibaichen** [comment]
> @kerwin-zk
> 
> > Mapper side in Gluten is to receive the arrow IPC format through arrow::io::BufferOutputStream, then convert it into a jbytearray
> 
> Can we chat offline?
> 
> 1. My initial idea was using protocol like grpc(or brpc) to avoid c++to java memory conversion, but netty is fine until we found memory copying is bottle neck
> 2. Since CK has its own buffer stream,  it's better that Celeborn provoids jbytearry related interfaces
> 3. By the way, we currently support converting columnar data to UnsafeRow's KV format.   we can try this first.

Actually,  UnsafeRow's KV format is  Product2<k, v>,  we customize an CHColumnarBatchSerializer through ShuffleDependency

**Comment by zhouyuan** [comment]
CC: @zuochunwei

**Comment by kerwin-zk** [comment]
Several key points of the current design for Celeborn Hash Based Columnar Shuffle.
- Map side
   - Create CelebornShuffleManager and ShuffleWriter in Gluten.
   - In the process of register shuffle, if it fails, it will fall back to GlutenColumnarShuffle.
   - During the Split process, the data will be pushed to Celebron when the buffer for SinglePartSplitter reaches the set threshold, and for other types of Splitter, when the Split Partition Buffer is insufficient, the data will be pushed to Celebron.
   - The specific push logic is to receive the arrow IPC format through arrow::io::BufferOutputStream, then convert it into a jbytearray, and finally call the Celeborn Java API on the native layer through JNI to send the data to Celeborn.
  - When the memory is insufficient, Spark will trigger Spill, and then push the largest Partition to Celebron to release the memory.
- Reduce side
   - use CelebornShuffleReader to read data
   - use GlutenColumnarBatchSerializer to deserialize stream.

cc @zhouyuan
